/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type { AnomaliaProdutividadeGetDataDto } from '../../model';

export const getGetAnomaliasResponseMock =
  (): AnomaliaProdutividadeGetDataDto[] =>
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.number.int({ min: -2147483648, max: 2147483647 }),
      demandaId: faker.number.int({ min: -2147483648, max: 2147483647 }),
      centerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      funcionarioId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      criadoPorId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      inicio: faker.string.alpha({ length: { min: 10, max: 20 } }),
      fim: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      caixas: faker.number.int({ min: -2147483648, max: 2147483647 }),
      unidades: faker.number.int({ min: -2147483648, max: 2147483647 }),
      paletes: faker.number.int({ min: -2147483648, max: 2147483647 }),
      enderecosVisitado: faker.number.int({
        min: -2147483648,
        max: 2147483647,
      }),
      produtividade: faker.number.float({
        min: -140737488355328,
        max: 140737488355327,
        fractionDigits: 2,
      }),
      motivoAnomalia: faker.string.alpha({ length: { min: 10, max: 20 } }),
      motivoAnomaliaDescricao: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      paletesNaDemanda: faker.number.int({ min: -2147483648, max: 2147483647 }),
    }));

export const getGetAnomaliasMockHandler = (
  overrideResponse?:
    | AnomaliaProdutividadeGetDataDto[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<AnomaliaProdutividadeGetDataDto[]>
        | AnomaliaProdutividadeGetDataDto[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/anomalias-produtividade/:centerId',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetAnomaliasResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};
export const getAnomaliasProdutividadeMock = () => [
  getGetAnomaliasMockHandler(),
];
