/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import zod from 'zod';


/**
 * @summary Adicionar check list
 */
export const addCheckListDevolucaoMobileParams = zod.object({
  "demandaId": zod.string()
})

export const addCheckListDevolucaoMobileBody = zod.object({
  "fotoBauAberto": zod.string().describe('Foto do baú aberto'),
  "fotoBauFechado": zod.string().describe('Foto do baú fechado'),
  "demandaId": zod.string(),
  "temperaturaBau": zod.string().describe('Temperatura do Baú'),
  "temperaturaProduto": zod.string().describe('Temperatura do Produto'),
  "anomalias": zod.string().optional()
})

export const addCheckListDevolucaoMobileResponse = zod.string()

/**
 * @summary Listar demandas em aberto
 */
export const listarDemandasEmAbertoDevolucaoMobileParams = zod.object({
  "centerId": zod.string()
})

export const listarDemandasEmAbertoDevolucaoMobileResponseIdMin = -2147483648;
export const listarDemandasEmAbertoDevolucaoMobileResponseIdMax = 2147483647;export const listarDemandasEmAbertoDevolucaoMobileResponseQuantidadePaletesMinOne = -2147483648;
export const listarDemandasEmAbertoDevolucaoMobileResponseQuantidadePaletesMaxOne = 2147483647;export const listarDemandasEmAbertoDevolucaoMobileResponsePaletesRecebidosMinOne = -2147483648;
export const listarDemandasEmAbertoDevolucaoMobileResponsePaletesRecebidosMaxOne = 2147483647;

export const listarDemandasEmAbertoDevolucaoMobileResponseItem = zod.object({
  "id": zod.number().min(listarDemandasEmAbertoDevolucaoMobileResponseIdMin).max(listarDemandasEmAbertoDevolucaoMobileResponseIdMax),
  "placa": zod.string(),
  "motorista": zod.string(),
  "idTransportadora": zod.union([zod.string(),zod.null()]),
  "telefone": zod.union([zod.string(),zod.null()]),
  "cargaSegregada": zod.boolean(),
  "quantidadePaletes": zod.union([zod.number().min(listarDemandasEmAbertoDevolucaoMobileResponseQuantidadePaletesMinOne).max(listarDemandasEmAbertoDevolucaoMobileResponseQuantidadePaletesMaxOne),zod.null()]),
  "doca": zod.union([zod.string(),zod.null()]),
  "centerId": zod.string(),
  "adicionadoPorId": zod.string(),
  "conferenteId": zod.union([zod.string(),zod.null()]),
  "criadoEm": zod.string(),
  "atualizadoEm": zod.string(),
  "status": zod.enum(['AGUARDANDO_LIBERACAO', 'AGUARDANDO_CONFERENCIA', 'EM_CONFERENCIA', 'CONFERENCIA_FINALIZADA', 'FINALIZADO', 'CANCELADO']),
  "fechouComAnomalia": zod.union([zod.boolean(),zod.null()]),
  "liberadoParaConferenciaEm": zod.union([zod.string(),zod.null()]),
  "inicioConferenciaEm": zod.union([zod.string(),zod.null()]),
  "fimConferenciaEm": zod.union([zod.string(),zod.null()]),
  "finalizadoEm": zod.union([zod.string(),zod.null()]),
  "senha": zod.string(),
  "viagemId": zod.union([zod.string(),zod.null()]),
  "transporte": zod.union([zod.string(),zod.null()]),
  "paletesRecebidos": zod.union([zod.number().min(listarDemandasEmAbertoDevolucaoMobileResponsePaletesRecebidosMinOne).max(listarDemandasEmAbertoDevolucaoMobileResponsePaletesRecebidosMaxOne),zod.null()])
})
export const listarDemandasEmAbertoDevolucaoMobileResponse = zod.array(listarDemandasEmAbertoDevolucaoMobileResponseItem)

/**
 * @summary Iniciar conferência
 */
export const startDemandaDevolucaoMobileParams = zod.object({
  "demandaId": zod.string()
})

export const startDemandaDevolucaoMobileResponse = zod.string()

/**
 * @summary Listar itens contabilizados
 */
export const getItensContabilDevolucaoMobileParams = zod.object({
  "demandaId": zod.string()
})

export const getItensContabilDevolucaoMobileResponseItem = zod.object({
  "demandaId": zod.number(),
  "sku": zod.string(),
  "descricao": zod.string(),
  "tipo": zod.enum(['CONTABIL', 'FISICO']),
  "tipoDevolucao": zod.enum(['RETORNO', 'REENTREGA']),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "avariaCaixas": zod.number(),
  "avariaUnidades": zod.number()
})
export const getItensContabilDevolucaoMobileResponse = zod.array(getItensContabilDevolucaoMobileResponseItem)

