/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AddCheckListDto,
  ItensContabilDto,
  ListarDemandasDto,
} from '../../model';

import { axiosFetcher } from '../../../http/axios.http';
import type { ErrorType, BodyType } from '../../../http/axios.http';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Adicionar check list
 */
export const addCheckListDevolucaoMobile = (
  demandaId: string,
  addCheckListDto: BodyType<AddCheckListDto>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<string>(
    {
      url: `/api/devolucao-mobile/add-check-list/${demandaId}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addCheckListDto,
      signal,
    },
    options,
  );
};

export const getAddCheckListDevolucaoMobileMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>,
    TError,
    { demandaId: string; data: BodyType<AddCheckListDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>,
  TError,
  { demandaId: string; data: BodyType<AddCheckListDto> },
  TContext
> => {
  const mutationKey = ['addCheckListDevolucaoMobile'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>,
    { demandaId: string; data: BodyType<AddCheckListDto> }
  > = (props) => {
    const { demandaId, data } = props ?? {};

    return addCheckListDevolucaoMobile(demandaId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddCheckListDevolucaoMobileMutationResult = NonNullable<
  Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>
>;
export type AddCheckListDevolucaoMobileMutationBody = BodyType<AddCheckListDto>;
export type AddCheckListDevolucaoMobileMutationError = ErrorType<unknown>;

/**
 * @summary Adicionar check list
 */
export const useAddCheckListDevolucaoMobile = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>,
      TError,
      { demandaId: string; data: BodyType<AddCheckListDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addCheckListDevolucaoMobile>>,
  TError,
  { demandaId: string; data: BodyType<AddCheckListDto> },
  TContext
> => {
  const mutationOptions =
    getAddCheckListDevolucaoMobileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Listar demandas em aberto
 */
export const listarDemandasEmAbertoDevolucaoMobile = (
  centerId: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<ListarDemandasDto[]>(
    {
      url: `/api/devolucao-mobile/listar-demandas-em-aberto/${centerId}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getListarDemandasEmAbertoDevolucaoMobileQueryKey = (
  centerId?: string,
) => {
  return [
    `/api/devolucao-mobile/listar-demandas-em-aberto/${centerId}`,
  ] as const;
};

export const getListarDemandasEmAbertoDevolucaoMobileQueryOptions = <
  TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getListarDemandasEmAbertoDevolucaoMobileQueryKey(centerId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>
  > = ({ signal }) =>
    listarDemandasEmAbertoDevolucaoMobile(centerId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!centerId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListarDemandasEmAbertoDevolucaoMobileQueryResult = NonNullable<
  Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>
>;
export type ListarDemandasEmAbertoDevolucaoMobileQueryError =
  ErrorType<unknown>;

export function useListarDemandasEmAbertoDevolucaoMobile<
  TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
          TError,
          Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListarDemandasEmAbertoDevolucaoMobile<
  TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
          TError,
          Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListarDemandasEmAbertoDevolucaoMobile<
  TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Listar demandas em aberto
 */

export function useListarDemandasEmAbertoDevolucaoMobile<
  TData = Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listarDemandasEmAbertoDevolucaoMobile>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListarDemandasEmAbertoDevolucaoMobileQueryOptions(
    centerId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Iniciar conferência
 */
export const startDemandaDevolucaoMobile = (
  demandaId: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<string>(
    {
      url: `/api/devolucao-mobile/start-demanda/${demandaId}`,
      method: 'POST',
      signal,
    },
    options,
  );
};

export const getStartDemandaDevolucaoMobileMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>,
    TError,
    { demandaId: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>,
  TError,
  { demandaId: string },
  TContext
> => {
  const mutationKey = ['startDemandaDevolucaoMobile'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>,
    { demandaId: string }
  > = (props) => {
    const { demandaId } = props ?? {};

    return startDemandaDevolucaoMobile(demandaId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type StartDemandaDevolucaoMobileMutationResult = NonNullable<
  Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>
>;

export type StartDemandaDevolucaoMobileMutationError = ErrorType<unknown>;

/**
 * @summary Iniciar conferência
 */
export const useStartDemandaDevolucaoMobile = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>,
      TError,
      { demandaId: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof startDemandaDevolucaoMobile>>,
  TError,
  { demandaId: string },
  TContext
> => {
  const mutationOptions =
    getStartDemandaDevolucaoMobileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Listar itens contabilizados
 */
export const getItensContabilDevolucaoMobile = (
  demandaId: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<ItensContabilDto[]>(
    {
      url: `/api/devolucao-mobile/get-itens-contabil/${demandaId}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getGetItensContabilDevolucaoMobileQueryKey = (
  demandaId?: string,
) => {
  return [`/api/devolucao-mobile/get-itens-contabil/${demandaId}`] as const;
};

export const getGetItensContabilDevolucaoMobileQueryOptions = <
  TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
  TError = ErrorType<unknown>,
>(
  demandaId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetItensContabilDevolucaoMobileQueryKey(demandaId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>
  > = ({ signal }) =>
    getItensContabilDevolucaoMobile(demandaId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!demandaId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetItensContabilDevolucaoMobileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>
>;
export type GetItensContabilDevolucaoMobileQueryError = ErrorType<unknown>;

export function useGetItensContabilDevolucaoMobile<
  TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
  TError = ErrorType<unknown>,
>(
  demandaId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
          TError,
          Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetItensContabilDevolucaoMobile<
  TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
  TError = ErrorType<unknown>,
>(
  demandaId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
          TError,
          Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetItensContabilDevolucaoMobile<
  TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
  TError = ErrorType<unknown>,
>(
  demandaId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Listar itens contabilizados
 */

export function useGetItensContabilDevolucaoMobile<
  TData = Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
  TError = ErrorType<unknown>,
>(
  demandaId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getItensContabilDevolucaoMobile>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetItensContabilDevolucaoMobileQueryOptions(
    demandaId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
