/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import zod from 'zod';

/**
 * @summary Criar uma nova demanda
 */
export const criarDemandaProdutividadeBody = zod.object({
  funcionarioId: zod.string(),
  paletesIds: zod.array(zod.string()),
  centerId: zod.string(),
  processo: zod.enum(['SEPARACAO', 'CARREGAMENTO', 'CONFERENCIA']),
  inicio: zod.string(),
  obs: zod.string().optional(),
  turno: zod.enum(['MANHA', 'TARDE', 'NOITE']),
});

/**
 * @summary Adicionar paletes a uma produtividade existente
 */
export const adicionarPaletesBodyItem = zod.object({
  transporteId: zod.string(),
  id: zod.string(),
  empresa: zod.string(),
  quantidadeCaixas: zod.number(),
  quantidadeUnidades: zod.number(),
  quantidadePaletes: zod.number(),
  enderecoVisitado: zod.number(),
  segmento: zod.string(),
  tipoProcesso: zod.string(),
});
export const adicionarPaletesBody = zod.array(adicionarPaletesBodyItem);

/**
 * @summary Finalizar uma produtividade existente
 */
export const finalizarProdutividadeParams = zod.object({
  paleteId: zod.string(),
});

/**
 * @summary Inicia uma nova pausa para a demanda associada a um palete
 */
export const iniciarPausaParams = zod.object({
  paleteId: zod.string(),
});

export const iniciarPausaBody = zod.object({
  inicio: zod.string(),
  fim: zod.string().optional(),
  motivo: zod.string().optional(),
  descricao: zod.string().optional(),
  demandaId: zod.string(),
  registradoPorId: zod.string(),
  pausaGeralId: zod.union([zod.string(), zod.null()]).optional(),
});

/**
 * @summary Finaliza pausa para a demanda associada a um palete
 */
export const finalizarPausaParams = zod.object({
  paleteId: zod.string(),
});

/**
 * @summary Deletar uma demanda com base no palete Id
 */
export const deletarPaleteParams = zod.object({
  paleteId: zod.string(),
});

export const produtividadeControllerFindAllParams = zod.object({
  id: zod.string(),
});

export const produtividadeControllerFindAllQueryParams = zod.object({
  processo: zod.union([zod.string(), zod.null()]).optional(),
  turno: zod
    .union([zod.enum(['MANHA', 'TARDE', 'NOITE']), zod.null()])
    .optional(),
  tipoProcesso: zod
    .union([zod.enum(['SEPARACAO', 'CARREGAMENTO', 'CONFERENCIA']), zod.null()])
    .optional(),
  status: zod
    .union([
      zod.enum(['NAO_INICIADO', 'EM_PROGRESSO', 'CONCLUIDO', 'EM_PAUSA']),
      zod.null(),
    ])
    .optional(),
  empresa: zod.union([zod.enum(['LDB', 'ITB', 'DPA']), zod.null()]).optional(),
});
