/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import zod from 'zod';


/**
 * @summary criar usuario
 */
export const criarUsuarioBody = zod.object({
  "centerId": zod.string(),
  "id": zod.string(),
  "name": zod.string(),
  "primeiroNome": zod.string().optional(),
  "ultimoNome": zod.string().optional(),
  "credencial": zod.string().optional(),
  "turno": zod.enum(['MANHA', 'TARDE', 'NOITE', 'INTERMEDIARIO', 'ADMINISTRATIVO']),
  "processo": zod.string().optional(),
  "empresa": zod.string(),
  "role": zod.enum(['FUNCIONARIO', 'USER', 'ADMIN', 'MASTER']).optional(),
  "roles": zod.union([zod.array(zod.string()),zod.null()]).optional()
})

export const criarUsuarioResponse = zod.object({
  "centerId": zod.string(),
  "id": zod.string(),
  "name": zod.string(),
  "turno": zod.enum(['MANHA', 'TARDE', 'NOITE', 'INTERMEDIARIO', 'ADMINISTRATIVO']),
  "empresa": zod.string(),
  "roles": zod.array(zod.string())
})

/**
 * @summary criar usuario em massa
 */
export const criarUsuarioEmMassaBodyItem = zod.object({
  "centerId": zod.string(),
  "id": zod.string(),
  "name": zod.string(),
  "primeiroNome": zod.string().optional(),
  "ultimoNome": zod.string().optional(),
  "credencial": zod.string().optional(),
  "turno": zod.enum(['MANHA', 'TARDE', 'NOITE', 'INTERMEDIARIO', 'ADMINISTRATIVO']),
  "processo": zod.string().optional(),
  "empresa": zod.string(),
  "role": zod.enum(['FUNCIONARIO', 'USER', 'ADMIN', 'MASTER']).optional(),
  "roles": zod.union([zod.array(zod.string()),zod.null()]).optional()
})
export const criarUsuarioEmMassaBody = zod.array(criarUsuarioEmMassaBodyItem)

/**
 * @summary usuario
 */
export const listarUsuariosParams = zod.object({
  "centerId": zod.string()
})

export const listarUsuariosQueryParams = zod.object({
  "role": zod.union([zod.enum(['FUNCIONARIO', 'USER', 'ADMIN', 'MASTER']),zod.null()]).optional(),
  "processo": zod.union([zod.string(),zod.null()]).optional(),
  "search": zod.union([zod.string(),zod.null()]).optional()
})

export const listarUsuariosResponseItem = zod.object({
  "centerId": zod.string(),
  "id": zod.string(),
  "name": zod.string(),
  "turno": zod.enum(['MANHA', 'TARDE', 'NOITE', 'INTERMEDIARIO', 'ADMINISTRATIVO']),
  "empresa": zod.string(),
  "roles": zod.array(zod.string())
})
export const listarUsuariosResponse = zod.array(listarUsuariosResponseItem)

export const userControllerInfoMeResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "empresa": zod.enum(['LDB', 'ITB', 'DPA']),
  "roles": zod.array(zod.string())
})

/**
 * @summary Buscar roles
 */
export const getRolesResponseItem = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "composite": zod.boolean(),
  "clientRole": zod.boolean(),
  "containerId": zod.string()
})
export const getRolesResponse = zod.array(getRolesResponseItem)

/**
 * @summary Criar nova Role
 */
export const criarRoleParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Deletar Usuario
 */
export const deletarUsuarioParams = zod.object({
  "id": zod.string(),
  "centerId": zod.string()
})

/**
 * @summary Atualizar Usuario
 */
export const atualizarUsuarioParams = zod.object({
  "id": zod.string()
})

export const atualizarUsuarioBody = zod.object({
  "name": zod.string(),
  "turno": zod.enum(['MANHA', 'TARDE', 'NOITE', 'INTERMEDIARIO', 'ADMINISTRATIVO'])
})

/**
 * @summary Resetar senha
 */
export const resetarSenhaParams = zod.object({
  "id": zod.string(),
  "password": zod.string()
})

/**
 * @summary Atualizar permissões
 */
export const atualizarPermissoesParams = zod.object({
  "id": zod.string(),
  "centerId": zod.string()
})

export const atualizarPermissoesBodyItem = zod.string()
export const atualizarPermissoesBody = zod.array(atualizarPermissoesBodyItem)

/**
 * @summary Buscar todas as permissões por centro
 */
export const buscarTodasPermissoesPorCentroParams = zod.object({
  "userId": zod.string(),
  "centerId": zod.string()
})

export const buscarTodasPermissoesPorCentroResponseItem = zod.string()
export const buscarTodasPermissoesPorCentroResponse = zod.array(buscarTodasPermissoesPorCentroResponseItem)

/**
 * @summary Encerrar sessão
 */
export const encerrarSessaoParams = zod.object({
  "userId": zod.string()
})

