/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { InventarioDto } from '../../model';

import { axiosFetcher } from '../../../http/axios.http';
import type { ErrorType, BodyType } from '../../../http/axios.http';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Buscar inventário por centro e data
 */
export const getInventariosByCenterAndData = (
  centerId: string,
  data: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<InventarioDto[]>(
    {
      url: `/api/estoque/get-inventarios-by-center-and-data/${centerId}/${data}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getGetInventariosByCenterAndDataQueryKey = (
  centerId?: string,
  data?: string,
) => {
  return [
    `/api/estoque/get-inventarios-by-center-and-data/${centerId}/${data}`,
  ] as const;
};

export const getGetInventariosByCenterAndDataQueryOptions = <
  TData = Awaited<ReturnType<typeof getInventariosByCenterAndData>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  data: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventariosByCenterAndData>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetInventariosByCenterAndDataQueryKey(centerId, data);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getInventariosByCenterAndData>>
  > = ({ signal }) =>
    getInventariosByCenterAndData(centerId, data, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(centerId && data),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getInventariosByCenterAndData>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetInventariosByCenterAndDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getInventariosByCenterAndData>>
>;
export type GetInventariosByCenterAndDataQueryError = ErrorType<
  void | void | void | void | void | void
>;

export function useGetInventariosByCenterAndData<
  TData = Awaited<ReturnType<typeof getInventariosByCenterAndData>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  data: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventariosByCenterAndData>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInventariosByCenterAndData>>,
          TError,
          Awaited<ReturnType<typeof getInventariosByCenterAndData>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetInventariosByCenterAndData<
  TData = Awaited<ReturnType<typeof getInventariosByCenterAndData>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  data: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventariosByCenterAndData>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInventariosByCenterAndData>>,
          TError,
          Awaited<ReturnType<typeof getInventariosByCenterAndData>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetInventariosByCenterAndData<
  TData = Awaited<ReturnType<typeof getInventariosByCenterAndData>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  data: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventariosByCenterAndData>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar inventário por centro e data
 */

export function useGetInventariosByCenterAndData<
  TData = Awaited<ReturnType<typeof getInventariosByCenterAndData>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  data: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventariosByCenterAndData>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetInventariosByCenterAndDataQueryOptions(
    centerId,
    data,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Criar inventário
 */
export const createInventario = (
  centerId: string,
  inventarioDto: BodyType<InventarioDto>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<string>(
    {
      url: `/api/estoque/create-inventario/${centerId}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: inventarioDto,
      signal,
    },
    options,
  );
};

export const getCreateInventarioMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createInventario>>,
    TError,
    { centerId: string; data: BodyType<InventarioDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createInventario>>,
  TError,
  { centerId: string; data: BodyType<InventarioDto> },
  TContext
> => {
  const mutationKey = ['createInventario'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createInventario>>,
    { centerId: string; data: BodyType<InventarioDto> }
  > = (props) => {
    const { centerId, data } = props ?? {};

    return createInventario(centerId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateInventarioMutationResult = NonNullable<
  Awaited<ReturnType<typeof createInventario>>
>;
export type CreateInventarioMutationBody = BodyType<InventarioDto>;
export type CreateInventarioMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Criar inventário
 */
export const useCreateInventario = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createInventario>>,
      TError,
      { centerId: string; data: BodyType<InventarioDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createInventario>>,
  TError,
  { centerId: string; data: BodyType<InventarioDto> },
  TContext
> => {
  const mutationOptions = getCreateInventarioMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Atualizar inventário
 */
export const updateInventario = (
  id: string,
  inventarioDto: BodyType<InventarioDto>,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<string>(
    {
      url: `/api/estoque/update/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: inventarioDto,
    },
    options,
  );
};

export const getUpdateInventarioMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateInventario>>,
    TError,
    { id: string; data: BodyType<InventarioDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateInventario>>,
  TError,
  { id: string; data: BodyType<InventarioDto> },
  TContext
> => {
  const mutationKey = ['updateInventario'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateInventario>>,
    { id: string; data: BodyType<InventarioDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateInventario(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateInventarioMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateInventario>>
>;
export type UpdateInventarioMutationBody = BodyType<InventarioDto>;
export type UpdateInventarioMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Atualizar inventário
 */
export const useUpdateInventario = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateInventario>>,
      TError,
      { id: string; data: BodyType<InventarioDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateInventario>>,
  TError,
  { id: string; data: BodyType<InventarioDto> },
  TContext
> => {
  const mutationOptions = getUpdateInventarioMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Deletar inventário
 */
export const deleteInventario = (
  id: string,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<boolean>(
    { url: `/api/estoque/delete/${id}`, method: 'DELETE' },
    options,
  );
};

export const getDeleteInventarioMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteInventario>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteInventario>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteInventario'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteInventario>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteInventario(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteInventarioMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteInventario>>
>;

export type DeleteInventarioMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Deletar inventário
 */
export const useDeleteInventario = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteInventario>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteInventario>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteInventarioMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Buscar inventário por ID
 */
export const getInventarioById = (
  id: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<InventarioDto>(
    { url: `/api/estoque/get-inventario-by-id/${id}`, method: 'GET', signal },
    options,
  );
};

export const getGetInventarioByIdQueryKey = (id?: string) => {
  return [`/api/estoque/get-inventario-by-id/${id}`] as const;
};

export const getGetInventarioByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getInventarioById>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventarioById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetInventarioByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getInventarioById>>
  > = ({ signal }) => getInventarioById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getInventarioById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetInventarioByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getInventarioById>>
>;
export type GetInventarioByIdQueryError = ErrorType<
  void | void | void | void | void | void
>;

export function useGetInventarioById<
  TData = Awaited<ReturnType<typeof getInventarioById>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventarioById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInventarioById>>,
          TError,
          Awaited<ReturnType<typeof getInventarioById>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetInventarioById<
  TData = Awaited<ReturnType<typeof getInventarioById>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventarioById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInventarioById>>,
          TError,
          Awaited<ReturnType<typeof getInventarioById>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetInventarioById<
  TData = Awaited<ReturnType<typeof getInventarioById>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventarioById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar inventário por ID
 */

export function useGetInventarioById<
  TData = Awaited<ReturnType<typeof getInventarioById>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventarioById>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetInventarioByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
