/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import zod from 'zod';


/**
 * @summary Criar uma nova demanda de produtividade
 */
export const criarDemandaProdutividadeBodyIdMin = -2147483648;
export const criarDemandaProdutividadeBodyIdMax = 2147483647;export const criarDemandaProdutividadeBodyPaletesIdsDefault = [];

export const criarDemandaProdutividadeBody = zod.object({
  "id": zod.number().min(criarDemandaProdutividadeBodyIdMin).max(criarDemandaProdutividadeBodyIdMax).optional(),
  "processo": zod.enum(['SEPARACAO', 'CARREGAMENTO', 'CONFERENCIA']),
  "fim": zod.union([zod.string(),zod.null()]).optional(),
  "status": zod.enum(['EM_PROGRESSO', 'FINALIZADA', 'PAUSA', 'CANCELADA']).optional(),
  "turno": zod.enum(['MANHA', 'TARDE', 'NOITE', 'INTERMEDIARIO', 'ADMINISTRATIVO']),
  "funcionarioId": zod.string(),
  "criadoEm": zod.string().optional(),
  "centerId": zod.string(),
  "obs": zod.union([zod.string(),zod.null()]).optional(),
  "dataExpedicao": zod.string().optional(),
  "paletesIds": zod.array(zod.string()).default(criarDemandaProdutividadeBodyPaletesIdsDefault)
})

/**
 * @summary Finalizar uma palete de uma demanda de produtividade
 */
export const finalizarPaleteProdutividadeBodyItem = zod.string()
export const finalizarPaleteProdutividadeBody = zod.array(finalizarPaleteProdutividadeBodyItem)

/**
 * @summary Adicionar uma pausa individual a uma demanda de produtividade
 */
export const addPausaIndividualParams = zod.object({
  "paleteId": zod.string()
})

export const addPausaIndividualBodyIdMin = -2147483648;
export const addPausaIndividualBodyIdMax = 2147483647;export const addPausaIndividualBodyPausaGeralIdMinOne = -2147483648;
export const addPausaIndividualBodyPausaGeralIdMaxOne = 2147483647;

export const addPausaIndividualBody = zod.object({
  "id": zod.number().min(addPausaIndividualBodyIdMin).max(addPausaIndividualBodyIdMax).optional(),
  "inicio": zod.string(),
  "fim": zod.union([zod.string(),zod.null()]).optional(),
  "motivo": zod.string(),
  "descricao": zod.union([zod.string(),zod.null()]).optional(),
  "pausaGeralId": zod.union([zod.number().min(addPausaIndividualBodyPausaGeralIdMinOne).max(addPausaIndividualBodyPausaGeralIdMaxOne),zod.null()]).optional()
})

/**
 * @summary Finalizar uma pausa individual de uma demanda de produtividade
 */
export const finalizarPausaIndividualParams = zod.object({
  "paleteId": zod.string()
})

/**
 * @summary Adicionar uma pausa geral a uma demanda de produtividade
 */
export const addPausaGeralBody = zod.object({
  "inicio": zod.string(),
  "fim": zod.union([zod.string(),zod.null()]).optional(),
  "motivo": zod.string(),
  "centerId": zod.string(),
  "processo": zod.enum(['SEPARACAO', 'CARREGAMENTO', 'CONFERENCIA']),
  "turno": zod.enum(['MANHA', 'TARDE', 'NOITE', 'INTERMEDIARIO', 'ADMINISTRATIVO']),
  "criadoEm": zod.string().optional(),
  "segmento": zod.string()
})

/**
 * @summary Finalizar uma pausa geral a uma demanda de produtividade
 */
export const finalizarPausaGeralParams = zod.object({
  "centerId": zod.string(),
  "segmento": zod.string(),
  "turno": zod.string(),
  "processo": zod.string()
})

/**
 * @summary Buscar as pausas ativas de uma demanda de produtividade
 */
export const buscarPausasAtivasParams = zod.object({
  "centerId": zod.string()
})

export const buscarPausasAtivasQueryIdMin = -2147483648;
export const buscarPausasAtivasQueryIdMax = 2147483647;

export const buscarPausasAtivasQueryParams = zod.object({
  "id": zod.number().min(buscarPausasAtivasQueryIdMin).max(buscarPausasAtivasQueryIdMax).optional(),
  "inicio": zod.string().optional(),
  "fim": zod.union([zod.string(),zod.null()]).optional(),
  "motivo": zod.string().optional(),
  "processo": zod.enum(['SEPARACAO', 'CARREGAMENTO', 'CONFERENCIA']).optional(),
  "turno": zod.enum(['MANHA', 'TARDE', 'NOITE', 'INTERMEDIARIO', 'ADMINISTRATIVO']).optional(),
  "registradoPorId": zod.string().optional(),
  "criadoEm": zod.string().optional(),
  "atualizadoEm": zod.string().optional(),
  "segmento": zod.string().optional(),
  "ativo": zod.enum(['true', 'false']).optional()
})

export const buscarPausasAtivasResponseIdMin = -2147483648;
export const buscarPausasAtivasResponseIdMax = 2147483647;

export const buscarPausasAtivasResponseItem = zod.object({
  "id": zod.number().min(buscarPausasAtivasResponseIdMin).max(buscarPausasAtivasResponseIdMax),
  "inicio": zod.string(),
  "fim": zod.union([zod.string(),zod.null()]),
  "motivo": zod.string(),
  "centerId": zod.string(),
  "processo": zod.enum(['SEPARACAO', 'CARREGAMENTO', 'CONFERENCIA']),
  "turno": zod.enum(['MANHA', 'TARDE', 'NOITE', 'INTERMEDIARIO', 'ADMINISTRATIVO']),
  "registradoPorId": zod.string(),
  "criadoEm": zod.string(),
  "atualizadoEm": zod.string(),
  "segmento": zod.string()
})
export const buscarPausasAtivasResponse = zod.array(buscarPausasAtivasResponseItem)

/**
 * @summary Buscar a produtividade melhoria continua
 */
export const getProdutividadeMelhoriaContinuaParams = zod.object({
  "dataInicial": zod.string(),
  "dataFinal": zod.string()
})

export const getProdutividadeMelhoriaContinuaResponseItem = zod.object({
  "data": zod.string(),
  "id_funcionario": zod.string(),
  "unidade": zod.string(),
  "nome_funcionario": zod.string(),
  "turno": zod.string(),
  "caixas": zod.number()
})
export const getProdutividadeMelhoriaContinuaResponse = zod.array(getProdutividadeMelhoriaContinuaResponseItem)

/**
 * @summary Buscar a produtividade de uma demanda de produtividade
 */
export const getProdutividadeParams = zod.object({
  "centerId": zod.string()
})

export const getProdutividadeResponseItem = zod.object({
  "idDemanda": zod.number(),
  "empresa": zod.string(),
  "centerId": zod.string(),
  "processo": zod.string(),
  "segmento": zod.string(),
  "inicio": zod.string(),
  "fim": zod.union([zod.string(),zod.null()]),
  "cadastradoPorId": zod.string(),
  "turno": zod.string(),
  "funcionarioId": zod.string(),
  "nomeFuncionario": zod.string(),
  "statusDemanda": zod.string(),
  "caixas": zod.number(),
  "unidades": zod.number(),
  "paletes": zod.number(),
  "visitas": zod.number(),
  "pausas": zod.number(),
  "tempoTrabalhado": zod.number(),
  "tempoPausas": zod.number(),
  "tempoTotal": zod.number(),
  "produtividade": zod.number(),
  "obs": zod.union([zod.string(),zod.null()])
})
export const getProdutividadeResponse = zod.array(getProdutividadeResponseItem)

/**
 * @summary Buscar a visão geral da produtividade
 */
export const overViewProdutividadeParams = zod.object({
  "centerId": zod.string(),
  "processo": zod.string(),
  "dataRegistro": zod.string()
})

export const overViewProdutividadeResponse = zod.object({
  "processos": zod.number(),
  "emAndamento": zod.number(),
  "concluidos": zod.number(),
  "totalCaixas": zod.number(),
  "totalUnidades": zod.number(),
  "produtividade": zod.number()
})

/**
 * @summary Buscar a produtividade de uma demanda de produtividade por ID
 */
export const getProdutividadeByIdParams = zod.object({
  "idDemanda": zod.string()
})

export const getProdutividadeByIdResponse = zod.object({
  "idDemanda": zod.number(),
  "empresa": zod.string(),
  "centerId": zod.string(),
  "processo": zod.string(),
  "segmento": zod.string(),
  "inicio": zod.string(),
  "fim": zod.union([zod.string(),zod.null()]),
  "cadastradoPorId": zod.string(),
  "turno": zod.string(),
  "funcionarioId": zod.string(),
  "nomeFuncionario": zod.string(),
  "statusDemanda": zod.string(),
  "caixas": zod.number(),
  "unidades": zod.number(),
  "paletes": zod.number(),
  "visitas": zod.number(),
  "pausas": zod.number(),
  "tempoTrabalhado": zod.number(),
  "tempoPausas": zod.number(),
  "tempoTotal": zod.number(),
  "produtividade": zod.number(),
  "obs": zod.union([zod.string(),zod.null()]),
  "listaPausas": zod.array(zod.object({
  "id": zod.number(),
  "inicio": zod.string(),
  "fim": zod.union([zod.string(),zod.null()]),
  "motivo": zod.string(),
  "descricao": zod.union([zod.string(),zod.null()]),
  "demandaId": zod.number(),
  "registradoPorId": zod.string()
})),
  "listaPaletes": zod.array(zod.object({
  "id": zod.string(),
  "empresa": zod.string(),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "quantidadePaletes": zod.number(),
  "enderecoVisitado": zod.number(),
  "segmento": zod.string(),
  "transporteId": zod.string(),
  "inicio": zod.union([zod.string(),zod.null()]),
  "fim": zod.union([zod.string(),zod.null()]),
  "tipoProcesso": zod.string(),
  "criadoEm": zod.string(),
  "atualizadoEm": zod.string(),
  "demandaId": zod.union([zod.number(),zod.null()]),
  "status": zod.string(),
  "validado": zod.boolean(),
  "criadoPorId": zod.string()
}))
})

/**
 * @summary Deletar uma demanda de produtividade
 */
export const deletarDemandaParams = zod.object({
  "paleteId": zod.string()
})

/**
 * @summary Deletar uma demanda de produtividade por ID
 */
export const deletarDemandaAnomaliaParams = zod.object({
  "idDemanda": zod.string()
})

/**
 * @summary Buscar uma demanda de produtividade por ID
 */
export const getDemandaByIdParams = zod.object({
  "idDemanda": zod.string()
})

export const getDemandaByIdResponse = zod.object({
  "idDemanda": zod.number(),
  "processo": zod.enum(['SEPARACAO', 'CARREGAMENTO', 'CONFERENCIA']),
  "status": zod.enum(['EM_PROGRESSO', 'FINALIZADA', 'PAUSA', 'CANCELADA']),
  "funcionarioId": zod.string(),
  "centerId": zod.string(),
  "dataExpedicao": zod.string(),
  "paletes": zod.array(zod.object({
  "id": zod.string(),
  "empresa": zod.string(),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "quantidadePaletes": zod.number(),
  "enderecoVisitado": zod.number(),
  "transporteId": zod.string(),
  "tipoProcesso": zod.enum(['SEPARACAO', 'CARREGAMENTO', 'CONFERENCIA']),
  "status": zod.enum(['NAO_INICIADO', 'EM_PROGRESSO', 'CONCLUIDO', 'EM_PAUSA'])
}))
})

