/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import zod from 'zod';


/**
 * @summary Criar uma movimentação
 */
export const criarNovaMovimentacaoBodyIdMovMin = -2147483648;
export const criarNovaMovimentacaoBodyIdMovMax = 2147483647;export const criarNovaMovimentacaoBodyPaleteMax = 50;export const criarNovaMovimentacaoBodyOrigemMaxOne = 50;export const criarNovaMovimentacaoBodyDestinoMaxOne = 50;export const criarNovaMovimentacaoBodyPrioridadeMin = -2147483648;
export const criarNovaMovimentacaoBodyPrioridadeMax = 2147483647;export const criarNovaMovimentacaoBodyStatusMaxOne = 20;

export const criarNovaMovimentacaoBodyItem = zod.object({
  "idMov": zod.number().min(criarNovaMovimentacaoBodyIdMovMin).max(criarNovaMovimentacaoBodyIdMovMax).optional(),
  "idUsuario": zod.union([zod.string(),zod.null()]).optional(),
  "idCentro": zod.string(),
  "palete": zod.string().max(criarNovaMovimentacaoBodyPaleteMax),
  "origem": zod.union([zod.string().max(criarNovaMovimentacaoBodyOrigemMaxOne),zod.null()]).optional(),
  "destino": zod.union([zod.string().max(criarNovaMovimentacaoBodyDestinoMaxOne),zod.null()]).optional(),
  "prioridade": zod.number().min(criarNovaMovimentacaoBodyPrioridadeMin).max(criarNovaMovimentacaoBodyPrioridadeMax),
  "status": zod.union([zod.string().max(criarNovaMovimentacaoBodyStatusMaxOne),zod.null()]).optional(),
  "dataCriacao": zod.union([zod.string(),zod.null()]).optional(),
  "dataExecucao": zod.union([zod.string(),zod.null()]).optional(),
  "sku": zod.union([zod.string(),zod.null()]).optional(),
  "descricao": zod.union([zod.string(),zod.null()]).optional(),
  "lote": zod.union([zod.string(),zod.null()]).optional(),
  "executadoPor": zod.union([zod.string(),zod.null()]).optional(),
  "iniciado": zod.union([zod.string(),zod.null()]).optional()
})
export const criarNovaMovimentacaoBody = zod.array(criarNovaMovimentacaoBodyItem)

export const criarNovaMovimentacaoResponseIdMovMin = -2147483648;
export const criarNovaMovimentacaoResponseIdMovMax = 2147483647;export const criarNovaMovimentacaoResponsePaleteMax = 50;export const criarNovaMovimentacaoResponseOrigemMaxOne = 50;export const criarNovaMovimentacaoResponseDestinoMaxOne = 50;export const criarNovaMovimentacaoResponsePrioridadeMin = -2147483648;
export const criarNovaMovimentacaoResponsePrioridadeMax = 2147483647;export const criarNovaMovimentacaoResponseStatusMaxOne = 20;

export const criarNovaMovimentacaoResponse = zod.object({
  "idMov": zod.number().min(criarNovaMovimentacaoResponseIdMovMin).max(criarNovaMovimentacaoResponseIdMovMax),
  "idUsuario": zod.union([zod.string(),zod.null()]),
  "idCentro": zod.string(),
  "palete": zod.string().max(criarNovaMovimentacaoResponsePaleteMax),
  "origem": zod.union([zod.string().max(criarNovaMovimentacaoResponseOrigemMaxOne),zod.null()]),
  "destino": zod.union([zod.string().max(criarNovaMovimentacaoResponseDestinoMaxOne),zod.null()]),
  "prioridade": zod.number().min(criarNovaMovimentacaoResponsePrioridadeMin).max(criarNovaMovimentacaoResponsePrioridadeMax),
  "status": zod.union([zod.string().max(criarNovaMovimentacaoResponseStatusMaxOne),zod.null()]),
  "dataCriacao": zod.union([zod.string(),zod.null()]),
  "dataExecucao": zod.union([zod.string(),zod.null()]),
  "sku": zod.union([zod.string(),zod.null()]),
  "descricao": zod.union([zod.string(),zod.null()]),
  "lote": zod.union([zod.string(),zod.null()]),
  "executadoPor": zod.union([zod.string(),zod.null()]),
  "iniciado": zod.union([zod.string(),zod.null()])
})

/**
 * @summary Buscar todas as movimentações pendentes
 */
export const findAllPendingParams = zod.object({
  "centerId": zod.string()
})

export const findAllPendingResponseIdMovMin = -2147483648;
export const findAllPendingResponseIdMovMax = 2147483647;export const findAllPendingResponsePaleteMax = 50;export const findAllPendingResponseOrigemMaxOne = 50;export const findAllPendingResponseDestinoMaxOne = 50;export const findAllPendingResponsePrioridadeMin = -2147483648;
export const findAllPendingResponsePrioridadeMax = 2147483647;export const findAllPendingResponseStatusMaxOne = 20;

export const findAllPendingResponseItem = zod.object({
  "idMov": zod.number().min(findAllPendingResponseIdMovMin).max(findAllPendingResponseIdMovMax),
  "idUsuario": zod.union([zod.string(),zod.null()]),
  "idCentro": zod.string(),
  "palete": zod.string().max(findAllPendingResponsePaleteMax),
  "origem": zod.union([zod.string().max(findAllPendingResponseOrigemMaxOne),zod.null()]),
  "destino": zod.union([zod.string().max(findAllPendingResponseDestinoMaxOne),zod.null()]),
  "prioridade": zod.number().min(findAllPendingResponsePrioridadeMin).max(findAllPendingResponsePrioridadeMax),
  "status": zod.union([zod.string().max(findAllPendingResponseStatusMaxOne),zod.null()]),
  "dataCriacao": zod.union([zod.string(),zod.null()]),
  "dataExecucao": zod.union([zod.string(),zod.null()]),
  "sku": zod.union([zod.string(),zod.null()]),
  "descricao": zod.union([zod.string(),zod.null()]),
  "lote": zod.union([zod.string(),zod.null()]),
  "executadoPor": zod.union([zod.string(),zod.null()]),
  "iniciado": zod.union([zod.string(),zod.null()])
})
export const findAllPendingResponse = zod.array(findAllPendingResponseItem)

export const movimentacaoControllerFindOneParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Atualizar uma movimentação
 */
export const updateMovimentacaoParams = zod.object({
  "id": zod.number().describe('ID da movimentação')
})

export const updateMovimentacaoBodyIdMovMin = -2147483648;
export const updateMovimentacaoBodyIdMovMax = 2147483647;export const updateMovimentacaoBodyPaleteMax = 50;export const updateMovimentacaoBodyOrigemMaxOne = 50;export const updateMovimentacaoBodyDestinoMaxOne = 50;export const updateMovimentacaoBodyPrioridadeMin = -2147483648;
export const updateMovimentacaoBodyPrioridadeMax = 2147483647;export const updateMovimentacaoBodyStatusMaxOne = 20;

export const updateMovimentacaoBody = zod.object({
  "idMov": zod.number().min(updateMovimentacaoBodyIdMovMin).max(updateMovimentacaoBodyIdMovMax).optional(),
  "idUsuario": zod.union([zod.string(),zod.null()]).optional(),
  "idCentro": zod.string().optional(),
  "palete": zod.string().max(updateMovimentacaoBodyPaleteMax).optional(),
  "origem": zod.union([zod.string().max(updateMovimentacaoBodyOrigemMaxOne),zod.null()]).optional(),
  "destino": zod.union([zod.string().max(updateMovimentacaoBodyDestinoMaxOne),zod.null()]).optional(),
  "prioridade": zod.number().min(updateMovimentacaoBodyPrioridadeMin).max(updateMovimentacaoBodyPrioridadeMax).optional(),
  "status": zod.union([zod.string().max(updateMovimentacaoBodyStatusMaxOne),zod.null()]).optional(),
  "dataCriacao": zod.union([zod.string(),zod.null()]).optional(),
  "dataExecucao": zod.union([zod.string(),zod.null()]).optional(),
  "sku": zod.union([zod.string(),zod.null()]).optional(),
  "descricao": zod.union([zod.string(),zod.null()]).optional(),
  "lote": zod.union([zod.string(),zod.null()]).optional(),
  "executadoPor": zod.union([zod.string(),zod.null()]).optional(),
  "iniciado": zod.union([zod.string(),zod.null()]).optional()
})

export const updateMovimentacaoResponse = zod.boolean()

/**
 * @summary Remover uma movimentação
 */
export const removerMovimentacaoParams = zod.object({
  "id": zod.number().describe('ID da movimentação')
})

export const removerMovimentacaoResponse = zod.boolean()

/**
 * @summary Buscar a próxima movimentação pendente
 */
export const getNextMovimentacaoParams = zod.object({
  "centerId": zod.string()
})

export const getNextMovimentacaoResponseIdMovMin = -2147483648;
export const getNextMovimentacaoResponseIdMovMax = 2147483647;export const getNextMovimentacaoResponsePaleteMax = 50;export const getNextMovimentacaoResponseOrigemMaxOne = 50;export const getNextMovimentacaoResponseDestinoMaxOne = 50;export const getNextMovimentacaoResponsePrioridadeMin = -2147483648;
export const getNextMovimentacaoResponsePrioridadeMax = 2147483647;export const getNextMovimentacaoResponseStatusMaxOne = 20;

export const getNextMovimentacaoResponse = zod.object({
  "idMov": zod.number().min(getNextMovimentacaoResponseIdMovMin).max(getNextMovimentacaoResponseIdMovMax),
  "idUsuario": zod.union([zod.string(),zod.null()]),
  "idCentro": zod.string(),
  "palete": zod.string().max(getNextMovimentacaoResponsePaleteMax),
  "origem": zod.union([zod.string().max(getNextMovimentacaoResponseOrigemMaxOne),zod.null()]),
  "destino": zod.union([zod.string().max(getNextMovimentacaoResponseDestinoMaxOne),zod.null()]),
  "prioridade": zod.number().min(getNextMovimentacaoResponsePrioridadeMin).max(getNextMovimentacaoResponsePrioridadeMax),
  "status": zod.union([zod.string().max(getNextMovimentacaoResponseStatusMaxOne),zod.null()]),
  "dataCriacao": zod.union([zod.string(),zod.null()]),
  "dataExecucao": zod.union([zod.string(),zod.null()]),
  "sku": zod.union([zod.string(),zod.null()]),
  "descricao": zod.union([zod.string(),zod.null()]),
  "lote": zod.union([zod.string(),zod.null()]),
  "executadoPor": zod.union([zod.string(),zod.null()]),
  "iniciado": zod.union([zod.string(),zod.null()])
})

/**
 * @summary Validar uma movimentação
 */
export const validateMovimentacaoParams = zod.object({
  "id": zod.string()
})

export const validateMovimentacaoResponse = zod.boolean()

/**
 * @summary Cadastrar uma anomalia
 */
export const cadastrarAnomaliaParams = zod.object({
  "id": zod.string()
})

export const cadastrarAnomaliaResponse = zod.boolean()

/**
 * @summary Registrar o início de uma movimentação
 */
export const registerStartMovementParams = zod.object({
  "id": zod.number()
})

export const registerStartMovementResponse = zod.boolean()

/**
 * @summary Adicionar uma contagem lite validation
 */
export const addContagemLiteValidationBodyIdMin = -2147483648;
export const addContagemLiteValidationBodyIdMax = 2147483647;export const addContagemLiteValidationBodyCaixasMinOne = -2147483648;
export const addContagemLiteValidationBodyCaixasMaxOne = 2147483647;export const addContagemLiteValidationBodyQtdPaleteMinOne = -2147483648;
export const addContagemLiteValidationBodyQtdPaleteMaxOne = 2147483647;export const addContagemLiteValidationBodyCapacidadePaleteMinOne = -2147483648;
export const addContagemLiteValidationBodyCapacidadePaleteMaxOne = 2147483647;

export const addContagemLiteValidationBodyItem = zod.object({
  "id": zod.number().min(addContagemLiteValidationBodyIdMin).max(addContagemLiteValidationBodyIdMax).optional(),
  "dataRef": zod.string(),
  "endereco": zod.string(),
  "sku": zod.union([zod.string(),zod.null()]).optional(),
  "descricao": zod.union([zod.string(),zod.null()]).optional(),
  "dataValidade": zod.union([zod.string(),zod.null()]).optional(),
  "lote": zod.union([zod.string(),zod.null()]).optional(),
  "peso": zod.union([zod.string(),zod.null()]).optional(),
  "caixas": zod.union([zod.number().min(addContagemLiteValidationBodyCaixasMinOne).max(addContagemLiteValidationBodyCaixasMaxOne),zod.null()]).optional(),
  "qtdPalete": zod.union([zod.number().min(addContagemLiteValidationBodyQtdPaleteMinOne).max(addContagemLiteValidationBodyQtdPaleteMaxOne),zod.null()]).optional(),
  "capacidadePalete": zod.union([zod.number().min(addContagemLiteValidationBodyCapacidadePaleteMinOne).max(addContagemLiteValidationBodyCapacidadePaleteMaxOne),zod.null()]).optional(),
  "area": zod.union([zod.string(),zod.null()]).optional(),
  "centroId": zod.string(),
  "codigoBloqueio": zod.union([zod.string(),zod.null()]).optional(),
  "validado": zod.union([zod.boolean(),zod.null()]).optional(),
  "adicionarPor": zod.union([zod.string(),zod.null()]).optional(),
  "contadoPor": zod.union([zod.string(),zod.null()]).optional(),
  "horaRegistro": zod.union([zod.string(),zod.null()]).optional()
})
export const addContagemLiteValidationBody = zod.array(addContagemLiteValidationBodyItem)

export const addContagemLiteValidationResponse = zod.boolean()

/**
 * @summary Buscar uma contagem lite validation por endereço
 */
export const getEnderecoParams = zod.object({
  "endereco": zod.string().describe('Endereço da contagem lite validation')
})

export const getEnderecoResponseIdMin = -2147483648;
export const getEnderecoResponseIdMax = 2147483647;export const getEnderecoResponseCaixasMinOne = -2147483648;
export const getEnderecoResponseCaixasMaxOne = 2147483647;export const getEnderecoResponseQtdPaleteMinOne = -2147483648;
export const getEnderecoResponseQtdPaleteMaxOne = 2147483647;export const getEnderecoResponseCapacidadePaleteMinOne = -2147483648;
export const getEnderecoResponseCapacidadePaleteMaxOne = 2147483647;

export const getEnderecoResponseItem = zod.object({
  "id": zod.number().min(getEnderecoResponseIdMin).max(getEnderecoResponseIdMax),
  "dataRef": zod.string(),
  "endereco": zod.string(),
  "sku": zod.union([zod.string(),zod.null()]),
  "descricao": zod.union([zod.string(),zod.null()]),
  "dataValidade": zod.union([zod.string(),zod.null()]),
  "lote": zod.union([zod.string(),zod.null()]),
  "peso": zod.union([zod.string(),zod.null()]),
  "caixas": zod.union([zod.number().min(getEnderecoResponseCaixasMinOne).max(getEnderecoResponseCaixasMaxOne),zod.null()]),
  "qtdPalete": zod.union([zod.number().min(getEnderecoResponseQtdPaleteMinOne).max(getEnderecoResponseQtdPaleteMaxOne),zod.null()]),
  "capacidadePalete": zod.union([zod.number().min(getEnderecoResponseCapacidadePaleteMinOne).max(getEnderecoResponseCapacidadePaleteMaxOne),zod.null()]),
  "area": zod.union([zod.string(),zod.null()]),
  "centroId": zod.string(),
  "codigoBloqueio": zod.union([zod.string(),zod.null()]),
  "validado": zod.union([zod.boolean(),zod.null()]),
  "adicionarPor": zod.union([zod.string(),zod.null()]),
  "contadoPor": zod.union([zod.string(),zod.null()]),
  "horaRegistro": zod.union([zod.string(),zod.null()])
})
export const getEnderecoResponse = zod.array(getEnderecoResponseItem)

/**
 * @summary Validar um endereço
 */
export const validarEnderecoParams = zod.object({
  "endereco": zod.string().describe('Endereço da contagem lite validation'),
  "centerId": zod.string()
})

export const validarEnderecoResponse = zod.boolean()

/**
 * @summary Adicionar uma anomalia contagem lite
 */
export const addAnomaliaContagemLiteParams = zod.object({
  "centerId": zod.string(),
  "endereco": zod.string()
})

export const addAnomaliaContagemLiteBodyQuantidadeMinOne = -2147483648;
export const addAnomaliaContagemLiteBodyQuantidadeMaxOne = 2147483647;

export const addAnomaliaContagemLiteBody = zod.object({
  "sku": zod.union([zod.string(),zod.null()]).optional(),
  "lote": zod.union([zod.string(),zod.null()]).optional(),
  "quantidade": zod.union([zod.number().min(addAnomaliaContagemLiteBodyQuantidadeMinOne).max(addAnomaliaContagemLiteBodyQuantidadeMaxOne),zod.null()]).optional(),
  "peso": zod.union([zod.string(),zod.null()]).optional(),
  "dataReferencia": zod.union([zod.string(),zod.null()]).optional(),
  "addPor": zod.union([zod.string(),zod.null()]).optional()
})

export const addAnomaliaContagemLiteResponse = zod.boolean()

/**
 * @summary Buscar o resumo da contagem lite
 */
export const resumoContagemLiteParams = zod.object({
  "centerId": zod.string().describe('ID do centro')
})

export const resumoContagemLiteResponseItem = zod.object({
  "endereco_base": zod.string(),
  "total_enderecos": zod.number(),
  "enderecos_validados": zod.number()
})
export const resumoContagemLiteResponse = zod.array(resumoContagemLiteResponseItem)

/**
 * @summary Deletar a contagem lite
 */
export const deleteContagemLiteParams = zod.object({
  "centerId": zod.string().describe('ID do centro')
})

export const deleteContagemLiteResponse = zod.boolean()

/**
 * @summary Buscar o relatorio de anomalias da contagem lite
 */
export const relatorioAnomaliasContagemLiteParams = zod.object({
  "centerId": zod.string().describe('ID do centro'),
  "dataReferencia": zod.string().describe('Data de referencia')
})

export const relatorioAnomaliasContagemLiteResponseIdMin = -2147483648;
export const relatorioAnomaliasContagemLiteResponseIdMax = 2147483647;export const relatorioAnomaliasContagemLiteResponseQuantidadeMinOne = -2147483648;
export const relatorioAnomaliasContagemLiteResponseQuantidadeMaxOne = 2147483647;

export const relatorioAnomaliasContagemLiteResponseItem = zod.object({
  "id": zod.number().min(relatorioAnomaliasContagemLiteResponseIdMin).max(relatorioAnomaliasContagemLiteResponseIdMax),
  "endereco": zod.union([zod.string(),zod.null()]),
  "centroId": zod.union([zod.string(),zod.null()]),
  "sku": zod.union([zod.string(),zod.null()]),
  "lote": zod.union([zod.string(),zod.null()]),
  "quantidade": zod.union([zod.number().min(relatorioAnomaliasContagemLiteResponseQuantidadeMinOne).max(relatorioAnomaliasContagemLiteResponseQuantidadeMaxOne),zod.null()]),
  "peso": zod.union([zod.string(),zod.null()]),
  "dataReferencia": zod.union([zod.string(),zod.null()]),
  "addPor": zod.union([zod.string(),zod.null()])
})
export const relatorioAnomaliasContagemLiteResponse = zod.array(relatorioAnomaliasContagemLiteResponseItem)

