/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import zod from 'zod';


/**
 * @summary Criar uma movimentação
 */
export const criarNovaMovimentacaoBodyPaleteMax = 50;export const criarNovaMovimentacaoBodyOrigemMax = 50;export const criarNovaMovimentacaoBodyDestinoMax = 50;export const criarNovaMovimentacaoBodyPrioridadeMin = -2147483648;
export const criarNovaMovimentacaoBodyPrioridadeMax = 2147483647;export const criarNovaMovimentacaoBodyStatusMaxOne = 20;

export const criarNovaMovimentacaoBodyItem = zod.object({
  "idUsuario": zod.union([zod.string(),zod.null()]).optional(),
  "idCentro": zod.string(),
  "palete": zod.string().max(criarNovaMovimentacaoBodyPaleteMax),
  "origem": zod.string().max(criarNovaMovimentacaoBodyOrigemMax),
  "destino": zod.string().max(criarNovaMovimentacaoBodyDestinoMax),
  "prioridade": zod.number().min(criarNovaMovimentacaoBodyPrioridadeMin).max(criarNovaMovimentacaoBodyPrioridadeMax),
  "status": zod.union([zod.string().max(criarNovaMovimentacaoBodyStatusMaxOne),zod.null()]).optional(),
  "dataCriacao": zod.union([zod.string(),zod.null()]).optional(),
  "dataExecucao": zod.union([zod.string(),zod.null()]).optional(),
  "sku": zod.union([zod.string(),zod.null()]).optional(),
  "descricao": zod.union([zod.string(),zod.null()]).optional(),
  "lote": zod.union([zod.string(),zod.null()]).optional()
})
export const criarNovaMovimentacaoBody = zod.array(criarNovaMovimentacaoBodyItem)

export const criarNovaMovimentacaoResponseIdMovMin = -2147483648;
export const criarNovaMovimentacaoResponseIdMovMax = 2147483647;export const criarNovaMovimentacaoResponsePaleteMax = 50;export const criarNovaMovimentacaoResponseOrigemMax = 50;export const criarNovaMovimentacaoResponseDestinoMax = 50;export const criarNovaMovimentacaoResponsePrioridadeMin = -2147483648;
export const criarNovaMovimentacaoResponsePrioridadeMax = 2147483647;export const criarNovaMovimentacaoResponseStatusMaxOne = 20;

export const criarNovaMovimentacaoResponse = zod.object({
  "idMov": zod.number().min(criarNovaMovimentacaoResponseIdMovMin).max(criarNovaMovimentacaoResponseIdMovMax),
  "idUsuario": zod.union([zod.string(),zod.null()]),
  "idCentro": zod.string(),
  "palete": zod.string().max(criarNovaMovimentacaoResponsePaleteMax),
  "origem": zod.string().max(criarNovaMovimentacaoResponseOrigemMax),
  "destino": zod.string().max(criarNovaMovimentacaoResponseDestinoMax),
  "prioridade": zod.number().min(criarNovaMovimentacaoResponsePrioridadeMin).max(criarNovaMovimentacaoResponsePrioridadeMax),
  "status": zod.union([zod.string().max(criarNovaMovimentacaoResponseStatusMaxOne),zod.null()]),
  "dataCriacao": zod.union([zod.string(),zod.null()]),
  "dataExecucao": zod.union([zod.string(),zod.null()]),
  "sku": zod.union([zod.string(),zod.null()]),
  "descricao": zod.union([zod.string(),zod.null()]),
  "lote": zod.union([zod.string(),zod.null()])
})

/**
 * @summary Buscar todas as movimentações pendentes
 */
export const findAllPendingParams = zod.object({
  "centerId": zod.string()
})

export const findAllPendingResponseIdMovMin = -2147483648;
export const findAllPendingResponseIdMovMax = 2147483647;export const findAllPendingResponsePaleteMax = 50;export const findAllPendingResponseOrigemMax = 50;export const findAllPendingResponseDestinoMax = 50;export const findAllPendingResponsePrioridadeMin = -2147483648;
export const findAllPendingResponsePrioridadeMax = 2147483647;export const findAllPendingResponseStatusMaxOne = 20;

export const findAllPendingResponseItem = zod.object({
  "idMov": zod.number().min(findAllPendingResponseIdMovMin).max(findAllPendingResponseIdMovMax),
  "idUsuario": zod.union([zod.string(),zod.null()]),
  "idCentro": zod.string(),
  "palete": zod.string().max(findAllPendingResponsePaleteMax),
  "origem": zod.string().max(findAllPendingResponseOrigemMax),
  "destino": zod.string().max(findAllPendingResponseDestinoMax),
  "prioridade": zod.number().min(findAllPendingResponsePrioridadeMin).max(findAllPendingResponsePrioridadeMax),
  "status": zod.union([zod.string().max(findAllPendingResponseStatusMaxOne),zod.null()]),
  "dataCriacao": zod.union([zod.string(),zod.null()]),
  "dataExecucao": zod.union([zod.string(),zod.null()]),
  "sku": zod.union([zod.string(),zod.null()]),
  "descricao": zod.union([zod.string(),zod.null()]),
  "lote": zod.union([zod.string(),zod.null()])
})
export const findAllPendingResponse = zod.array(findAllPendingResponseItem)

export const movimentacaoControllerFindOneParams = zod.object({
  "id": zod.string()
})

export const movimentacaoControllerUpdateParams = zod.object({
  "id": zod.string()
})

export const movimentacaoControllerUpdateBodyPaleteMax = 50;export const movimentacaoControllerUpdateBodyOrigemMax = 50;export const movimentacaoControllerUpdateBodyDestinoMax = 50;export const movimentacaoControllerUpdateBodyPrioridadeMin = -2147483648;
export const movimentacaoControllerUpdateBodyPrioridadeMax = 2147483647;export const movimentacaoControllerUpdateBodyStatusMaxOne = 20;

export const movimentacaoControllerUpdateBody = zod.object({
  "idUsuario": zod.union([zod.string(),zod.null()]).optional(),
  "idCentro": zod.string().optional(),
  "palete": zod.string().max(movimentacaoControllerUpdateBodyPaleteMax).optional(),
  "origem": zod.string().max(movimentacaoControllerUpdateBodyOrigemMax).optional(),
  "destino": zod.string().max(movimentacaoControllerUpdateBodyDestinoMax).optional(),
  "prioridade": zod.number().min(movimentacaoControllerUpdateBodyPrioridadeMin).max(movimentacaoControllerUpdateBodyPrioridadeMax).optional(),
  "status": zod.union([zod.string().max(movimentacaoControllerUpdateBodyStatusMaxOne),zod.null()]).optional(),
  "dataCriacao": zod.union([zod.string(),zod.null()]).optional(),
  "dataExecucao": zod.union([zod.string(),zod.null()]).optional(),
  "sku": zod.union([zod.string(),zod.null()]).optional(),
  "descricao": zod.union([zod.string(),zod.null()]).optional(),
  "lote": zod.union([zod.string(),zod.null()]).optional()
})

export const movimentacaoControllerRemoveParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Buscar a próxima movimentação pendente
 */
export const getNextMovimentacaoParams = zod.object({
  "centerId": zod.string()
})

export const getNextMovimentacaoResponseIdMovMin = -2147483648;
export const getNextMovimentacaoResponseIdMovMax = 2147483647;export const getNextMovimentacaoResponsePaleteMax = 50;export const getNextMovimentacaoResponseOrigemMax = 50;export const getNextMovimentacaoResponseDestinoMax = 50;export const getNextMovimentacaoResponsePrioridadeMin = -2147483648;
export const getNextMovimentacaoResponsePrioridadeMax = 2147483647;export const getNextMovimentacaoResponseStatusMaxOne = 20;

export const getNextMovimentacaoResponse = zod.object({
  "idMov": zod.number().min(getNextMovimentacaoResponseIdMovMin).max(getNextMovimentacaoResponseIdMovMax),
  "idUsuario": zod.union([zod.string(),zod.null()]),
  "idCentro": zod.string(),
  "palete": zod.string().max(getNextMovimentacaoResponsePaleteMax),
  "origem": zod.string().max(getNextMovimentacaoResponseOrigemMax),
  "destino": zod.string().max(getNextMovimentacaoResponseDestinoMax),
  "prioridade": zod.number().min(getNextMovimentacaoResponsePrioridadeMin).max(getNextMovimentacaoResponsePrioridadeMax),
  "status": zod.union([zod.string().max(getNextMovimentacaoResponseStatusMaxOne),zod.null()]),
  "dataCriacao": zod.union([zod.string(),zod.null()]),
  "dataExecucao": zod.union([zod.string(),zod.null()]),
  "sku": zod.union([zod.string(),zod.null()]),
  "descricao": zod.union([zod.string(),zod.null()]),
  "lote": zod.union([zod.string(),zod.null()])
})

