/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { CreateProdutividadeDtoProcesso } from './createProdutividadeDtoProcesso';
import type { CreateProdutividadeDtoTurno } from './createProdutividadeDtoTurno';

export interface CreateProdutividadeDto {
  funcionarioId: string;
  paletesIds: string[];
  centerId: string;
  processo: CreateProdutividadeDtoProcesso;
  inicio: string;
  obs?: string;
  turno: CreateProdutividadeDtoTurno;
}
