/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { CreateTransporteDtoOutputStatus } from './createTransporteDtoOutputStatus';
import type { CreateTransporteDtoOutputObs } from './createTransporteDtoOutputObs';
import type { CreateTransporteDtoOutputCarregamento } from './createTransporteDtoOutputCarregamento';
import type { CreateTransporteDtoOutputConferencia } from './createTransporteDtoOutputConferencia';
import type { CreateTransporteDtoOutputSeparacao } from './createTransporteDtoOutputSeparacao';

export interface CreateTransporteDtoOutput {
  numeroTransporte: string;
  status: CreateTransporteDtoOutputStatus;
  /** @minLength 1 */
  nomeRota: string;
  /** @minLength 1 */
  nomeTransportadora: string;
  /** @minLength 1 */
  placa: string;
  /** @minLength 1 */
  criadoEm: string;
  /** @minLength 1 */
  atualizadoEm: string;
  /** @minLength 1 */
  cadastradoPorId: string;
  /** @minLength 1 */
  dataExpedicao: string;
  /** @minLength 1 */
  centerId: string;
  obs: CreateTransporteDtoOutputObs;
  prioridade?: number;
  carregamento?: CreateTransporteDtoOutputCarregamento;
  conferencia?: CreateTransporteDtoOutputConferencia;
  separacao?: CreateTransporteDtoOutputSeparacao;
  qtdImpressoes?: number;
}
