/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */

export type GetAnomaliasParams = {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id?: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  demandaId?: number;
  centerId?: string;
  funcionarioId?: string;
  inicio?: string;
  fim?: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  caixas?: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  unidades?: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  paletes?: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  enderecosVisitado?: number;
  /**
   * @minimum -140737488355328
   * @maximum 140737488355327
   */
  produtividade?: number;
  motivoAnomalia?: string;
  motivoAnomaliaDescricao?: string | null;
  criadoPorId?: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  paletesNaDemanda?: number;
};
