/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */

export type ProdutividadeControllerFindAllParams = {
  processo?: string | null;
  turno?: 'MANHA' | 'TARDE' | 'NOITE' | null;
  tipoProcesso?: 'SEPARACAO' | 'CARREGAMENTO' | 'CONFERENCIA' | null;
  status?: 'NAO_INICIADO' | 'EM_PROGRESSO' | 'CONCLUIDO' | 'EM_PAUSA' | null;
  empresa?: 'LDB' | 'ITB' | 'DPA' | null;
};
