/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import type { UpdateTransporteDtoStatus } from './updateTransporteDtoStatus';
import type { UpdateTransporteDtoObs } from './updateTransporteDtoObs';
import type { UpdateTransporteDtoCarregamento } from './updateTransporteDtoCarregamento';
import type { UpdateTransporteDtoConferencia } from './updateTransporteDtoConferencia';
import type { UpdateTransporteDtoSeparacao } from './updateTransporteDtoSeparacao';

export interface UpdateTransporteDto {
  numeroTransporte?: string;
  status?: UpdateTransporteDtoStatus;
  /** @minLength 1 */
  nomeRota?: string;
  /** @minLength 1 */
  nomeTransportadora?: string;
  /** @minLength 1 */
  placa?: string;
  /** @minLength 1 */
  criadoEm?: string;
  /** @minLength 1 */
  atualizadoEm?: string;
  /** @minLength 1 */
  cadastradoPorId?: string;
  /** @minLength 1 */
  dataExpedicao?: string;
  /** @minLength 1 */
  centerId?: string;
  obs?: UpdateTransporteDtoObs;
  prioridade?: number;
  carregamento?: UpdateTransporteDtoCarregamento;
  conferencia?: UpdateTransporteDtoConferencia;
  separacao?: UpdateTransporteDtoSeparacao;
  qtdImpressoes?: number;
}
