/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type {
  GetTransporteDto,
  ResultTransporteDtoOutput,
  ResultadoHoraHoraDtoOutput,
  TransporteComRelacionamentosGetDto,
} from '../../model';

export const getBuscarTodosTransportesResponseMock =
  (): ResultTransporteDtoOutput[] =>
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      numeroTransporte: faker.string.alpha({ length: { min: 10, max: 20 } }),
      status: faker.helpers.arrayElement([
        'AGUARDANDO_SEPARACAO',
        'EM_SEPARACAO',
        'SEPARACAO_CONCLUIDA',
        'EM_CONFERENCIA',
        'CONFERENCIA_CONCLUIDA',
        'EM_CARREGAMENTO',
        'CARREGAMENTO_CONCLUIDO',
        'FATURADO',
        'LIBERADO_PORTARIA',
        'CANCELADO',
      ] as const),
      nomeRota: faker.string.alpha({ length: { min: 1, max: 20 } }),
      nomeTransportadora: faker.string.alpha({ length: { min: 1, max: 20 } }),
      placa: faker.string.alpha({ length: { min: 1, max: 20 } }),
      criadoEm: faker.string.alpha({ length: { min: 1, max: 20 } }),
      atualizadoEm: faker.string.alpha({ length: { min: 1, max: 20 } }),
      cadastradoPorId: faker.string.alpha({ length: { min: 1, max: 20 } }),
      dataExpedicao: faker.string.alpha({ length: { min: 1, max: 20 } }),
      centerId: faker.string.alpha({ length: { min: 1, max: 20 } }),
      obs: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      prioridade: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
      carregamento: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          'NAO_INICIADO',
          'EM_PROGRESSO',
          'CONCLUIDO',
          'EM_PAUSA',
        ] as const),
        undefined,
      ]),
      conferencia: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          'NAO_INICIADO',
          'EM_PROGRESSO',
          'CONCLUIDO',
          'EM_PAUSA',
        ] as const),
        undefined,
      ]),
      separacao: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          'NAO_INICIADO',
          'EM_PROGRESSO',
          'CONCLUIDO',
          'EM_PAUSA',
        ] as const),
        undefined,
      ]),
      qtdImpressoes: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
    }));

export const getBuscarTodosTransportesSemTransporteResponseMock =
  (): ResultTransporteDtoOutput[] =>
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      numeroTransporte: faker.string.alpha({ length: { min: 10, max: 20 } }),
      status: faker.helpers.arrayElement([
        'AGUARDANDO_SEPARACAO',
        'EM_SEPARACAO',
        'SEPARACAO_CONCLUIDA',
        'EM_CONFERENCIA',
        'CONFERENCIA_CONCLUIDA',
        'EM_CARREGAMENTO',
        'CARREGAMENTO_CONCLUIDO',
        'FATURADO',
        'LIBERADO_PORTARIA',
        'CANCELADO',
      ] as const),
      nomeRota: faker.string.alpha({ length: { min: 1, max: 20 } }),
      nomeTransportadora: faker.string.alpha({ length: { min: 1, max: 20 } }),
      placa: faker.string.alpha({ length: { min: 1, max: 20 } }),
      criadoEm: faker.string.alpha({ length: { min: 1, max: 20 } }),
      atualizadoEm: faker.string.alpha({ length: { min: 1, max: 20 } }),
      cadastradoPorId: faker.string.alpha({ length: { min: 1, max: 20 } }),
      dataExpedicao: faker.string.alpha({ length: { min: 1, max: 20 } }),
      centerId: faker.string.alpha({ length: { min: 1, max: 20 } }),
      obs: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      prioridade: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
      carregamento: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          'NAO_INICIADO',
          'EM_PROGRESSO',
          'CONCLUIDO',
          'EM_PAUSA',
        ] as const),
        undefined,
      ]),
      conferencia: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          'NAO_INICIADO',
          'EM_PROGRESSO',
          'CONCLUIDO',
          'EM_PAUSA',
        ] as const),
        undefined,
      ]),
      separacao: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          'NAO_INICIADO',
          'EM_PROGRESSO',
          'CONCLUIDO',
          'EM_PAUSA',
        ] as const),
        undefined,
      ]),
      qtdImpressoes: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
    }));

export const getBuscarInfoTransportePorTransportIdResponseMock = (
  overrideResponse: Partial<GetTransporteDto> = {},
): GetTransporteDto => ({
  id: faker.number.int({ min: -2147483648, max: 2147483647 }),
  numeroTransporte: faker.string.alpha({ length: { min: 10, max: 20 } }),
  status: faker.helpers.arrayElement([
    'AGUARDANDO_SEPARACAO',
    'EM_SEPARACAO',
    'SEPARACAO_CONCLUIDA',
    'EM_CONFERENCIA',
    'CONFERENCIA_CONCLUIDA',
    'EM_CARREGAMENTO',
    'CARREGAMENTO_CONCLUIDO',
    'FATURADO',
    'LIBERADO_PORTARIA',
    'CANCELADO',
  ] as const),
  nomeRota: faker.string.alpha({ length: { min: 10, max: 20 } }),
  nomeTransportadora: faker.string.alpha({ length: { min: 10, max: 20 } }),
  placa: faker.string.alpha({ length: { min: 10, max: 20 } }),
  criadoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
  atualizadoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
  cadastradoPorId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  dataExpedicao: faker.string.alpha({ length: { min: 10, max: 20 } }),
  centerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  obs: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    null,
  ]),
  prioridade: faker.number.int({ min: -2147483648, max: 2147483647 }),
  carregamento: faker.helpers.arrayElement([
    'NAO_INICIADO',
    'EM_PROGRESSO',
    'CONCLUIDO',
    'EM_PAUSA',
  ] as const),
  conferencia: faker.helpers.arrayElement([
    'NAO_INICIADO',
    'EM_PROGRESSO',
    'CONCLUIDO',
    'EM_PAUSA',
  ] as const),
  separacao: faker.helpers.arrayElement([
    'NAO_INICIADO',
    'EM_PROGRESSO',
    'CONCLUIDO',
    'EM_PAUSA',
  ] as const),
  cargaParada: faker.helpers.arrayElement([faker.datatype.boolean(), null]),
  ...overrideResponse,
});

export const getBuscarHoraAHoraTransportesResponseMock = (
  overrideResponse: Partial<ResultadoHoraHoraDtoOutput> = {},
): ResultadoHoraHoraDtoOutput => ({
  totalTransportes: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  horaHora: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    hora: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    totalCarregados: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
  })),
  ...overrideResponse,
});

export const getBuscarTransportePorNumeroTransporteResponseMock = (
  overrideResponse: Partial<TransporteComRelacionamentosGetDto> = {},
): TransporteComRelacionamentosGetDto => ({
  id: faker.number.int({ min: -2147483648, max: 2147483647 }),
  numeroTransporte: faker.string.alpha({ length: { min: 10, max: 20 } }),
  status: faker.helpers.arrayElement([
    'AGUARDANDO_SEPARACAO',
    'EM_SEPARACAO',
    'SEPARACAO_CONCLUIDA',
    'EM_CONFERENCIA',
    'CONFERENCIA_CONCLUIDA',
    'EM_CARREGAMENTO',
    'CARREGAMENTO_CONCLUIDO',
    'FATURADO',
    'LIBERADO_PORTARIA',
    'CANCELADO',
  ] as const),
  nomeRota: faker.string.alpha({ length: { min: 10, max: 20 } }),
  nomeTransportadora: faker.string.alpha({ length: { min: 10, max: 20 } }),
  placa: faker.string.alpha({ length: { min: 10, max: 20 } }),
  criadoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
  atualizadoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
  cadastradoPorId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  dataExpedicao: faker.string.alpha({ length: { min: 10, max: 20 } }),
  centerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  obs: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    null,
  ]),
  prioridade: faker.number.int({ min: -2147483648, max: 2147483647 }),
  carregamento: faker.helpers.arrayElement([
    'NAO_INICIADO',
    'EM_PROGRESSO',
    'CONCLUIDO',
    'EM_PAUSA',
  ] as const),
  conferencia: faker.helpers.arrayElement([
    'NAO_INICIADO',
    'EM_PROGRESSO',
    'CONCLUIDO',
    'EM_PAUSA',
  ] as const),
  separacao: faker.helpers.arrayElement([
    'NAO_INICIADO',
    'EM_PROGRESSO',
    'CONCLUIDO',
    'EM_PAUSA',
  ] as const),
  cargaParada: faker.helpers.arrayElement([faker.datatype.boolean(), null]),
  paletes: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.string.alpha({ length: { min: 10, max: 20 } }),
      empresa: faker.string.alpha({ length: { min: 10, max: 20 } }),
      quantidadeCaixas: faker.number.int({ min: -2147483648, max: 2147483647 }),
      quantidadeUnidades: faker.number.int({
        min: -2147483648,
        max: 2147483647,
      }),
      quantidadePaletes: faker.number.int({
        min: -2147483648,
        max: 2147483647,
      }),
      enderecoVisitado: faker.number.int({ min: -2147483648, max: 2147483647 }),
      segmento: faker.string.alpha({ length: { min: 10, max: 20 } }),
      transporteId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      tipoProcesso: faker.helpers.arrayElement([
        'SEPARACAO',
        'CARREGAMENTO',
        'CONFERENCIA',
      ] as const),
      criadoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
      atualizadoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
      demandaId: faker.helpers.arrayElement([
        faker.number.int({ min: -2147483648, max: 2147483647 }),
        null,
      ]),
      status: faker.helpers.arrayElement([
        'NAO_INICIADO',
        'EM_PROGRESSO',
        'CONCLUIDO',
        'EM_PAUSA',
      ] as const),
      validado: faker.datatype.boolean(),
      criadoPorId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      fim: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      inicio: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      totalCaixas: faker.number.int({ min: -2147483648, max: 2147483647 }),
      pesoLiquido: faker.number.float({
        min: -140737488355328,
        max: 140737488355327,
        fractionDigits: 2,
      }),
      dataTransporte: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
    })),
    undefined,
  ]),
  cortes: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.number.int({ min: -2147483648, max: 2147483647 }),
      produto: faker.string.alpha({ length: { min: 10, max: 20 } }),
      lote: faker.string.alpha({ length: { min: 10, max: 20 } }),
      unidades: faker.number.int({ min: -2147483648, max: 2147483647 }),
      motivo: faker.helpers.arrayElement([
        'FALTA_MERCADORIA',
        'FALTA_ESPACO',
        'RECUSA_SEFAZ',
      ] as const),
      realizado: faker.datatype.boolean(),
      criadoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
      atualizadoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
      criadoPorId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      transporteId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      direcao: faker.helpers.arrayElement([
        faker.helpers.arrayElement(['OPERACIONAL', 'ADMINISTRATIVO'] as const),
        null,
      ]),
      caixas: faker.number.int({ min: -2147483648, max: 2147483647 }),
      centerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      descricao: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      realizadoPorId: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
    })),
    undefined,
  ]),
  historicoTransporte: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.number.int({ min: -2147483648, max: 2147483647 }),
      alteradoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
      tipoEvento: faker.helpers.arrayElement([
        'CRIACAO_TRANSPORTE',
        'INICIO_SEPARACAO',
        'TERMINO_SEPARACAO',
        'INICIO_CONFERENCIA',
        'TERMINO_CONFERENCIA',
        'INICIO_CARREGAMENTO',
        'TERMINO_CARREGAMENTO',
        'CORTE_PRODUTO',
        'FATURADO',
        'LIBERADO_PORTARIA',
      ] as const),
      descricao: faker.string.alpha({ length: { min: 10, max: 20 } }),
      transporteId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      alteradoPorId: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      processo: faker.helpers.arrayElement([
        'SEPARACAO',
        'CARREGAMENTO',
        'CONFERENCIA',
      ] as const),
    })),
    undefined,
  ]),
  impressaoMapa: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.number.int({ min: -2147483648, max: 2147483647 }),
      impressoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
      transporteId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      impressoPorId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      tipoImpressao: faker.helpers.arrayElement([
        'SEPARACAO',
        'CARREGAMENTO',
        'CONFERENCIA',
      ] as const),
    })),
    undefined,
  ]),
  clientes: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      cliente: faker.string.alpha({ length: { min: 10, max: 20 } }),
      nomeCliente: faker.string.alpha({ length: { min: 10, max: 20 } }),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getCriarTransporteEmMassaMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/transporte',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getCriarCargaParadaMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/transporte/create-carga-parada',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getBuscarTodosTransportesMockHandler = (
  overrideResponse?:
    | ResultTransporteDtoOutput[]
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResultTransporteDtoOutput[]> | ResultTransporteDtoOutput[]),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/transporte/find-all',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getBuscarTodosTransportesResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getBuscarTodosTransportesSemTransporteMockHandler = (
  overrideResponse?:
    | ResultTransporteDtoOutput[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ResultTransporteDtoOutput[]> | ResultTransporteDtoOutput[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/transporte/find-all-without-transporte/:centerId',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getBuscarTodosTransportesSemTransporteResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getBuscarInfoTransportePorTransportIdMockHandler = (
  overrideResponse?:
    | GetTransporteDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetTransporteDto> | GetTransporteDto),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/transporte/get-info-transporte-by-transport-id/:transportId',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getBuscarInfoTransportePorTransportIdResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getBuscarHoraAHoraTransportesMockHandler = (
  overrideResponse?:
    | ResultadoHoraHoraDtoOutput
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ResultadoHoraHoraDtoOutput> | ResultadoHoraHoraDtoOutput),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/transporte/hora-a-hora-transporte/:data/:centerId/:tipoEvento',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getBuscarHoraAHoraTransportesResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getAdicionarItensAoTransporteMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/transporte/add-items-to-transporte',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getAdicionarPaletesAoTransporteMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/transporte/add-paletes-in-transporte',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getBuscarTransportePorNumeroTransporteMockHandler = (
  overrideResponse?:
    | TransporteComRelacionamentosGetDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<TransporteComRelacionamentosGetDto>
        | TransporteComRelacionamentosGetDto),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/transporte/find-by-numero-transporte/:numeroTransporte',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getBuscarTransportePorNumeroTransporteResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};
export const getTransporteMock = () => [
  getCriarTransporteEmMassaMockHandler(),
  getCriarCargaParadaMockHandler(),
  getBuscarTodosTransportesMockHandler(),
  getBuscarTodosTransportesSemTransporteMockHandler(),
  getBuscarInfoTransportePorTransportIdMockHandler(),
  getBuscarHoraAHoraTransportesMockHandler(),
  getAdicionarItensAoTransporteMockHandler(),
  getAdicionarPaletesAoTransporteMockHandler(),
  getBuscarTransportePorNumeroTransporteMockHandler(),
];
