/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AddItemsTransporteDto,
  BuscarTodosTransportesParams,
  BuscarTodosTransportesSemTransporteParams,
  CreateCargaParadaDto,
  CreateTransporteItemDto,
  GetAllTransportesDto,
  GetTransporteDto,
  PaleteCreateDataDto,
  ResultTransporteDtoOutput,
  ResultadoHoraHoraDtoOutput,
  TransporteComRelacionamentosGetDto,
} from '../../model';

import { axiosFetcher } from '../../../http/axios.http';
import type { ErrorType, BodyType } from '../../../http/axios.http';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Criar transporte em massa
 */
export const criarTransporteEmMassa = (
  createTransporteItemDto: BodyType<CreateTransporteItemDto[]>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<void>(
    {
      url: `/api/transporte`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTransporteItemDto,
      signal,
    },
    options,
  );
};

export const getCriarTransporteEmMassaMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarTransporteEmMassa>>,
    TError,
    { data: BodyType<CreateTransporteItemDto[]> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarTransporteEmMassa>>,
  TError,
  { data: BodyType<CreateTransporteItemDto[]> },
  TContext
> => {
  const mutationKey = ['criarTransporteEmMassa'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarTransporteEmMassa>>,
    { data: BodyType<CreateTransporteItemDto[]> }
  > = (props) => {
    const { data } = props ?? {};

    return criarTransporteEmMassa(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarTransporteEmMassaMutationResult = NonNullable<
  Awaited<ReturnType<typeof criarTransporteEmMassa>>
>;
export type CriarTransporteEmMassaMutationBody = BodyType<
  CreateTransporteItemDto[]
>;
export type CriarTransporteEmMassaMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Criar transporte em massa
 */
export const useCriarTransporteEmMassa = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarTransporteEmMassa>>,
      TError,
      { data: BodyType<CreateTransporteItemDto[]> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarTransporteEmMassa>>,
  TError,
  { data: BodyType<CreateTransporteItemDto[]> },
  TContext
> => {
  const mutationOptions = getCriarTransporteEmMassaMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Criar carga parada
 */
export const criarCargaParada = (
  createCargaParadaDto: BodyType<CreateCargaParadaDto>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<void>(
    {
      url: `/api/transporte/create-carga-parada`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createCargaParadaDto,
      signal,
    },
    options,
  );
};

export const getCriarCargaParadaMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarCargaParada>>,
    TError,
    { data: BodyType<CreateCargaParadaDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarCargaParada>>,
  TError,
  { data: BodyType<CreateCargaParadaDto> },
  TContext
> => {
  const mutationKey = ['criarCargaParada'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarCargaParada>>,
    { data: BodyType<CreateCargaParadaDto> }
  > = (props) => {
    const { data } = props ?? {};

    return criarCargaParada(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarCargaParadaMutationResult = NonNullable<
  Awaited<ReturnType<typeof criarCargaParada>>
>;
export type CriarCargaParadaMutationBody = BodyType<CreateCargaParadaDto>;
export type CriarCargaParadaMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Criar carga parada
 */
export const useCriarCargaParada = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarCargaParada>>,
      TError,
      { data: BodyType<CreateCargaParadaDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarCargaParada>>,
  TError,
  { data: BodyType<CreateCargaParadaDto> },
  TContext
> => {
  const mutationOptions = getCriarCargaParadaMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Buscar todos os transportes
 */
export const buscarTodosTransportes = (
  getAllTransportesDto: BodyType<GetAllTransportesDto>,
  params?: BuscarTodosTransportesParams,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<ResultTransporteDtoOutput[]>(
    {
      url: `/api/transporte/find-all`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: getAllTransportesDto,
      params,
      signal,
    },
    options,
  );
};

export const getBuscarTodosTransportesMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof buscarTodosTransportes>>,
    TError,
    {
      data: BodyType<GetAllTransportesDto>;
      params?: BuscarTodosTransportesParams;
    },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof buscarTodosTransportes>>,
  TError,
  {
    data: BodyType<GetAllTransportesDto>;
    params?: BuscarTodosTransportesParams;
  },
  TContext
> => {
  const mutationKey = ['buscarTodosTransportes'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof buscarTodosTransportes>>,
    {
      data: BodyType<GetAllTransportesDto>;
      params?: BuscarTodosTransportesParams;
    }
  > = (props) => {
    const { data, params } = props ?? {};

    return buscarTodosTransportes(data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BuscarTodosTransportesMutationResult = NonNullable<
  Awaited<ReturnType<typeof buscarTodosTransportes>>
>;
export type BuscarTodosTransportesMutationBody = BodyType<GetAllTransportesDto>;
export type BuscarTodosTransportesMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Buscar todos os transportes
 */
export const useBuscarTodosTransportes = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof buscarTodosTransportes>>,
      TError,
      {
        data: BodyType<GetAllTransportesDto>;
        params?: BuscarTodosTransportesParams;
      },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof buscarTodosTransportes>>,
  TError,
  {
    data: BodyType<GetAllTransportesDto>;
    params?: BuscarTodosTransportesParams;
  },
  TContext
> => {
  const mutationOptions = getBuscarTodosTransportesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Buscar todos os transportes sem transporte
 */
export const buscarTodosTransportesSemTransporte = (
  centerId: string,
  params?: BuscarTodosTransportesSemTransporteParams,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<ResultTransporteDtoOutput[]>(
    {
      url: `/api/transporte/find-all-without-transporte/${centerId}`,
      method: 'GET',
      params,
      signal,
    },
    options,
  );
};

export const getBuscarTodosTransportesSemTransporteQueryKey = (
  centerId?: string,
  params?: BuscarTodosTransportesSemTransporteParams,
) => {
  return [
    `/api/transporte/find-all-without-transporte/${centerId}`,
    ...(params ? [params] : []),
  ] as const;
};

export const getBuscarTodosTransportesSemTransporteQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  params?: BuscarTodosTransportesSemTransporteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getBuscarTodosTransportesSemTransporteQueryKey(centerId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>
  > = ({ signal }) =>
    buscarTodosTransportesSemTransporte(
      centerId,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!centerId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BuscarTodosTransportesSemTransporteQueryResult = NonNullable<
  Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>
>;
export type BuscarTodosTransportesSemTransporteQueryError = ErrorType<
  void | void | void | void | void | void
>;

export function useBuscarTodosTransportesSemTransporte<
  TData = Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  params: undefined | BuscarTodosTransportesSemTransporteParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>,
          TError,
          Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarTodosTransportesSemTransporte<
  TData = Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  params?: BuscarTodosTransportesSemTransporteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>,
          TError,
          Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarTodosTransportesSemTransporte<
  TData = Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  params?: BuscarTodosTransportesSemTransporteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar todos os transportes sem transporte
 */

export function useBuscarTodosTransportesSemTransporte<
  TData = Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  params?: BuscarTodosTransportesSemTransporteParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodosTransportesSemTransporte>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBuscarTodosTransportesSemTransporteQueryOptions(
    centerId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Buscar informações do transporte
 */
export const buscarInfoTransportePorTransportId = (
  transportId: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<GetTransporteDto>(
    {
      url: `/api/transporte/get-info-transporte-by-transport-id/${transportId}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getBuscarInfoTransportePorTransportIdQueryKey = (
  transportId?: string,
) => {
  return [
    `/api/transporte/get-info-transporte-by-transport-id/${transportId}`,
  ] as const;
};

export const getBuscarInfoTransportePorTransportIdQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  transportId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getBuscarInfoTransportePorTransportIdQueryKey(transportId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>
  > = ({ signal }) =>
    buscarInfoTransportePorTransportId(transportId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!transportId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BuscarInfoTransportePorTransportIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>
>;
export type BuscarInfoTransportePorTransportIdQueryError = ErrorType<
  void | void | void | void | void | void
>;

export function useBuscarInfoTransportePorTransportId<
  TData = Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  transportId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>,
          TError,
          Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarInfoTransportePorTransportId<
  TData = Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  transportId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>,
          TError,
          Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarInfoTransportePorTransportId<
  TData = Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  transportId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar informações do transporte
 */

export function useBuscarInfoTransportePorTransportId<
  TData = Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  transportId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarInfoTransportePorTransportId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBuscarInfoTransportePorTransportIdQueryOptions(
    transportId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Buscar a hora a hora de transportes
 */
export const buscarHoraAHoraTransportes = (
  data: string,
  centerId: string,
  tipoEvento: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<ResultadoHoraHoraDtoOutput>(
    {
      url: `/api/transporte/hora-a-hora-transporte/${data}/${centerId}/${tipoEvento}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getBuscarHoraAHoraTransportesQueryKey = (
  data?: string,
  centerId?: string,
  tipoEvento?: string,
) => {
  return [
    `/api/transporte/hora-a-hora-transporte/${data}/${centerId}/${tipoEvento}`,
  ] as const;
};

export const getBuscarHoraAHoraTransportesQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  data: string,
  centerId: string,
  tipoEvento: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getBuscarHoraAHoraTransportesQueryKey(data, centerId, tipoEvento);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>
  > = ({ signal }) =>
    buscarHoraAHoraTransportes(
      data,
      centerId,
      tipoEvento,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(data && centerId && tipoEvento),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BuscarHoraAHoraTransportesQueryResult = NonNullable<
  Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>
>;
export type BuscarHoraAHoraTransportesQueryError = ErrorType<
  void | void | void | void | void | void
>;

export function useBuscarHoraAHoraTransportes<
  TData = Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  data: string,
  centerId: string,
  tipoEvento: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>,
          TError,
          Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarHoraAHoraTransportes<
  TData = Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  data: string,
  centerId: string,
  tipoEvento: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>,
          TError,
          Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarHoraAHoraTransportes<
  TData = Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  data: string,
  centerId: string,
  tipoEvento: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar a hora a hora de transportes
 */

export function useBuscarHoraAHoraTransportes<
  TData = Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  data: string,
  centerId: string,
  tipoEvento: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarHoraAHoraTransportes>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBuscarHoraAHoraTransportesQueryOptions(
    data,
    centerId,
    tipoEvento,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Adicionar itens a um transporte
 */
export const adicionarItensAoTransporte = (
  addItemsTransporteDto: BodyType<AddItemsTransporteDto[]>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<void>(
    {
      url: `/api/transporte/add-items-to-transporte`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addItemsTransporteDto,
      signal,
    },
    options,
  );
};

export const getAdicionarItensAoTransporteMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adicionarItensAoTransporte>>,
    TError,
    { data: BodyType<AddItemsTransporteDto[]> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adicionarItensAoTransporte>>,
  TError,
  { data: BodyType<AddItemsTransporteDto[]> },
  TContext
> => {
  const mutationKey = ['adicionarItensAoTransporte'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adicionarItensAoTransporte>>,
    { data: BodyType<AddItemsTransporteDto[]> }
  > = (props) => {
    const { data } = props ?? {};

    return adicionarItensAoTransporte(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdicionarItensAoTransporteMutationResult = NonNullable<
  Awaited<ReturnType<typeof adicionarItensAoTransporte>>
>;
export type AdicionarItensAoTransporteMutationBody = BodyType<
  AddItemsTransporteDto[]
>;
export type AdicionarItensAoTransporteMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Adicionar itens a um transporte
 */
export const useAdicionarItensAoTransporte = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adicionarItensAoTransporte>>,
      TError,
      { data: BodyType<AddItemsTransporteDto[]> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adicionarItensAoTransporte>>,
  TError,
  { data: BodyType<AddItemsTransporteDto[]> },
  TContext
> => {
  const mutationOptions = getAdicionarItensAoTransporteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Adicionar paletes a um transporte
 */
export const adicionarPaletesAoTransporte = (
  paleteCreateDataDto: BodyType<PaleteCreateDataDto[]>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<void>(
    {
      url: `/api/transporte/add-paletes-in-transporte`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: paleteCreateDataDto,
      signal,
    },
    options,
  );
};

export const getAdicionarPaletesAoTransporteMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adicionarPaletesAoTransporte>>,
    TError,
    { data: BodyType<PaleteCreateDataDto[]> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adicionarPaletesAoTransporte>>,
  TError,
  { data: BodyType<PaleteCreateDataDto[]> },
  TContext
> => {
  const mutationKey = ['adicionarPaletesAoTransporte'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adicionarPaletesAoTransporte>>,
    { data: BodyType<PaleteCreateDataDto[]> }
  > = (props) => {
    const { data } = props ?? {};

    return adicionarPaletesAoTransporte(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdicionarPaletesAoTransporteMutationResult = NonNullable<
  Awaited<ReturnType<typeof adicionarPaletesAoTransporte>>
>;
export type AdicionarPaletesAoTransporteMutationBody = BodyType<
  PaleteCreateDataDto[]
>;
export type AdicionarPaletesAoTransporteMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Adicionar paletes a um transporte
 */
export const useAdicionarPaletesAoTransporte = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adicionarPaletesAoTransporte>>,
      TError,
      { data: BodyType<PaleteCreateDataDto[]> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof adicionarPaletesAoTransporte>>,
  TError,
  { data: BodyType<PaleteCreateDataDto[]> },
  TContext
> => {
  const mutationOptions =
    getAdicionarPaletesAoTransporteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Buscar transporte por número de transporte
 */
export const buscarTransportePorNumeroTransporte = (
  numeroTransporte: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<TransporteComRelacionamentosGetDto>(
    {
      url: `/api/transporte/find-by-numero-transporte/${numeroTransporte}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getBuscarTransportePorNumeroTransporteQueryKey = (
  numeroTransporte?: string,
) => {
  return [
    `/api/transporte/find-by-numero-transporte/${numeroTransporte}`,
  ] as const;
};

export const getBuscarTransportePorNumeroTransporteQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  numeroTransporte: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getBuscarTransportePorNumeroTransporteQueryKey(numeroTransporte);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>
  > = ({ signal }) =>
    buscarTransportePorNumeroTransporte(
      numeroTransporte,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!numeroTransporte,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BuscarTransportePorNumeroTransporteQueryResult = NonNullable<
  Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>
>;
export type BuscarTransportePorNumeroTransporteQueryError = ErrorType<
  void | void | void | void | void | void
>;

export function useBuscarTransportePorNumeroTransporte<
  TData = Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  numeroTransporte: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>,
          TError,
          Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarTransportePorNumeroTransporte<
  TData = Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  numeroTransporte: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>,
          TError,
          Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarTransportePorNumeroTransporte<
  TData = Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  numeroTransporte: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar transporte por número de transporte
 */

export function useBuscarTransportePorNumeroTransporte<
  TData = Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  numeroTransporte: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTransportePorNumeroTransporte>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBuscarTransportePorNumeroTransporteQueryOptions(
    numeroTransporte,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Trocar data de expedição de transportes
 */
export const trocarDataExpedicaoTransportes = (
  dataExpedicao: string,
  trocarDataExpedicaoTransportesBody: BodyType<string[]>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<void>(
    {
      url: `/api/transporte/trocar-data-expedicao-transporte/${dataExpedicao}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: trocarDataExpedicaoTransportesBody,
      signal,
    },
    options,
  );
};

export const getTrocarDataExpedicaoTransportesMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof trocarDataExpedicaoTransportes>>,
    TError,
    { dataExpedicao: string; data: BodyType<string[]> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof trocarDataExpedicaoTransportes>>,
  TError,
  { dataExpedicao: string; data: BodyType<string[]> },
  TContext
> => {
  const mutationKey = ['trocarDataExpedicaoTransportes'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof trocarDataExpedicaoTransportes>>,
    { dataExpedicao: string; data: BodyType<string[]> }
  > = (props) => {
    const { dataExpedicao, data } = props ?? {};

    return trocarDataExpedicaoTransportes(dataExpedicao, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TrocarDataExpedicaoTransportesMutationResult = NonNullable<
  Awaited<ReturnType<typeof trocarDataExpedicaoTransportes>>
>;
export type TrocarDataExpedicaoTransportesMutationBody = BodyType<string[]>;
export type TrocarDataExpedicaoTransportesMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Trocar data de expedição de transportes
 */
export const useTrocarDataExpedicaoTransportes = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof trocarDataExpedicaoTransportes>>,
      TError,
      { dataExpedicao: string; data: BodyType<string[]> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof trocarDataExpedicaoTransportes>>,
  TError,
  { dataExpedicao: string; data: BodyType<string[]> },
  TContext
> => {
  const mutationOptions =
    getTrocarDataExpedicaoTransportesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
