/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateUserDto,
  EditUserDto,
  InfoMeDtoOutput,
  ListarUsuariosParams,
  RoleDtoOutput,
  UserDto,
  UserDtoOutput,
} from '../../model';

import { axiosFetcher } from '../../../http/axios.http';
import type { ErrorType, BodyType } from '../../../http/axios.http';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary criar usuario
 */
export const criarUsuario = (
  createUserDto: BodyType<CreateUserDto>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<UserDto>(
    {
      url: `/api/user`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createUserDto,
      signal,
    },
    options,
  );
};

export const getCriarUsuarioMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarUsuario>>,
    TError,
    { data: BodyType<CreateUserDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarUsuario>>,
  TError,
  { data: BodyType<CreateUserDto> },
  TContext
> => {
  const mutationKey = ['criarUsuario'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarUsuario>>,
    { data: BodyType<CreateUserDto> }
  > = (props) => {
    const { data } = props ?? {};

    return criarUsuario(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarUsuarioMutationResult = NonNullable<
  Awaited<ReturnType<typeof criarUsuario>>
>;
export type CriarUsuarioMutationBody = BodyType<CreateUserDto>;
export type CriarUsuarioMutationError = ErrorType<unknown>;

/**
 * @summary criar usuario
 */
export const useCriarUsuario = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarUsuario>>,
      TError,
      { data: BodyType<CreateUserDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarUsuario>>,
  TError,
  { data: BodyType<CreateUserDto> },
  TContext
> => {
  const mutationOptions = getCriarUsuarioMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary criar usuario em massa
 */
export const criarUsuarioEmMassa = (
  createUserDto: BodyType<CreateUserDto[]>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<void>(
    {
      url: `/api/user/batch`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createUserDto,
      signal,
    },
    options,
  );
};

export const getCriarUsuarioEmMassaMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarUsuarioEmMassa>>,
    TError,
    { data: BodyType<CreateUserDto[]> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarUsuarioEmMassa>>,
  TError,
  { data: BodyType<CreateUserDto[]> },
  TContext
> => {
  const mutationKey = ['criarUsuarioEmMassa'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarUsuarioEmMassa>>,
    { data: BodyType<CreateUserDto[]> }
  > = (props) => {
    const { data } = props ?? {};

    return criarUsuarioEmMassa(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarUsuarioEmMassaMutationResult = NonNullable<
  Awaited<ReturnType<typeof criarUsuarioEmMassa>>
>;
export type CriarUsuarioEmMassaMutationBody = BodyType<CreateUserDto[]>;
export type CriarUsuarioEmMassaMutationError = ErrorType<unknown>;

/**
 * @summary criar usuario em massa
 */
export const useCriarUsuarioEmMassa = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarUsuarioEmMassa>>,
      TError,
      { data: BodyType<CreateUserDto[]> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarUsuarioEmMassa>>,
  TError,
  { data: BodyType<CreateUserDto[]> },
  TContext
> => {
  const mutationOptions = getCriarUsuarioEmMassaMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary usuario
 */
export const listarUsuarios = (
  centerId: string,
  params?: ListarUsuariosParams,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<UserDtoOutput[]>(
    { url: `/api/user/userid/${centerId}`, method: 'GET', params, signal },
    options,
  );
};

export const getListarUsuariosQueryKey = (
  centerId?: string,
  params?: ListarUsuariosParams,
) => {
  return [`/api/user/userid/${centerId}`, ...(params ? [params] : [])] as const;
};

export const getListarUsuariosQueryOptions = <
  TData = Awaited<ReturnType<typeof listarUsuarios>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  params?: ListarUsuariosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listarUsuarios>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListarUsuariosQueryKey(centerId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listarUsuarios>>> = ({
    signal,
  }) => listarUsuarios(centerId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!centerId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listarUsuarios>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListarUsuariosQueryResult = NonNullable<
  Awaited<ReturnType<typeof listarUsuarios>>
>;
export type ListarUsuariosQueryError = ErrorType<unknown>;

export function useListarUsuarios<
  TData = Awaited<ReturnType<typeof listarUsuarios>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  params: undefined | ListarUsuariosParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listarUsuarios>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarUsuarios>>,
          TError,
          Awaited<ReturnType<typeof listarUsuarios>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListarUsuarios<
  TData = Awaited<ReturnType<typeof listarUsuarios>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  params?: ListarUsuariosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listarUsuarios>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarUsuarios>>,
          TError,
          Awaited<ReturnType<typeof listarUsuarios>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListarUsuarios<
  TData = Awaited<ReturnType<typeof listarUsuarios>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  params?: ListarUsuariosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listarUsuarios>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary usuario
 */

export function useListarUsuarios<
  TData = Awaited<ReturnType<typeof listarUsuarios>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  params?: ListarUsuariosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listarUsuarios>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListarUsuariosQueryOptions(centerId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const userControllerInfoMe = (
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<InfoMeDtoOutput>(
    { url: `/api/user/info-me`, method: 'GET', signal },
    options,
  );
};

export const getUserControllerInfoMeQueryKey = () => {
  return [`/api/user/info-me`] as const;
};

export const getUserControllerInfoMeQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerInfoMe>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof userControllerInfoMe>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerInfoMeQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userControllerInfoMe>>
  > = ({ signal }) => userControllerInfoMe(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerInfoMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerInfoMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerInfoMe>>
>;
export type UserControllerInfoMeQueryError = ErrorType<unknown>;

export function useUserControllerInfoMe<
  TData = Awaited<ReturnType<typeof userControllerInfoMe>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerInfoMe>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerInfoMe>>,
          TError,
          Awaited<ReturnType<typeof userControllerInfoMe>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserControllerInfoMe<
  TData = Awaited<ReturnType<typeof userControllerInfoMe>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerInfoMe>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerInfoMe>>,
          TError,
          Awaited<ReturnType<typeof userControllerInfoMe>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserControllerInfoMe<
  TData = Awaited<ReturnType<typeof userControllerInfoMe>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerInfoMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUserControllerInfoMe<
  TData = Awaited<ReturnType<typeof userControllerInfoMe>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerInfoMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUserControllerInfoMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Buscar roles
 */
export const getRoles = (
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<RoleDtoOutput[]>(
    { url: `/api/user/get-roles`, method: 'GET', signal },
    options,
  );
};

export const getGetRolesQueryKey = () => {
  return [`/api/user/get-roles`] as const;
};

export const getGetRolesQueryOptions = <
  TData = Awaited<ReturnType<typeof getRoles>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRolesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoles>>> = ({
    signal,
  }) => getRoles(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRoles>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRolesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRoles>>
>;
export type GetRolesQueryError = ErrorType<unknown>;

export function useGetRoles<
  TData = Awaited<ReturnType<typeof getRoles>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoles>>,
          TError,
          Awaited<ReturnType<typeof getRoles>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRoles<
  TData = Awaited<ReturnType<typeof getRoles>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoles>>,
          TError,
          Awaited<ReturnType<typeof getRoles>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRoles<
  TData = Awaited<ReturnType<typeof getRoles>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar roles
 */

export function useGetRoles<
  TData = Awaited<ReturnType<typeof getRoles>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRolesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Criar nova Role
 */
export const criarRole = (
  id: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<void>(
    { url: `/api/user/criar-role/${id}`, method: 'POST', signal },
    options,
  );
};

export const getCriarRoleMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarRole>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarRole>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['criarRole'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarRole>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return criarRole(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarRoleMutationResult = NonNullable<
  Awaited<ReturnType<typeof criarRole>>
>;

export type CriarRoleMutationError = ErrorType<unknown>;

/**
 * @summary Criar nova Role
 */
export const useCriarRole = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarRole>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarRole>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getCriarRoleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Deletar Usuario
 */
export const deletarUsuario = (
  id: string,
  centerId: string,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<void>(
    { url: `/api/user/${id}/${centerId}`, method: 'DELETE' },
    options,
  );
};

export const getDeletarUsuarioMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletarUsuario>>,
    TError,
    { id: string; centerId: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletarUsuario>>,
  TError,
  { id: string; centerId: string },
  TContext
> => {
  const mutationKey = ['deletarUsuario'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletarUsuario>>,
    { id: string; centerId: string }
  > = (props) => {
    const { id, centerId } = props ?? {};

    return deletarUsuario(id, centerId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletarUsuarioMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletarUsuario>>
>;

export type DeletarUsuarioMutationError = ErrorType<unknown>;

/**
 * @summary Deletar Usuario
 */
export const useDeletarUsuario = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletarUsuario>>,
      TError,
      { id: string; centerId: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletarUsuario>>,
  TError,
  { id: string; centerId: string },
  TContext
> => {
  const mutationOptions = getDeletarUsuarioMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Atualizar Usuario
 */
export const atualizarUsuario = (
  id: string,
  editUserDto: BodyType<EditUserDto>,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<void>(
    {
      url: `/api/user/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: editUserDto,
    },
    options,
  );
};

export const getAtualizarUsuarioMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof atualizarUsuario>>,
    TError,
    { id: string; data: BodyType<EditUserDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof atualizarUsuario>>,
  TError,
  { id: string; data: BodyType<EditUserDto> },
  TContext
> => {
  const mutationKey = ['atualizarUsuario'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof atualizarUsuario>>,
    { id: string; data: BodyType<EditUserDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return atualizarUsuario(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AtualizarUsuarioMutationResult = NonNullable<
  Awaited<ReturnType<typeof atualizarUsuario>>
>;
export type AtualizarUsuarioMutationBody = BodyType<EditUserDto>;
export type AtualizarUsuarioMutationError = ErrorType<unknown>;

/**
 * @summary Atualizar Usuario
 */
export const useAtualizarUsuario = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof atualizarUsuario>>,
      TError,
      { id: string; data: BodyType<EditUserDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof atualizarUsuario>>,
  TError,
  { id: string; data: BodyType<EditUserDto> },
  TContext
> => {
  const mutationOptions = getAtualizarUsuarioMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Resetar senha
 */
export const resetarSenha = (
  id: string,
  password: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<void>(
    {
      url: `/api/user/reset-password/${id}/${password}`,
      method: 'POST',
      signal,
    },
    options,
  );
};

export const getResetarSenhaMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetarSenha>>,
    TError,
    { id: string; password: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof resetarSenha>>,
  TError,
  { id: string; password: string },
  TContext
> => {
  const mutationKey = ['resetarSenha'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resetarSenha>>,
    { id: string; password: string }
  > = (props) => {
    const { id, password } = props ?? {};

    return resetarSenha(id, password, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ResetarSenhaMutationResult = NonNullable<
  Awaited<ReturnType<typeof resetarSenha>>
>;

export type ResetarSenhaMutationError = ErrorType<unknown>;

/**
 * @summary Resetar senha
 */
export const useResetarSenha = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof resetarSenha>>,
      TError,
      { id: string; password: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof resetarSenha>>,
  TError,
  { id: string; password: string },
  TContext
> => {
  const mutationOptions = getResetarSenhaMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Atualizar permissões
 */
export const atualizarPermissoes = (
  id: string,
  centerId: string,
  atualizarPermissoesBody: BodyType<string[]>,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<void>(
    {
      url: `/api/user/update-permissions/${id}/${centerId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: atualizarPermissoesBody,
    },
    options,
  );
};

export const getAtualizarPermissoesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof atualizarPermissoes>>,
    TError,
    { id: string; centerId: string; data: BodyType<string[]> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof atualizarPermissoes>>,
  TError,
  { id: string; centerId: string; data: BodyType<string[]> },
  TContext
> => {
  const mutationKey = ['atualizarPermissoes'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof atualizarPermissoes>>,
    { id: string; centerId: string; data: BodyType<string[]> }
  > = (props) => {
    const { id, centerId, data } = props ?? {};

    return atualizarPermissoes(id, centerId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AtualizarPermissoesMutationResult = NonNullable<
  Awaited<ReturnType<typeof atualizarPermissoes>>
>;
export type AtualizarPermissoesMutationBody = BodyType<string[]>;
export type AtualizarPermissoesMutationError = ErrorType<unknown>;

/**
 * @summary Atualizar permissões
 */
export const useAtualizarPermissoes = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof atualizarPermissoes>>,
      TError,
      { id: string; centerId: string; data: BodyType<string[]> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof atualizarPermissoes>>,
  TError,
  { id: string; centerId: string; data: BodyType<string[]> },
  TContext
> => {
  const mutationOptions = getAtualizarPermissoesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Buscar todas as permissões por centro
 */
export const buscarTodasPermissoesPorCentro = (
  userId: string,
  centerId: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<string[]>(
    {
      url: `/api/user/get-all-permissions-by-center/${userId}/${centerId}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getBuscarTodasPermissoesPorCentroQueryKey = (
  userId?: string,
  centerId?: string,
) => {
  return [
    `/api/user/get-all-permissions-by-center/${userId}/${centerId}`,
  ] as const;
};

export const getBuscarTodasPermissoesPorCentroQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getBuscarTodasPermissoesPorCentroQueryKey(userId, centerId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>
  > = ({ signal }) =>
    buscarTodasPermissoesPorCentro(userId, centerId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(userId && centerId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BuscarTodasPermissoesPorCentroQueryResult = NonNullable<
  Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>
>;
export type BuscarTodasPermissoesPorCentroQueryError = ErrorType<unknown>;

export function useBuscarTodasPermissoesPorCentro<
  TData = Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  centerId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>,
          TError,
          Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarTodasPermissoesPorCentro<
  TData = Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>,
          TError,
          Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarTodasPermissoesPorCentro<
  TData = Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar todas as permissões por centro
 */

export function useBuscarTodasPermissoesPorCentro<
  TData = Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodasPermissoesPorCentro>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBuscarTodasPermissoesPorCentroQueryOptions(
    userId,
    centerId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Encerrar sessão
 */
export const encerrarSessao = (
  userId: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<void>(
    { url: `/api/user/logout/${userId}`, method: 'POST', signal },
    options,
  );
};

export const getEncerrarSessaoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof encerrarSessao>>,
    TError,
    { userId: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof encerrarSessao>>,
  TError,
  { userId: string },
  TContext
> => {
  const mutationKey = ['encerrarSessao'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof encerrarSessao>>,
    { userId: string }
  > = (props) => {
    const { userId } = props ?? {};

    return encerrarSessao(userId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EncerrarSessaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof encerrarSessao>>
>;

export type EncerrarSessaoMutationError = ErrorType<unknown>;

/**
 * @summary Encerrar sessão
 */
export const useEncerrarSessao = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof encerrarSessao>>,
      TError,
      { userId: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof encerrarSessao>>,
  TError,
  { userId: string },
  TContext
> => {
  const mutationOptions = getEncerrarSessaoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
