/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type {
  InfoMeDtoOutput,
  RoleDtoOutput,
  UserDto,
  UserDtoOutput,
} from '../../model';

export const getCriarUsuarioResponseMock = (
  overrideResponse: Partial<UserDto> = {},
): UserDto => ({
  centerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  turno: faker.helpers.arrayElement([
    'MANHA',
    'TARDE',
    'NOITE',
    'INTERMEDIARIO',
    'ADMINISTRATIVO',
  ] as const),
  empresa: faker.string.alpha({ length: { min: 10, max: 20 } }),
  roles: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
  ...overrideResponse,
});

export const getListarUsuariosResponseMock = (): UserDtoOutput[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    centerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    turno: faker.helpers.arrayElement([
      'MANHA',
      'TARDE',
      'NOITE',
      'INTERMEDIARIO',
      'ADMINISTRATIVO',
    ] as const),
    empresa: faker.string.alpha({ length: { min: 10, max: 20 } }),
    roles: Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
  }));

export const getUserControllerInfoMeResponseMock = (
  overrideResponse: Partial<InfoMeDtoOutput> = {},
): InfoMeDtoOutput => ({
  id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  empresa: faker.helpers.arrayElement(['LDB', 'ITB', 'DPA'] as const),
  roles: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
  ...overrideResponse,
});

export const getGetRolesResponseMock = (): RoleDtoOutput[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    composite: faker.datatype.boolean(),
    clientRole: faker.datatype.boolean(),
    containerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  }));

export const getBuscarTodasPermissoesPorCentroResponseMock = (): string[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, () =>
    faker.word.sample(),
  );

export const getCriarUsuarioMockHandler = (
  overrideResponse?:
    | UserDto
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<UserDto> | UserDto),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/user',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getCriarUsuarioResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCriarUsuarioEmMassaMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/user/batch',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getListarUsuariosMockHandler = (
  overrideResponse?:
    | UserDtoOutput[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<UserDtoOutput[]> | UserDtoOutput[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/user/userid/:centerId',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getListarUsuariosResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getUserControllerInfoMeMockHandler = (
  overrideResponse?:
    | InfoMeDtoOutput
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<InfoMeDtoOutput> | InfoMeDtoOutput),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/user/info-me',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getUserControllerInfoMeResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetRolesMockHandler = (
  overrideResponse?:
    | RoleDtoOutput[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<RoleDtoOutput[]> | RoleDtoOutput[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/user/get-roles',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetRolesResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCriarRoleMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/user/criar-role/:id',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getDeletarUsuarioMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/api/user/:id/:centerId',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getAtualizarUsuarioMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/api/user/:id',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getResetarSenhaMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/user/reset-password/:id/:password',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getAtualizarPermissoesMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/api/user/update-permissions/:id/:centerId',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getBuscarTodasPermissoesPorCentroMockHandler = (
  overrideResponse?:
    | string[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<string[]> | string[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/user/get-all-permissions-by-center/:userId/:centerId',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getBuscarTodasPermissoesPorCentroResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getEncerrarSessaoMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/user/logout/:userId',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};
export const getUserMock = () => [
  getCriarUsuarioMockHandler(),
  getCriarUsuarioEmMassaMockHandler(),
  getListarUsuariosMockHandler(),
  getUserControllerInfoMeMockHandler(),
  getGetRolesMockHandler(),
  getCriarRoleMockHandler(),
  getDeletarUsuarioMockHandler(),
  getAtualizarUsuarioMockHandler(),
  getResetarSenhaMockHandler(),
  getAtualizarPermissoesMockHandler(),
  getBuscarTodasPermissoesPorCentroMockHandler(),
  getEncerrarSessaoMockHandler(),
];
