/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import zod from 'zod';


/**
 * @summary Buscar a produtividade dia a dia
 */
export const dashDiaDiaResponseProdutividadeItemTotalCaixasMinOne = -9007199254740991;
export const dashDiaDiaResponseProdutividadeItemTotalCaixasMaxOne = 9007199254740991;export const dashDiaDiaResponseTop5ProdutividadeItemTotalCaixasMinOne = -9007199254740991;
export const dashDiaDiaResponseTop5ProdutividadeItemTotalCaixasMaxOne = 9007199254740991;export const dashDiaDiaResponseTop5ProdutividadeItemTotalDemandasMinOne = -9007199254740991;
export const dashDiaDiaResponseTop5ProdutividadeItemTotalDemandasMaxOne = 9007199254740991;export const dashDiaDiaResponseTop5ProdutividadeItemTotalEnderecosVisitadosMinOne = -9007199254740991;
export const dashDiaDiaResponseTop5ProdutividadeItemTotalEnderecosVisitadosMaxOne = 9007199254740991;export const dashDiaDiaResponseBottom5ProdutividadeItemTotalCaixasMinOne = -9007199254740991;
export const dashDiaDiaResponseBottom5ProdutividadeItemTotalCaixasMaxOne = 9007199254740991;export const dashDiaDiaResponseBottom5ProdutividadeItemTotalDemandasMinOne = -9007199254740991;
export const dashDiaDiaResponseBottom5ProdutividadeItemTotalDemandasMaxOne = 9007199254740991;export const dashDiaDiaResponseBottom5ProdutividadeItemTotalEnderecosVisitadosMinOne = -9007199254740991;
export const dashDiaDiaResponseBottom5ProdutividadeItemTotalEnderecosVisitadosMaxOne = 9007199254740991;export const dashDiaDiaResponseProdutividadeProcessoItemTotalCaixasMinOne = -9007199254740991;
export const dashDiaDiaResponseProdutividadeProcessoItemTotalCaixasMaxOne = 9007199254740991;export const dashDiaDiaResponseProdutividadeProcessoItemTotalDemandasMinOne = -9007199254740991;
export const dashDiaDiaResponseProdutividadeProcessoItemTotalDemandasMaxOne = 9007199254740991;export const dashDiaDiaResponseProdutividadeProcessoItemTotalEnderecosVisitadosMinOne = -9007199254740991;
export const dashDiaDiaResponseProdutividadeProcessoItemTotalEnderecosVisitadosMaxOne = 9007199254740991;export const dashDiaDiaResponseListaProdutividadePorFuncionarioItemTotalCaixasMinOne = -9007199254740991;
export const dashDiaDiaResponseListaProdutividadePorFuncionarioItemTotalCaixasMaxOne = 9007199254740991;export const dashDiaDiaResponseListaProdutividadePorFuncionarioItemTotalDemandasMinOne = -9007199254740991;
export const dashDiaDiaResponseListaProdutividadePorFuncionarioItemTotalDemandasMaxOne = 9007199254740991;export const dashDiaDiaResponseListaProdutividadePorFuncionarioItemTotalEnderecosVisitadosMinOne = -9007199254740991;
export const dashDiaDiaResponseListaProdutividadePorFuncionarioItemTotalEnderecosVisitadosMaxOne = 9007199254740991;

export const dashDiaDiaResponse = zod.object({
  "produtividade": zod.array(zod.object({
  "centerid": zod.union([zod.string(),zod.null()]),
  "data": zod.union([zod.string(),zod.null()]),
  "totalTempoPausa": zod.union([zod.string(),zod.null()]),
  "totalCaixas": zod.union([zod.number().min(dashDiaDiaResponseProdutividadeItemTotalCaixasMinOne).max(dashDiaDiaResponseProdutividadeItemTotalCaixasMaxOne),zod.null()]),
  "tempoTotal": zod.union([zod.string(),zod.null()]),
  "tempoTrabalhado": zod.union([zod.string(),zod.null()]),
  "processo": zod.union([zod.enum(['SEPARACAO', 'CARREGAMENTO', 'CONFERENCIA']),zod.null()]),
  "produtividadeCaixaPorHora": zod.union([zod.string(),zod.null()])
})),
  "top5Produtividade": zod.array(zod.object({
  "funcionarioid": zod.union([zod.string(),zod.null()]),
  "funcionarionome": zod.union([zod.string(),zod.null()]),
  "processo": zod.union([zod.enum(['SEPARACAO', 'CARREGAMENTO', 'CONFERENCIA']),zod.null()]),
  "centerid": zod.union([zod.string(),zod.null()]),
  "dataregistro": zod.union([zod.string(),zod.null()]),
  "periodoInicio": zod.union([zod.string(),zod.null()]),
  "periodoFim": zod.union([zod.string(),zod.null()]),
  "totalTempoPausa": zod.union([zod.string(),zod.null()]),
  "totalCaixas": zod.union([zod.number().min(dashDiaDiaResponseTop5ProdutividadeItemTotalCaixasMinOne).max(dashDiaDiaResponseTop5ProdutividadeItemTotalCaixasMaxOne),zod.null()]),
  "tempoTotal": zod.union([zod.string(),zod.null()]),
  "totalDemandas": zod.union([zod.number().min(dashDiaDiaResponseTop5ProdutividadeItemTotalDemandasMinOne).max(dashDiaDiaResponseTop5ProdutividadeItemTotalDemandasMaxOne),zod.null()]),
  "totalEnderecosVisitados": zod.union([zod.number().min(dashDiaDiaResponseTop5ProdutividadeItemTotalEnderecosVisitadosMinOne).max(dashDiaDiaResponseTop5ProdutividadeItemTotalEnderecosVisitadosMaxOne),zod.null()]),
  "tempoTrabalhado": zod.union([zod.string(),zod.null()]),
  "produtividadeCaixaPorHora": zod.union([zod.string(),zod.null()]),
  "mediaEnderecosPorDemanda": zod.union([zod.string(),zod.null()]),
  "segmento": zod.union([zod.string(),zod.null()])
})),
  "bottom5Produtividade": zod.array(zod.object({
  "funcionarioid": zod.union([zod.string(),zod.null()]),
  "funcionarionome": zod.union([zod.string(),zod.null()]),
  "processo": zod.union([zod.enum(['SEPARACAO', 'CARREGAMENTO', 'CONFERENCIA']),zod.null()]),
  "centerid": zod.union([zod.string(),zod.null()]),
  "dataregistro": zod.union([zod.string(),zod.null()]),
  "periodoInicio": zod.union([zod.string(),zod.null()]),
  "periodoFim": zod.union([zod.string(),zod.null()]),
  "totalTempoPausa": zod.union([zod.string(),zod.null()]),
  "totalCaixas": zod.union([zod.number().min(dashDiaDiaResponseBottom5ProdutividadeItemTotalCaixasMinOne).max(dashDiaDiaResponseBottom5ProdutividadeItemTotalCaixasMaxOne),zod.null()]),
  "tempoTotal": zod.union([zod.string(),zod.null()]),
  "totalDemandas": zod.union([zod.number().min(dashDiaDiaResponseBottom5ProdutividadeItemTotalDemandasMinOne).max(dashDiaDiaResponseBottom5ProdutividadeItemTotalDemandasMaxOne),zod.null()]),
  "totalEnderecosVisitados": zod.union([zod.number().min(dashDiaDiaResponseBottom5ProdutividadeItemTotalEnderecosVisitadosMinOne).max(dashDiaDiaResponseBottom5ProdutividadeItemTotalEnderecosVisitadosMaxOne),zod.null()]),
  "tempoTrabalhado": zod.union([zod.string(),zod.null()]),
  "produtividadeCaixaPorHora": zod.union([zod.string(),zod.null()]),
  "mediaEnderecosPorDemanda": zod.union([zod.string(),zod.null()]),
  "segmento": zod.union([zod.string(),zod.null()])
})),
  "produtividadeProcesso": zod.array(zod.object({
  "centerid": zod.union([zod.string(),zod.null()]),
  "processo": zod.union([zod.enum(['SEPARACAO', 'CARREGAMENTO', 'CONFERENCIA']),zod.null()]),
  "turno": zod.union([zod.enum(['MANHA', 'TARDE', 'NOITE', 'INTERMEDIARIO', 'ADMINISTRATIVO']),zod.null()]),
  "criadoem": zod.union([zod.string(),zod.null()]),
  "periodoInicio": zod.union([zod.string(),zod.null()]),
  "periodoFim": zod.union([zod.string(),zod.null()]),
  "totalTempoPausa": zod.union([zod.string(),zod.null()]),
  "totalCaixas": zod.union([zod.number().min(dashDiaDiaResponseProdutividadeProcessoItemTotalCaixasMinOne).max(dashDiaDiaResponseProdutividadeProcessoItemTotalCaixasMaxOne),zod.null()]),
  "tempoTotal": zod.union([zod.string(),zod.null()]),
  "totalDemandas": zod.union([zod.number().min(dashDiaDiaResponseProdutividadeProcessoItemTotalDemandasMinOne).max(dashDiaDiaResponseProdutividadeProcessoItemTotalDemandasMaxOne),zod.null()]),
  "totalEnderecosVisitados": zod.union([zod.number().min(dashDiaDiaResponseProdutividadeProcessoItemTotalEnderecosVisitadosMinOne).max(dashDiaDiaResponseProdutividadeProcessoItemTotalEnderecosVisitadosMaxOne),zod.null()]),
  "tempoTrabalhado": zod.union([zod.string(),zod.null()]),
  "produtividadeCaixaPorHora": zod.union([zod.string(),zod.null()]),
  "mediaEnderecosPorDemanda": zod.union([zod.string(),zod.null()])
})),
  "listaProdutividadePorFuncionario": zod.array(zod.object({
  "funcionarioid": zod.union([zod.string(),zod.null()]),
  "funcionarionome": zod.union([zod.string(),zod.null()]),
  "processo": zod.union([zod.enum(['SEPARACAO', 'CARREGAMENTO', 'CONFERENCIA']),zod.null()]),
  "centerid": zod.union([zod.string(),zod.null()]),
  "dataregistro": zod.union([zod.string(),zod.null()]),
  "periodoInicio": zod.union([zod.string(),zod.null()]),
  "periodoFim": zod.union([zod.string(),zod.null()]),
  "totalTempoPausa": zod.union([zod.string(),zod.null()]),
  "totalCaixas": zod.union([zod.number().min(dashDiaDiaResponseListaProdutividadePorFuncionarioItemTotalCaixasMinOne).max(dashDiaDiaResponseListaProdutividadePorFuncionarioItemTotalCaixasMaxOne),zod.null()]),
  "tempoTotal": zod.union([zod.string(),zod.null()]),
  "totalDemandas": zod.union([zod.number().min(dashDiaDiaResponseListaProdutividadePorFuncionarioItemTotalDemandasMinOne).max(dashDiaDiaResponseListaProdutividadePorFuncionarioItemTotalDemandasMaxOne),zod.null()]),
  "totalEnderecosVisitados": zod.union([zod.number().min(dashDiaDiaResponseListaProdutividadePorFuncionarioItemTotalEnderecosVisitadosMinOne).max(dashDiaDiaResponseListaProdutividadePorFuncionarioItemTotalEnderecosVisitadosMaxOne),zod.null()]),
  "tempoTrabalhado": zod.union([zod.string(),zod.null()]),
  "produtividadeCaixaPorHora": zod.union([zod.string(),zod.null()]),
  "mediaEnderecosPorDemanda": zod.union([zod.string(),zod.null()]),
  "segmento": zod.union([zod.string(),zod.null()])
}))
})

/**
 * @summary Buscar paletes em aberto
 */
export const getPaletesEmAbertoParams = zod.object({
  "centerId": zod.string(),
  "data": zod.string(),
  "processo": zod.string()
})

export const getPaletesEmAbertoResponseItem = zod.object({
  "palete_id": zod.string(),
  "empresa": zod.string(),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "quantidadePaletes": zod.number(),
  "enderecoVisitado": zod.number(),
  "segmento": zod.string(),
  "tipoProcesso": zod.enum(['SEPARACAO', 'CONFERENCIA', 'CARREGAMENTO']),
  "status_palete": zod.string(),
  "transporteId": zod.string(),
  "centerId": zod.string(),
  "data_expedicao": zod.string()
})
export const getPaletesEmAbertoResponse = zod.array(getPaletesEmAbertoResponseItem)

