/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CenterDto,
  CenterDtoOutput,
  ConfiguracaoImpressaoMapaDto,
  ConfiguracaoImpressaoMapaDtoOutput,
  EngineRuleCreateDto,
  EngineRuleGetDto,
  EngineRuleUpdateDto,
  UpdateCenterDto,
} from '../../model';

import { axiosFetcher } from '../../../http/axios.http';
import type { ErrorType, BodyType } from '../../../http/axios.http';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Cria novo centro
 */
export const criarNovoCentro = (
  centerDto: BodyType<CenterDto>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<CenterDtoOutput>(
    {
      url: `/api/center`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: centerDto,
      signal,
    },
    options,
  );
};

export const getCriarNovoCentroMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarNovoCentro>>,
    TError,
    { data: BodyType<CenterDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarNovoCentro>>,
  TError,
  { data: BodyType<CenterDto> },
  TContext
> => {
  const mutationKey = ['criarNovoCentro'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarNovoCentro>>,
    { data: BodyType<CenterDto> }
  > = (props) => {
    const { data } = props ?? {};

    return criarNovoCentro(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarNovoCentroMutationResult = NonNullable<
  Awaited<ReturnType<typeof criarNovoCentro>>
>;
export type CriarNovoCentroMutationBody = BodyType<CenterDto>;
export type CriarNovoCentroMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Cria novo centro
 */
export const useCriarNovoCentro = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarNovoCentro>>,
      TError,
      { data: BodyType<CenterDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarNovoCentro>>,
  TError,
  { data: BodyType<CenterDto> },
  TContext
> => {
  const mutationOptions = getCriarNovoCentroMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Buscar todos os centros
 */
export const buscarTodosCentros = (
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<CenterDtoOutput[]>(
    { url: `/api/center`, method: 'GET', signal },
    options,
  );
};

export const getBuscarTodosCentrosQueryKey = () => {
  return [`/api/center`] as const;
};

export const getBuscarTodosCentrosQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarTodosCentros>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof buscarTodosCentros>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBuscarTodosCentrosQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof buscarTodosCentros>>
  > = ({ signal }) => buscarTodosCentros(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof buscarTodosCentros>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BuscarTodosCentrosQueryResult = NonNullable<
  Awaited<ReturnType<typeof buscarTodosCentros>>
>;
export type BuscarTodosCentrosQueryError = ErrorType<
  void | void | void | void | void | void
>;

export function useBuscarTodosCentros<
  TData = Awaited<ReturnType<typeof buscarTodosCentros>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodosCentros>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarTodosCentros>>,
          TError,
          Awaited<ReturnType<typeof buscarTodosCentros>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarTodosCentros<
  TData = Awaited<ReturnType<typeof buscarTodosCentros>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodosCentros>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarTodosCentros>>,
          TError,
          Awaited<ReturnType<typeof buscarTodosCentros>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarTodosCentros<
  TData = Awaited<ReturnType<typeof buscarTodosCentros>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodosCentros>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar todos os centros
 */

export function useBuscarTodosCentros<
  TData = Awaited<ReturnType<typeof buscarTodosCentros>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodosCentros>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBuscarTodosCentrosQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Buscar um centro
 */
export const centerControllerFindOne = (
  id: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<CenterDtoOutput>(
    { url: `/api/center/${id}`, method: 'GET', signal },
    options,
  );
};

export const getCenterControllerFindOneQueryKey = (id?: string) => {
  return [`/api/center/${id}`] as const;
};

export const getCenterControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof centerControllerFindOne>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof centerControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCenterControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof centerControllerFindOne>>
  > = ({ signal }) => centerControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof centerControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CenterControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof centerControllerFindOne>>
>;
export type CenterControllerFindOneQueryError = ErrorType<
  void | void | void | void | void | void
>;

export function useCenterControllerFindOne<
  TData = Awaited<ReturnType<typeof centerControllerFindOne>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof centerControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof centerControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof centerControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCenterControllerFindOne<
  TData = Awaited<ReturnType<typeof centerControllerFindOne>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof centerControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof centerControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof centerControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCenterControllerFindOne<
  TData = Awaited<ReturnType<typeof centerControllerFindOne>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof centerControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar um centro
 */

export function useCenterControllerFindOne<
  TData = Awaited<ReturnType<typeof centerControllerFindOne>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof centerControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCenterControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Atualizar um centro
 */
export const centerControllerUpdate = (
  id: string,
  updateCenterDto: BodyType<UpdateCenterDto>,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<void>(
    {
      url: `/api/center/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateCenterDto,
    },
    options,
  );
};

export const getCenterControllerUpdateMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof centerControllerUpdate>>,
    TError,
    { id: string; data: BodyType<UpdateCenterDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof centerControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdateCenterDto> },
  TContext
> => {
  const mutationKey = ['centerControllerUpdate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof centerControllerUpdate>>,
    { id: string; data: BodyType<UpdateCenterDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return centerControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CenterControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof centerControllerUpdate>>
>;
export type CenterControllerUpdateMutationBody = BodyType<UpdateCenterDto>;
export type CenterControllerUpdateMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Atualizar um centro
 */
export const useCenterControllerUpdate = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof centerControllerUpdate>>,
      TError,
      { id: string; data: BodyType<UpdateCenterDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof centerControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdateCenterDto> },
  TContext
> => {
  const mutationOptions = getCenterControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Deletar um centro
 */
export const centerControllerRemove = (
  id: string,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<void>(
    { url: `/api/center/${id}`, method: 'DELETE' },
    options,
  );
};

export const getCenterControllerRemoveMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof centerControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof centerControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['centerControllerRemove'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof centerControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return centerControllerRemove(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CenterControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof centerControllerRemove>>
>;

export type CenterControllerRemoveMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Deletar um centro
 */
export const useCenterControllerRemove = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof centerControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof centerControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getCenterControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Buscar configuração de impressão de mapa por centro e empresa
 */
export const buscarConfiguracaoPorCentro = (
  centerId: string,
  empresa: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<ConfiguracaoImpressaoMapaDtoOutput>(
    {
      url: `/api/center/${centerId}/config/mapa/${empresa}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getBuscarConfiguracaoPorCentroQueryKey = (
  centerId?: string,
  empresa?: string,
) => {
  return [`/api/center/${centerId}/config/mapa/${empresa}`] as const;
};

export const getBuscarConfiguracaoPorCentroQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  empresa: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getBuscarConfiguracaoPorCentroQueryKey(centerId, empresa);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>
  > = ({ signal }) =>
    buscarConfiguracaoPorCentro(centerId, empresa, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(centerId && empresa),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BuscarConfiguracaoPorCentroQueryResult = NonNullable<
  Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>
>;
export type BuscarConfiguracaoPorCentroQueryError = ErrorType<
  void | void | void | void | void | void
>;

export function useBuscarConfiguracaoPorCentro<
  TData = Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  empresa: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>,
          TError,
          Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarConfiguracaoPorCentro<
  TData = Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  empresa: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>,
          TError,
          Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarConfiguracaoPorCentro<
  TData = Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  empresa: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar configuração de impressão de mapa por centro e empresa
 */

export function useBuscarConfiguracaoPorCentro<
  TData = Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  empresa: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarConfiguracaoPorCentro>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBuscarConfiguracaoPorCentroQueryOptions(
    centerId,
    empresa,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Configurar impressão de mapa por centro e empresa
 */
export const criarConfiguracaoImpressao = (
  centerId: string,
  configuracaoImpressaoMapaDto: BodyType<ConfiguracaoImpressaoMapaDto>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<ConfiguracaoImpressaoMapaDtoOutput>(
    {
      url: `/api/center/${centerId}/config/mapa`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: configuracaoImpressaoMapaDto,
      signal,
    },
    options,
  );
};

export const getCriarConfiguracaoImpressaoMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarConfiguracaoImpressao>>,
    TError,
    { centerId: string; data: BodyType<ConfiguracaoImpressaoMapaDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarConfiguracaoImpressao>>,
  TError,
  { centerId: string; data: BodyType<ConfiguracaoImpressaoMapaDto> },
  TContext
> => {
  const mutationKey = ['criarConfiguracaoImpressao'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarConfiguracaoImpressao>>,
    { centerId: string; data: BodyType<ConfiguracaoImpressaoMapaDto> }
  > = (props) => {
    const { centerId, data } = props ?? {};

    return criarConfiguracaoImpressao(centerId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarConfiguracaoImpressaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof criarConfiguracaoImpressao>>
>;
export type CriarConfiguracaoImpressaoMutationBody =
  BodyType<ConfiguracaoImpressaoMapaDto>;
export type CriarConfiguracaoImpressaoMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Configurar impressão de mapa por centro e empresa
 */
export const useCriarConfiguracaoImpressao = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarConfiguracaoImpressao>>,
      TError,
      { centerId: string; data: BodyType<ConfiguracaoImpressaoMapaDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarConfiguracaoImpressao>>,
  TError,
  { centerId: string; data: BodyType<ConfiguracaoImpressaoMapaDto> },
  TContext
> => {
  const mutationOptions = getCriarConfiguracaoImpressaoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Cria nova regra de motor
 */
export const criarNovaRegraDeMotor = (
  engineRuleCreateDto: BodyType<EngineRuleCreateDto>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<EngineRuleCreateDto>(
    {
      url: `/api/center/engine-rules`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: engineRuleCreateDto,
      signal,
    },
    options,
  );
};

export const getCriarNovaRegraDeMotorMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarNovaRegraDeMotor>>,
    TError,
    { data: BodyType<EngineRuleCreateDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarNovaRegraDeMotor>>,
  TError,
  { data: BodyType<EngineRuleCreateDto> },
  TContext
> => {
  const mutationKey = ['criarNovaRegraDeMotor'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarNovaRegraDeMotor>>,
    { data: BodyType<EngineRuleCreateDto> }
  > = (props) => {
    const { data } = props ?? {};

    return criarNovaRegraDeMotor(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarNovaRegraDeMotorMutationResult = NonNullable<
  Awaited<ReturnType<typeof criarNovaRegraDeMotor>>
>;
export type CriarNovaRegraDeMotorMutationBody = BodyType<EngineRuleCreateDto>;
export type CriarNovaRegraDeMotorMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Cria nova regra de motor
 */
export const useCriarNovaRegraDeMotor = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarNovaRegraDeMotor>>,
      TError,
      { data: BodyType<EngineRuleCreateDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarNovaRegraDeMotor>>,
  TError,
  { data: BodyType<EngineRuleCreateDto> },
  TContext
> => {
  const mutationOptions = getCriarNovaRegraDeMotorMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Busca todas as regras de motor
 */
export const buscarTodasRegrasDeMotor = (
  centerId: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<EngineRuleGetDto[]>(
    { url: `/api/center/${centerId}/engine-rules`, method: 'GET', signal },
    options,
  );
};

export const getBuscarTodasRegrasDeMotorQueryKey = (centerId?: string) => {
  return [`/api/center/${centerId}/engine-rules`] as const;
};

export const getBuscarTodasRegrasDeMotorQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getBuscarTodasRegrasDeMotorQueryKey(centerId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>
  > = ({ signal }) =>
    buscarTodasRegrasDeMotor(centerId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!centerId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BuscarTodasRegrasDeMotorQueryResult = NonNullable<
  Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>
>;
export type BuscarTodasRegrasDeMotorQueryError = ErrorType<
  void | void | void | void | void | void
>;

export function useBuscarTodasRegrasDeMotor<
  TData = Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>,
          TError,
          Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarTodasRegrasDeMotor<
  TData = Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>,
          TError,
          Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarTodasRegrasDeMotor<
  TData = Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Busca todas as regras de motor
 */

export function useBuscarTodasRegrasDeMotor<
  TData = Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodasRegrasDeMotor>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBuscarTodasRegrasDeMotorQueryOptions(
    centerId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Atualiza uma regra de motor
 */
export const atualizarRegraDeMotor = (
  id: string,
  engineRuleUpdateDto: BodyType<EngineRuleUpdateDto>,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<void>(
    {
      url: `/api/center/engine-rules/update/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: engineRuleUpdateDto,
    },
    options,
  );
};

export const getAtualizarRegraDeMotorMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof atualizarRegraDeMotor>>,
    TError,
    { id: string; data: BodyType<EngineRuleUpdateDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof atualizarRegraDeMotor>>,
  TError,
  { id: string; data: BodyType<EngineRuleUpdateDto> },
  TContext
> => {
  const mutationKey = ['atualizarRegraDeMotor'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof atualizarRegraDeMotor>>,
    { id: string; data: BodyType<EngineRuleUpdateDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return atualizarRegraDeMotor(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AtualizarRegraDeMotorMutationResult = NonNullable<
  Awaited<ReturnType<typeof atualizarRegraDeMotor>>
>;
export type AtualizarRegraDeMotorMutationBody = BodyType<EngineRuleUpdateDto>;
export type AtualizarRegraDeMotorMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Atualiza uma regra de motor
 */
export const useAtualizarRegraDeMotor = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof atualizarRegraDeMotor>>,
      TError,
      { id: string; data: BodyType<EngineRuleUpdateDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof atualizarRegraDeMotor>>,
  TError,
  { id: string; data: BodyType<EngineRuleUpdateDto> },
  TContext
> => {
  const mutationOptions = getAtualizarRegraDeMotorMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Deleta uma regra de motor
 */
export const deletarRegraDeMotor = (
  id: string,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<void>(
    { url: `/api/center/engine-rules/delete/${id}`, method: 'DELETE' },
    options,
  );
};

export const getDeletarRegraDeMotorMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletarRegraDeMotor>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletarRegraDeMotor>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deletarRegraDeMotor'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletarRegraDeMotor>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deletarRegraDeMotor(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletarRegraDeMotorMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletarRegraDeMotor>>
>;

export type DeletarRegraDeMotorMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Deleta uma regra de motor
 */
export const useDeletarRegraDeMotor = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletarRegraDeMotor>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletarRegraDeMotor>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeletarRegraDeMotorMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
