/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateAnomaliaContagemLiteDto,
  CreateContagemDto,
  CreateMovimentacaoDto,
  GetAnomaliaContagemDto,
  GetContagemDto,
  GetMovimentacaoDto,
  ResumoContagemLiteDto,
  UpdateMovimentacaoDto,
} from '../../model';

import { axiosFetcher } from '../../../http/axios.http';
import type { ErrorType, BodyType } from '../../../http/axios.http';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Criar uma movimentação
 */
export const criarNovaMovimentacao = (
  createMovimentacaoDto: BodyType<CreateMovimentacaoDto[]>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<GetMovimentacaoDto>(
    {
      url: `/api/movimentacao`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createMovimentacaoDto,
      signal,
    },
    options,
  );
};

export const getCriarNovaMovimentacaoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarNovaMovimentacao>>,
    TError,
    { data: BodyType<CreateMovimentacaoDto[]> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarNovaMovimentacao>>,
  TError,
  { data: BodyType<CreateMovimentacaoDto[]> },
  TContext
> => {
  const mutationKey = ['criarNovaMovimentacao'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarNovaMovimentacao>>,
    { data: BodyType<CreateMovimentacaoDto[]> }
  > = (props) => {
    const { data } = props ?? {};

    return criarNovaMovimentacao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarNovaMovimentacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof criarNovaMovimentacao>>
>;
export type CriarNovaMovimentacaoMutationBody = BodyType<
  CreateMovimentacaoDto[]
>;
export type CriarNovaMovimentacaoMutationError = ErrorType<unknown>;

/**
 * @summary Criar uma movimentação
 */
export const useCriarNovaMovimentacao = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarNovaMovimentacao>>,
      TError,
      { data: BodyType<CreateMovimentacaoDto[]> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarNovaMovimentacao>>,
  TError,
  { data: BodyType<CreateMovimentacaoDto[]> },
  TContext
> => {
  const mutationOptions = getCriarNovaMovimentacaoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Buscar todas as movimentações pendentes
 */
export const findAllPending = (
  centerId: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<GetMovimentacaoDto[]>(
    { url: `/api/movimentacao/pending/${centerId}`, method: 'GET', signal },
    options,
  );
};

export const getFindAllPendingQueryKey = (centerId?: string) => {
  return [`/api/movimentacao/pending/${centerId}`] as const;
};

export const getFindAllPendingQueryOptions = <
  TData = Awaited<ReturnType<typeof findAllPending>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findAllPending>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFindAllPendingQueryKey(centerId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllPending>>> = ({
    signal,
  }) => findAllPending(centerId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!centerId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof findAllPending>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindAllPendingQueryResult = NonNullable<
  Awaited<ReturnType<typeof findAllPending>>
>;
export type FindAllPendingQueryError = ErrorType<unknown>;

export function useFindAllPending<
  TData = Awaited<ReturnType<typeof findAllPending>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findAllPending>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllPending>>,
          TError,
          Awaited<ReturnType<typeof findAllPending>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindAllPending<
  TData = Awaited<ReturnType<typeof findAllPending>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findAllPending>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllPending>>,
          TError,
          Awaited<ReturnType<typeof findAllPending>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindAllPending<
  TData = Awaited<ReturnType<typeof findAllPending>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findAllPending>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar todas as movimentações pendentes
 */

export function useFindAllPending<
  TData = Awaited<ReturnType<typeof findAllPending>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findAllPending>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindAllPendingQueryOptions(centerId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const movimentacaoControllerFindOne = (
  id: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<void>(
    { url: `/api/movimentacao/${id}`, method: 'GET', signal },
    options,
  );
};

export const getMovimentacaoControllerFindOneQueryKey = (id?: string) => {
  return [`/api/movimentacao/${id}`] as const;
};

export const getMovimentacaoControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof movimentacaoControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof movimentacaoControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getMovimentacaoControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof movimentacaoControllerFindOne>>
  > = ({ signal }) => movimentacaoControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof movimentacaoControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MovimentacaoControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof movimentacaoControllerFindOne>>
>;
export type MovimentacaoControllerFindOneQueryError = ErrorType<unknown>;

export function useMovimentacaoControllerFindOne<
  TData = Awaited<ReturnType<typeof movimentacaoControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof movimentacaoControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof movimentacaoControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof movimentacaoControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMovimentacaoControllerFindOne<
  TData = Awaited<ReturnType<typeof movimentacaoControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof movimentacaoControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof movimentacaoControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof movimentacaoControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMovimentacaoControllerFindOne<
  TData = Awaited<ReturnType<typeof movimentacaoControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof movimentacaoControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useMovimentacaoControllerFindOne<
  TData = Awaited<ReturnType<typeof movimentacaoControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof movimentacaoControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getMovimentacaoControllerFindOneQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Atualizar uma movimentação
 */
export const updateMovimentacao = (
  id: number,
  updateMovimentacaoDto: BodyType<UpdateMovimentacaoDto>,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<boolean>(
    {
      url: `/api/movimentacao/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateMovimentacaoDto,
    },
    options,
  );
};

export const getUpdateMovimentacaoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMovimentacao>>,
    TError,
    { id: number; data: BodyType<UpdateMovimentacaoDto> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMovimentacao>>,
  TError,
  { id: number; data: BodyType<UpdateMovimentacaoDto> },
  TContext
> => {
  const mutationKey = ['updateMovimentacao'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMovimentacao>>,
    { id: number; data: BodyType<UpdateMovimentacaoDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateMovimentacao(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMovimentacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMovimentacao>>
>;
export type UpdateMovimentacaoMutationBody = BodyType<UpdateMovimentacaoDto>;
export type UpdateMovimentacaoMutationError = ErrorType<unknown>;

/**
 * @summary Atualizar uma movimentação
 */
export const useUpdateMovimentacao = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateMovimentacao>>,
      TError,
      { id: number; data: BodyType<UpdateMovimentacaoDto> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateMovimentacao>>,
  TError,
  { id: number; data: BodyType<UpdateMovimentacaoDto> },
  TContext
> => {
  const mutationOptions = getUpdateMovimentacaoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Remover uma movimentação
 */
export const removerMovimentacao = (
  id: number,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<boolean>(
    { url: `/api/movimentacao/${id}`, method: 'DELETE' },
    options,
  );
};

export const getRemoverMovimentacaoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removerMovimentacao>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removerMovimentacao>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['removerMovimentacao'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removerMovimentacao>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return removerMovimentacao(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoverMovimentacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof removerMovimentacao>>
>;

export type RemoverMovimentacaoMutationError = ErrorType<unknown>;

/**
 * @summary Remover uma movimentação
 */
export const useRemoverMovimentacao = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removerMovimentacao>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof removerMovimentacao>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getRemoverMovimentacaoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Buscar a próxima movimentação pendente
 */
export const getNextMovimentacao = (
  centerId: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<GetMovimentacaoDto>(
    { url: `/api/movimentacao/next/${centerId}`, method: 'GET', signal },
    options,
  );
};

export const getGetNextMovimentacaoQueryKey = (centerId?: string) => {
  return [`/api/movimentacao/next/${centerId}`] as const;
};

export const getGetNextMovimentacaoQueryOptions = <
  TData = Awaited<ReturnType<typeof getNextMovimentacao>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNextMovimentacao>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetNextMovimentacaoQueryKey(centerId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getNextMovimentacao>>
  > = ({ signal }) => getNextMovimentacao(centerId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!centerId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getNextMovimentacao>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNextMovimentacaoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNextMovimentacao>>
>;
export type GetNextMovimentacaoQueryError = ErrorType<unknown>;

export function useGetNextMovimentacao<
  TData = Awaited<ReturnType<typeof getNextMovimentacao>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNextMovimentacao>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNextMovimentacao>>,
          TError,
          Awaited<ReturnType<typeof getNextMovimentacao>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNextMovimentacao<
  TData = Awaited<ReturnType<typeof getNextMovimentacao>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNextMovimentacao>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNextMovimentacao>>,
          TError,
          Awaited<ReturnType<typeof getNextMovimentacao>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNextMovimentacao<
  TData = Awaited<ReturnType<typeof getNextMovimentacao>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNextMovimentacao>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar a próxima movimentação pendente
 */

export function useGetNextMovimentacao<
  TData = Awaited<ReturnType<typeof getNextMovimentacao>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNextMovimentacao>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetNextMovimentacaoQueryOptions(centerId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Validar uma movimentação
 */
export const validateMovimentacao = (
  id: string,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<boolean>(
    { url: `/api/movimentacao/${id}/validate`, method: 'PUT' },
    options,
  );
};

export const getValidateMovimentacaoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof validateMovimentacao>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof validateMovimentacao>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['validateMovimentacao'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof validateMovimentacao>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return validateMovimentacao(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ValidateMovimentacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof validateMovimentacao>>
>;

export type ValidateMovimentacaoMutationError = ErrorType<unknown>;

/**
 * @summary Validar uma movimentação
 */
export const useValidateMovimentacao = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof validateMovimentacao>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof validateMovimentacao>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getValidateMovimentacaoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Cadastrar uma anomalia
 */
export const cadastrarAnomalia = (
  id: string,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<boolean>(
    { url: `/api/movimentacao/${id}/anomalia`, method: 'PUT' },
    options,
  );
};

export const getCadastrarAnomaliaMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cadastrarAnomalia>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cadastrarAnomalia>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['cadastrarAnomalia'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cadastrarAnomalia>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return cadastrarAnomalia(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CadastrarAnomaliaMutationResult = NonNullable<
  Awaited<ReturnType<typeof cadastrarAnomalia>>
>;

export type CadastrarAnomaliaMutationError = ErrorType<unknown>;

/**
 * @summary Cadastrar uma anomalia
 */
export const useCadastrarAnomalia = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cadastrarAnomalia>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cadastrarAnomalia>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getCadastrarAnomaliaMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Registrar o início de uma movimentação
 */
export const registerStartMovement = (
  id: number,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<boolean>(
    { url: `/api/movimentacao/${id}/start`, method: 'PUT' },
    options,
  );
};

export const getRegisterStartMovementMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerStartMovement>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerStartMovement>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['registerStartMovement'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerStartMovement>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return registerStartMovement(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterStartMovementMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerStartMovement>>
>;

export type RegisterStartMovementMutationError = ErrorType<unknown>;

/**
 * @summary Registrar o início de uma movimentação
 */
export const useRegisterStartMovement = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof registerStartMovement>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof registerStartMovement>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getRegisterStartMovementMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Adicionar uma contagem lite validation
 */
export const addContagemLiteValidation = (
  createContagemDto: BodyType<CreateContagemDto[]>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<boolean>(
    {
      url: `/api/movimentacao/add-contagem-lite`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createContagemDto,
      signal,
    },
    options,
  );
};

export const getAddContagemLiteValidationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addContagemLiteValidation>>,
    TError,
    { data: BodyType<CreateContagemDto[]> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addContagemLiteValidation>>,
  TError,
  { data: BodyType<CreateContagemDto[]> },
  TContext
> => {
  const mutationKey = ['addContagemLiteValidation'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addContagemLiteValidation>>,
    { data: BodyType<CreateContagemDto[]> }
  > = (props) => {
    const { data } = props ?? {};

    return addContagemLiteValidation(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddContagemLiteValidationMutationResult = NonNullable<
  Awaited<ReturnType<typeof addContagemLiteValidation>>
>;
export type AddContagemLiteValidationMutationBody = BodyType<
  CreateContagemDto[]
>;
export type AddContagemLiteValidationMutationError = ErrorType<unknown>;

/**
 * @summary Adicionar uma contagem lite validation
 */
export const useAddContagemLiteValidation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addContagemLiteValidation>>,
      TError,
      { data: BodyType<CreateContagemDto[]> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addContagemLiteValidation>>,
  TError,
  { data: BodyType<CreateContagemDto[]> },
  TContext
> => {
  const mutationOptions = getAddContagemLiteValidationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Buscar uma contagem lite validation por endereço
 */
export const getEndereco = (
  endereco: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<GetContagemDto[]>(
    {
      url: `/api/movimentacao/get-endereco/${endereco}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getGetEnderecoQueryKey = (endereco?: string) => {
  return [`/api/movimentacao/get-endereco/${endereco}`] as const;
};

export const getGetEnderecoQueryOptions = <
  TData = Awaited<ReturnType<typeof getEndereco>>,
  TError = ErrorType<unknown>,
>(
  endereco: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEndereco>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetEnderecoQueryKey(endereco);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEndereco>>> = ({
    signal,
  }) => getEndereco(endereco, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!endereco,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getEndereco>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEnderecoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEndereco>>
>;
export type GetEnderecoQueryError = ErrorType<unknown>;

export function useGetEndereco<
  TData = Awaited<ReturnType<typeof getEndereco>>,
  TError = ErrorType<unknown>,
>(
  endereco: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEndereco>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEndereco>>,
          TError,
          Awaited<ReturnType<typeof getEndereco>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEndereco<
  TData = Awaited<ReturnType<typeof getEndereco>>,
  TError = ErrorType<unknown>,
>(
  endereco: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEndereco>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEndereco>>,
          TError,
          Awaited<ReturnType<typeof getEndereco>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEndereco<
  TData = Awaited<ReturnType<typeof getEndereco>>,
  TError = ErrorType<unknown>,
>(
  endereco: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEndereco>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar uma contagem lite validation por endereço
 */

export function useGetEndereco<
  TData = Awaited<ReturnType<typeof getEndereco>>,
  TError = ErrorType<unknown>,
>(
  endereco: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEndereco>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetEnderecoQueryOptions(endereco, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Validar um endereço
 */
export const validarEndereco = (
  endereco: string,
  centerId: string,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<boolean>(
    {
      url: `/api/movimentacao/validar-endereco/${endereco}/${centerId}`,
      method: 'PUT',
    },
    options,
  );
};

export const getValidarEnderecoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof validarEndereco>>,
    TError,
    { endereco: string; centerId: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof validarEndereco>>,
  TError,
  { endereco: string; centerId: string },
  TContext
> => {
  const mutationKey = ['validarEndereco'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof validarEndereco>>,
    { endereco: string; centerId: string }
  > = (props) => {
    const { endereco, centerId } = props ?? {};

    return validarEndereco(endereco, centerId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ValidarEnderecoMutationResult = NonNullable<
  Awaited<ReturnType<typeof validarEndereco>>
>;

export type ValidarEnderecoMutationError = ErrorType<unknown>;

/**
 * @summary Validar um endereço
 */
export const useValidarEndereco = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof validarEndereco>>,
      TError,
      { endereco: string; centerId: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof validarEndereco>>,
  TError,
  { endereco: string; centerId: string },
  TContext
> => {
  const mutationOptions = getValidarEnderecoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Adicionar uma anomalia contagem lite
 */
export const addAnomaliaContagemLite = (
  centerId: string,
  endereco: string,
  createAnomaliaContagemLiteDto: BodyType<CreateAnomaliaContagemLiteDto>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<boolean>(
    {
      url: `/api/movimentacao/add-anomalia-contagem-lite/${centerId}/${endereco}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createAnomaliaContagemLiteDto,
      signal,
    },
    options,
  );
};

export const getAddAnomaliaContagemLiteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addAnomaliaContagemLite>>,
    TError,
    {
      centerId: string;
      endereco: string;
      data: BodyType<CreateAnomaliaContagemLiteDto>;
    },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addAnomaliaContagemLite>>,
  TError,
  {
    centerId: string;
    endereco: string;
    data: BodyType<CreateAnomaliaContagemLiteDto>;
  },
  TContext
> => {
  const mutationKey = ['addAnomaliaContagemLite'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addAnomaliaContagemLite>>,
    {
      centerId: string;
      endereco: string;
      data: BodyType<CreateAnomaliaContagemLiteDto>;
    }
  > = (props) => {
    const { centerId, endereco, data } = props ?? {};

    return addAnomaliaContagemLite(centerId, endereco, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddAnomaliaContagemLiteMutationResult = NonNullable<
  Awaited<ReturnType<typeof addAnomaliaContagemLite>>
>;
export type AddAnomaliaContagemLiteMutationBody =
  BodyType<CreateAnomaliaContagemLiteDto>;
export type AddAnomaliaContagemLiteMutationError = ErrorType<unknown>;

/**
 * @summary Adicionar uma anomalia contagem lite
 */
export const useAddAnomaliaContagemLite = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addAnomaliaContagemLite>>,
      TError,
      {
        centerId: string;
        endereco: string;
        data: BodyType<CreateAnomaliaContagemLiteDto>;
      },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addAnomaliaContagemLite>>,
  TError,
  {
    centerId: string;
    endereco: string;
    data: BodyType<CreateAnomaliaContagemLiteDto>;
  },
  TContext
> => {
  const mutationOptions = getAddAnomaliaContagemLiteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Buscar o resumo da contagem lite
 */
export const resumoContagemLite = (
  centerId: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<ResumoContagemLiteDto[]>(
    {
      url: `/api/movimentacao/resumo-contagem-lite/${centerId}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getResumoContagemLiteQueryKey = (centerId?: string) => {
  return [`/api/movimentacao/resumo-contagem-lite/${centerId}`] as const;
};

export const getResumoContagemLiteQueryOptions = <
  TData = Awaited<ReturnType<typeof resumoContagemLite>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resumoContagemLite>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getResumoContagemLiteQueryKey(centerId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof resumoContagemLite>>
  > = ({ signal }) => resumoContagemLite(centerId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!centerId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof resumoContagemLite>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ResumoContagemLiteQueryResult = NonNullable<
  Awaited<ReturnType<typeof resumoContagemLite>>
>;
export type ResumoContagemLiteQueryError = ErrorType<unknown>;

export function useResumoContagemLite<
  TData = Awaited<ReturnType<typeof resumoContagemLite>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resumoContagemLite>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resumoContagemLite>>,
          TError,
          Awaited<ReturnType<typeof resumoContagemLite>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useResumoContagemLite<
  TData = Awaited<ReturnType<typeof resumoContagemLite>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resumoContagemLite>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resumoContagemLite>>,
          TError,
          Awaited<ReturnType<typeof resumoContagemLite>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useResumoContagemLite<
  TData = Awaited<ReturnType<typeof resumoContagemLite>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resumoContagemLite>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar o resumo da contagem lite
 */

export function useResumoContagemLite<
  TData = Awaited<ReturnType<typeof resumoContagemLite>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resumoContagemLite>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getResumoContagemLiteQueryOptions(centerId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Deletar a contagem lite
 */
export const deleteContagemLite = (
  centerId: string,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<boolean>(
    {
      url: `/api/movimentacao/delete-contagem-lite/${centerId}`,
      method: 'DELETE',
    },
    options,
  );
};

export const getDeleteContagemLiteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteContagemLite>>,
    TError,
    { centerId: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteContagemLite>>,
  TError,
  { centerId: string },
  TContext
> => {
  const mutationKey = ['deleteContagemLite'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteContagemLite>>,
    { centerId: string }
  > = (props) => {
    const { centerId } = props ?? {};

    return deleteContagemLite(centerId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteContagemLiteMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteContagemLite>>
>;

export type DeleteContagemLiteMutationError = ErrorType<unknown>;

/**
 * @summary Deletar a contagem lite
 */
export const useDeleteContagemLite = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteContagemLite>>,
      TError,
      { centerId: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteContagemLite>>,
  TError,
  { centerId: string },
  TContext
> => {
  const mutationOptions = getDeleteContagemLiteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Buscar o relatorio de anomalias da contagem lite
 */
export const relatorioAnomaliasContagemLite = (
  centerId: string,
  dataReferencia: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<GetAnomaliaContagemDto[]>(
    {
      url: `/api/movimentacao/relatorio-anomalias-contagem-lite/${centerId}/${dataReferencia}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getRelatorioAnomaliasContagemLiteQueryKey = (
  centerId?: string,
  dataReferencia?: string,
) => {
  return [
    `/api/movimentacao/relatorio-anomalias-contagem-lite/${centerId}/${dataReferencia}`,
  ] as const;
};

export const getRelatorioAnomaliasContagemLiteQueryOptions = <
  TData = Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  dataReferencia: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getRelatorioAnomaliasContagemLiteQueryKey(centerId, dataReferencia);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>
  > = ({ signal }) =>
    relatorioAnomaliasContagemLite(
      centerId,
      dataReferencia,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(centerId && dataReferencia),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RelatorioAnomaliasContagemLiteQueryResult = NonNullable<
  Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>
>;
export type RelatorioAnomaliasContagemLiteQueryError = ErrorType<unknown>;

export function useRelatorioAnomaliasContagemLite<
  TData = Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  dataReferencia: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>,
          TError,
          Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRelatorioAnomaliasContagemLite<
  TData = Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  dataReferencia: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>,
          TError,
          Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRelatorioAnomaliasContagemLite<
  TData = Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  dataReferencia: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar o relatorio de anomalias da contagem lite
 */

export function useRelatorioAnomaliasContagemLite<
  TData = Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  dataReferencia: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof relatorioAnomaliasContagemLite>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getRelatorioAnomaliasContagemLiteQueryOptions(
    centerId,
    dataReferencia,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
