/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AugmentedZodDto,
  BuscarTodosOsCortesDeProdutoParams,
  CorteMercadoriaDto,
  CorteMercadoriaGetDto,
} from '../../model';

import { axiosFetcher } from '../../../http/axios.http';
import type { ErrorType, BodyType } from '../../../http/axios.http';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Buscar produtos por transporte
 */
export const buscarProdutosPorTransporte = (
  centerId: string,
  transporteId: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<AugmentedZodDto[]>(
    {
      url: `/api/corte-produto/transporte/${centerId}/${transporteId}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getBuscarProdutosPorTransporteQueryKey = (
  centerId?: string,
  transporteId?: string,
) => {
  return [`/api/corte-produto/transporte/${centerId}/${transporteId}`] as const;
};

export const getBuscarProdutosPorTransporteQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarProdutosPorTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  transporteId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarProdutosPorTransporte>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getBuscarProdutosPorTransporteQueryKey(centerId, transporteId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof buscarProdutosPorTransporte>>
  > = ({ signal }) =>
    buscarProdutosPorTransporte(centerId, transporteId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(centerId && transporteId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof buscarProdutosPorTransporte>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BuscarProdutosPorTransporteQueryResult = NonNullable<
  Awaited<ReturnType<typeof buscarProdutosPorTransporte>>
>;
export type BuscarProdutosPorTransporteQueryError = ErrorType<
  void | void | void | void | void | void
>;

export function useBuscarProdutosPorTransporte<
  TData = Awaited<ReturnType<typeof buscarProdutosPorTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  transporteId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarProdutosPorTransporte>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarProdutosPorTransporte>>,
          TError,
          Awaited<ReturnType<typeof buscarProdutosPorTransporte>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarProdutosPorTransporte<
  TData = Awaited<ReturnType<typeof buscarProdutosPorTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  transporteId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarProdutosPorTransporte>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarProdutosPorTransporte>>,
          TError,
          Awaited<ReturnType<typeof buscarProdutosPorTransporte>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarProdutosPorTransporte<
  TData = Awaited<ReturnType<typeof buscarProdutosPorTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  transporteId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarProdutosPorTransporte>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar produtos por transporte
 */

export function useBuscarProdutosPorTransporte<
  TData = Awaited<ReturnType<typeof buscarProdutosPorTransporte>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  transporteId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarProdutosPorTransporte>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBuscarProdutosPorTransporteQueryOptions(
    centerId,
    transporteId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Criar corte de produto
 */
export const criarCorteDeProduto = (
  centerId: string,
  corteMercadoriaDto: BodyType<CorteMercadoriaDto[]>,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<void>(
    {
      url: `/api/corte-produto/${centerId}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: corteMercadoriaDto,
      signal,
    },
    options,
  );
};

export const getCriarCorteDeProdutoMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarCorteDeProduto>>,
    TError,
    { centerId: string; data: BodyType<CorteMercadoriaDto[]> },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarCorteDeProduto>>,
  TError,
  { centerId: string; data: BodyType<CorteMercadoriaDto[]> },
  TContext
> => {
  const mutationKey = ['criarCorteDeProduto'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarCorteDeProduto>>,
    { centerId: string; data: BodyType<CorteMercadoriaDto[]> }
  > = (props) => {
    const { centerId, data } = props ?? {};

    return criarCorteDeProduto(centerId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarCorteDeProdutoMutationResult = NonNullable<
  Awaited<ReturnType<typeof criarCorteDeProduto>>
>;
export type CriarCorteDeProdutoMutationBody = BodyType<CorteMercadoriaDto[]>;
export type CriarCorteDeProdutoMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Criar corte de produto
 */
export const useCriarCorteDeProduto = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarCorteDeProduto>>,
      TError,
      { centerId: string; data: BodyType<CorteMercadoriaDto[]> },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarCorteDeProduto>>,
  TError,
  { centerId: string; data: BodyType<CorteMercadoriaDto[]> },
  TContext
> => {
  const mutationOptions = getCriarCorteDeProdutoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Buscar todos os cortes de produto
 */
export const buscarTodosOsCortesDeProduto = (
  centerId: string,
  params?: BuscarTodosOsCortesDeProdutoParams,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<CorteMercadoriaGetDto[]>(
    { url: `/api/corte-produto/${centerId}`, method: 'GET', params, signal },
    options,
  );
};

export const getBuscarTodosOsCortesDeProdutoQueryKey = (
  centerId?: string,
  params?: BuscarTodosOsCortesDeProdutoParams,
) => {
  return [
    `/api/corte-produto/${centerId}`,
    ...(params ? [params] : []),
  ] as const;
};

export const getBuscarTodosOsCortesDeProdutoQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  params?: BuscarTodosOsCortesDeProdutoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getBuscarTodosOsCortesDeProdutoQueryKey(centerId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>
  > = ({ signal }) =>
    buscarTodosOsCortesDeProduto(centerId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!centerId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BuscarTodosOsCortesDeProdutoQueryResult = NonNullable<
  Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>
>;
export type BuscarTodosOsCortesDeProdutoQueryError = ErrorType<
  void | void | void | void | void | void
>;

export function useBuscarTodosOsCortesDeProduto<
  TData = Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  params: undefined | BuscarTodosOsCortesDeProdutoParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>,
          TError,
          Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarTodosOsCortesDeProduto<
  TData = Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  params?: BuscarTodosOsCortesDeProdutoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>,
          TError,
          Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useBuscarTodosOsCortesDeProduto<
  TData = Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  params?: BuscarTodosOsCortesDeProdutoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar todos os cortes de produto
 */

export function useBuscarTodosOsCortesDeProduto<
  TData = Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>,
  TError = ErrorType<void | void | void | void | void | void>,
>(
  centerId: string,
  params?: BuscarTodosOsCortesDeProdutoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof buscarTodosOsCortesDeProduto>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBuscarTodosOsCortesDeProdutoQueryOptions(
    centerId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Confirmar corte de produto
 */
export const confirmarCorteDeProduto = (
  id: string,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<void>(
    { url: `/api/corte-produto/${id}`, method: 'PUT' },
    options,
  );
};

export const getConfirmarCorteDeProdutoMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof confirmarCorteDeProduto>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof confirmarCorteDeProduto>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['confirmarCorteDeProduto'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof confirmarCorteDeProduto>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return confirmarCorteDeProduto(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ConfirmarCorteDeProdutoMutationResult = NonNullable<
  Awaited<ReturnType<typeof confirmarCorteDeProduto>>
>;

export type ConfirmarCorteDeProdutoMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Confirmar corte de produto
 */
export const useConfirmarCorteDeProduto = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof confirmarCorteDeProduto>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof confirmarCorteDeProduto>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getConfirmarCorteDeProdutoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Deletar corte de produto
 */
export const deletarCorteDeProduto = (
  id: string,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<void>(
    { url: `/api/corte-produto/${id}`, method: 'DELETE' },
    options,
  );
};

export const getDeletarCorteDeProdutoMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletarCorteDeProduto>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletarCorteDeProduto>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deletarCorteDeProduto'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletarCorteDeProduto>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deletarCorteDeProduto(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletarCorteDeProdutoMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletarCorteDeProduto>>
>;

export type DeletarCorteDeProdutoMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Deletar corte de produto
 */
export const useDeletarCorteDeProduto = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletarCorteDeProduto>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletarCorteDeProduto>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeletarCorteDeProdutoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Confirmar corte de produto por transporte
 */
export const confirmarCorteDeProdutoPorTransporte = (
  transporteId: string,
  options?: SecondParameter<typeof axiosFetcher>,
) => {
  return axiosFetcher<void>(
    {
      url: `/api/corte-produto/transporte/confirmar/${transporteId}`,
      method: 'PUT',
    },
    options,
  );
};

export const getConfirmarCorteDeProdutoPorTransporteMutationOptions = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof confirmarCorteDeProdutoPorTransporte>>,
    TError,
    { transporteId: string },
    TContext
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof confirmarCorteDeProdutoPorTransporte>>,
  TError,
  { transporteId: string },
  TContext
> => {
  const mutationKey = ['confirmarCorteDeProdutoPorTransporte'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof confirmarCorteDeProdutoPorTransporte>>,
    { transporteId: string }
  > = (props) => {
    const { transporteId } = props ?? {};

    return confirmarCorteDeProdutoPorTransporte(transporteId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ConfirmarCorteDeProdutoPorTransporteMutationResult = NonNullable<
  Awaited<ReturnType<typeof confirmarCorteDeProdutoPorTransporte>>
>;

export type ConfirmarCorteDeProdutoPorTransporteMutationError = ErrorType<
  void | void | void | void | void | void
>;

/**
 * @summary Confirmar corte de produto por transporte
 */
export const useConfirmarCorteDeProdutoPorTransporte = <
  TError = ErrorType<void | void | void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof confirmarCorteDeProdutoPorTransporte>>,
      TError,
      { transporteId: string },
      TContext
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof confirmarCorteDeProdutoPorTransporte>>,
  TError,
  { transporteId: string },
  TContext
> => {
  const mutationOptions =
    getConfirmarCorteDeProdutoPorTransporteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
