/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type { AugmentedZodDto, CorteMercadoriaGetDto } from '../../model';

export const getBuscarProdutosPorTransporteResponseMock =
  (): AugmentedZodDto[] =>
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      transporte: faker.string.alpha({ length: { min: 10, max: 20 } }),
      remessa: faker.string.alpha({ length: { min: 10, max: 20 } }),
      cliente: faker.string.alpha({ length: { min: 10, max: 20 } }),
      sku: faker.string.alpha({ length: { min: 10, max: 20 } }),
      descricao: faker.string.alpha({ length: { min: 10, max: 20 } }),
      placa: faker.string.alpha({ length: { min: 10, max: 20 } }),
      nomeCliente: faker.string.alpha({ length: { min: 10, max: 20 } }),
      lote: faker.string.alpha({ length: { min: 10, max: 20 } }),
      quantidade: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
      quantidadeCortada: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
      caixas: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
      caixasCortadas: faker.helpers.arrayElement([
        faker.number.float({
          min: undefined,
          max: undefined,
          fractionDigits: 2,
        }),
        undefined,
      ]),
      segmento: faker.string.alpha({ length: { min: 10, max: 20 } }),
      tipo: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
    }));

export const getBuscarTodosOsCortesDeProdutoResponseMock =
  (): CorteMercadoriaGetDto[] =>
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.number.int({ min: -2147483648, max: 2147483647 }),
      produto: faker.string.alpha({ length: { min: 10, max: 20 } }),
      lote: faker.string.alpha({ length: { min: 10, max: 20 } }),
      motivo: faker.helpers.arrayElement([
        'FALTA_MERCADORIA',
        'FALTA_ESPACO',
        'RECUSA_SEFAZ',
      ] as const),
      realizado: faker.datatype.boolean(),
      criadoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
      atualizadoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
      criadoPorId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      transporteId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      caixas: faker.number.int({ min: -2147483648, max: 2147483647 }),
      direcao: faker.helpers.arrayElement([
        'OPERACIONAL',
        'ADMINISTRATIVO',
      ] as const),
      unidades: faker.number.int({ min: -2147483648, max: 2147483647 }),
      centerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
      descricao: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      realizadoPorId: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
    }));

export const getBuscarProdutosPorTransporteMockHandler = (
  overrideResponse?:
    | AugmentedZodDto[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<AugmentedZodDto[]> | AugmentedZodDto[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/corte-produto/transporte/:centerId/:transporteId',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getBuscarProdutosPorTransporteResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getCriarCorteDeProdutoMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/corte-produto/:centerId',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getBuscarTodosOsCortesDeProdutoMockHandler = (
  overrideResponse?:
    | CorteMercadoriaGetDto[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CorteMercadoriaGetDto[]> | CorteMercadoriaGetDto[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/corte-produto/:centerId',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getBuscarTodosOsCortesDeProdutoResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getConfirmarCorteDeProdutoMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/api/corte-produto/:id',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getConfirmarCorteDeProdutoPorTransporteMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/api/corte-produto/transporte/confirmar/:transporteId',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getCorteProdutoMock = () => [
  getBuscarProdutosPorTransporteMockHandler(),
  getCriarCorteDeProdutoMockHandler(),
  getBuscarTodosOsCortesDeProdutoMockHandler(),
  getConfirmarCorteDeProdutoMockHandler(),
  getConfirmarCorteDeProdutoPorTransporteMockHandler(),
];
