/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ListVwProdutividadeDashParams,
  PaleteGetDataTransporteDto,
  ProdutividadeDiaDiaGetDataDto,
} from '../../model';

import { axiosFetcher } from '../../../http/axios.http';
import type { ErrorType } from '../../../http/axios.http';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Buscar a produtividade dia a dia
 */
export const dashDiaDia = (
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<ProdutividadeDiaDiaGetDataDto>(
    { url: `/api/produtividade-dash/dash-dia-dia`, method: 'GET', signal },
    options,
  );
};

export const getDashDiaDiaQueryKey = () => {
  return [`/api/produtividade-dash/dash-dia-dia`] as const;
};

export const getDashDiaDiaQueryOptions = <
  TData = Awaited<ReturnType<typeof dashDiaDia>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof dashDiaDia>>, TError, TData>
  >;
  request?: SecondParameter<typeof axiosFetcher>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDashDiaDiaQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dashDiaDia>>> = ({
    signal,
  }) => dashDiaDia(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof dashDiaDia>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DashDiaDiaQueryResult = NonNullable<
  Awaited<ReturnType<typeof dashDiaDia>>
>;
export type DashDiaDiaQueryError = ErrorType<unknown>;

export function useDashDiaDia<
  TData = Awaited<ReturnType<typeof dashDiaDia>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dashDiaDia>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashDiaDia>>,
          TError,
          Awaited<ReturnType<typeof dashDiaDia>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDashDiaDia<
  TData = Awaited<ReturnType<typeof dashDiaDia>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dashDiaDia>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashDiaDia>>,
          TError,
          Awaited<ReturnType<typeof dashDiaDia>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDashDiaDia<
  TData = Awaited<ReturnType<typeof dashDiaDia>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dashDiaDia>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar a produtividade dia a dia
 */

export function useDashDiaDia<
  TData = Awaited<ReturnType<typeof dashDiaDia>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dashDiaDia>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDashDiaDiaQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Buscar paletes em aberto
 */
export const getPaletesEmAberto = (
  centerId: string,
  data: string,
  processo: string,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<PaleteGetDataTransporteDto[]>(
    {
      url: `/api/produtividade-dash/paletes-em-aberto/${centerId}/${data}/${processo}`,
      method: 'GET',
      signal,
    },
    options,
  );
};

export const getGetPaletesEmAbertoQueryKey = (
  centerId?: string,
  data?: string,
  processo?: string,
) => {
  return [
    `/api/produtividade-dash/paletes-em-aberto/${centerId}/${data}/${processo}`,
  ] as const;
};

export const getGetPaletesEmAbertoQueryOptions = <
  TData = Awaited<ReturnType<typeof getPaletesEmAberto>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  data: string,
  processo: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPaletesEmAberto>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetPaletesEmAbertoQueryKey(centerId, data, processo);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPaletesEmAberto>>
  > = ({ signal }) =>
    getPaletesEmAberto(centerId, data, processo, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(centerId && data && processo),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPaletesEmAberto>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPaletesEmAbertoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPaletesEmAberto>>
>;
export type GetPaletesEmAbertoQueryError = ErrorType<unknown>;

export function useGetPaletesEmAberto<
  TData = Awaited<ReturnType<typeof getPaletesEmAberto>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  data: string,
  processo: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPaletesEmAberto>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPaletesEmAberto>>,
          TError,
          Awaited<ReturnType<typeof getPaletesEmAberto>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPaletesEmAberto<
  TData = Awaited<ReturnType<typeof getPaletesEmAberto>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  data: string,
  processo: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPaletesEmAberto>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPaletesEmAberto>>,
          TError,
          Awaited<ReturnType<typeof getPaletesEmAberto>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPaletesEmAberto<
  TData = Awaited<ReturnType<typeof getPaletesEmAberto>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  data: string,
  processo: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPaletesEmAberto>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Buscar paletes em aberto
 */

export function useGetPaletesEmAberto<
  TData = Awaited<ReturnType<typeof getPaletesEmAberto>>,
  TError = ErrorType<unknown>,
>(
  centerId: string,
  data: string,
  processo: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPaletesEmAberto>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPaletesEmAbertoQueryOptions(
    centerId,
    data,
    processo,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Listar linhas da view vw_produtividade_dash por centro e período
 */
export const listVwProdutividadeDash = (
  params: ListVwProdutividadeDashParams,
  options?: SecondParameter<typeof axiosFetcher>,
  signal?: AbortSignal,
) => {
  return axiosFetcher<void>(
    {
      url: `/api/produtividade-dash/vw-produtividade-dash`,
      method: 'GET',
      params,
      signal,
    },
    options,
  );
};

export const getListVwProdutividadeDashQueryKey = (
  params?: ListVwProdutividadeDashParams,
) => {
  return [
    `/api/produtividade-dash/vw-produtividade-dash`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListVwProdutividadeDashQueryOptions = <
  TData = Awaited<ReturnType<typeof listVwProdutividadeDash>>,
  TError = ErrorType<unknown>,
>(
  params: ListVwProdutividadeDashParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listVwProdutividadeDash>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListVwProdutividadeDashQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listVwProdutividadeDash>>
  > = ({ signal }) => listVwProdutividadeDash(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listVwProdutividadeDash>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListVwProdutividadeDashQueryResult = NonNullable<
  Awaited<ReturnType<typeof listVwProdutividadeDash>>
>;
export type ListVwProdutividadeDashQueryError = ErrorType<unknown>;

export function useListVwProdutividadeDash<
  TData = Awaited<ReturnType<typeof listVwProdutividadeDash>>,
  TError = ErrorType<unknown>,
>(
  params: ListVwProdutividadeDashParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listVwProdutividadeDash>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVwProdutividadeDash>>,
          TError,
          Awaited<ReturnType<typeof listVwProdutividadeDash>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListVwProdutividadeDash<
  TData = Awaited<ReturnType<typeof listVwProdutividadeDash>>,
  TError = ErrorType<unknown>,
>(
  params: ListVwProdutividadeDashParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listVwProdutividadeDash>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVwProdutividadeDash>>,
          TError,
          Awaited<ReturnType<typeof listVwProdutividadeDash>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListVwProdutividadeDash<
  TData = Awaited<ReturnType<typeof listVwProdutividadeDash>>,
  TError = ErrorType<unknown>,
>(
  params: ListVwProdutividadeDashParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listVwProdutividadeDash>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Listar linhas da view vw_produtividade_dash por centro e período
 */

export function useListVwProdutividadeDash<
  TData = Awaited<ReturnType<typeof listVwProdutividadeDash>>,
  TError = ErrorType<unknown>,
>(
  params: ListVwProdutividadeDashParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listVwProdutividadeDash>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosFetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListVwProdutividadeDashQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
