/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import zod from 'zod';


/**
 * @summary Buscar todas as anomalias de produtividade
 */
export const getAnomaliasParams = zod.object({
  "centerId": zod.string()
})

export const getAnomaliasResponseIdMin = -2147483648;
export const getAnomaliasResponseIdMax = 2147483647;export const getAnomaliasResponseDemandaIdMin = -2147483648;
export const getAnomaliasResponseDemandaIdMax = 2147483647;export const getAnomaliasResponseCaixasMin = -2147483648;
export const getAnomaliasResponseCaixasMax = 2147483647;export const getAnomaliasResponseUnidadesMin = -2147483648;
export const getAnomaliasResponseUnidadesMax = 2147483647;export const getAnomaliasResponsePaletesMin = -2147483648;
export const getAnomaliasResponsePaletesMax = 2147483647;export const getAnomaliasResponseEnderecosVisitadoMin = -2147483648;
export const getAnomaliasResponseEnderecosVisitadoMax = 2147483647;export const getAnomaliasResponseProdutividadeMin = -140737488355328;
export const getAnomaliasResponseProdutividadeMax = 140737488355327;export const getAnomaliasResponsePaletesNaDemandaMin = -2147483648;
export const getAnomaliasResponsePaletesNaDemandaMax = 2147483647;

export const getAnomaliasResponseItem = zod.object({
  "id": zod.number().min(getAnomaliasResponseIdMin).max(getAnomaliasResponseIdMax),
  "demandaId": zod.number().min(getAnomaliasResponseDemandaIdMin).max(getAnomaliasResponseDemandaIdMax),
  "centerId": zod.string(),
  "funcionarioId": zod.string(),
  "criadoPorId": zod.string(),
  "inicio": zod.string(),
  "fim": zod.union([zod.string(),zod.null()]),
  "caixas": zod.number().min(getAnomaliasResponseCaixasMin).max(getAnomaliasResponseCaixasMax),
  "unidades": zod.number().min(getAnomaliasResponseUnidadesMin).max(getAnomaliasResponseUnidadesMax),
  "paletes": zod.number().min(getAnomaliasResponsePaletesMin).max(getAnomaliasResponsePaletesMax),
  "enderecosVisitado": zod.number().min(getAnomaliasResponseEnderecosVisitadoMin).max(getAnomaliasResponseEnderecosVisitadoMax),
  "produtividade": zod.number().min(getAnomaliasResponseProdutividadeMin).max(getAnomaliasResponseProdutividadeMax),
  "motivoAnomalia": zod.string(),
  "motivoAnomaliaDescricao": zod.union([zod.string(),zod.null()]),
  "paletesNaDemanda": zod.number().min(getAnomaliasResponsePaletesNaDemandaMin).max(getAnomaliasResponsePaletesNaDemandaMax)
})
export const getAnomaliasResponse = zod.array(getAnomaliasResponseItem)

