/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import zod from 'zod';


/**
 * @summary Cria novo centro
 */
export const criarNovoCentroBody = zod.object({
  "centerId": zod.string().min(1),
  "description": zod.string().min(1),
  "state": zod.string().min(1),
  "cluster": zod.string().min(1)
})

export const criarNovoCentroResponse = zod.object({
  "centerId": zod.string().min(1),
  "description": zod.string().min(1),
  "state": zod.string().min(1),
  "cluster": zod.string().min(1)
})

/**
 * @summary Buscar todos os centros
 */
export const buscarTodosCentrosResponseItem = zod.object({
  "centerId": zod.string().min(1),
  "description": zod.string().min(1),
  "state": zod.string().min(1),
  "cluster": zod.string().min(1)
})
export const buscarTodosCentrosResponse = zod.array(buscarTodosCentrosResponseItem)

/**
 * @summary Buscar um centro
 */
export const centerControllerFindOneParams = zod.object({
  "id": zod.string()
})

export const centerControllerFindOneResponse = zod.object({
  "centerId": zod.string().min(1),
  "description": zod.string().min(1),
  "state": zod.string().min(1),
  "cluster": zod.string().min(1)
})

/**
 * @summary Atualizar um centro
 */
export const centerControllerUpdateParams = zod.object({
  "id": zod.string()
})

export const centerControllerUpdateBody = zod.object({

})

/**
 * @summary Deletar um centro
 */
export const centerControllerRemoveParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Buscar configuração de impressão de mapa por centro e empresa
 */
export const buscarConfiguracaoPorCentroParams = zod.object({
  "centerId": zod.string(),
  "empresa": zod.string()
})

export const buscarConfiguracaoPorCentroResponseDataMaximaPercentualMin = -2147483648;
export const buscarConfiguracaoPorCentroResponseDataMaximaPercentualMax = 2147483647;

export const buscarConfiguracaoPorCentroResponse = zod.object({
  "id": zod.string(),
  "tipoImpressao": zod.enum(['TRANSPORTE', 'CLIENTE']),
  "quebraPalete": zod.boolean(),
  "tipoQuebra": zod.union([zod.enum(['LINHAS', 'PERCENTUAL']),zod.null()]),
  "valorQuebra": zod.union([zod.string(),zod.null()]),
  "separarPaleteFull": zod.boolean(),
  "separarUnidades": zod.boolean(),
  "exibirInfoCabecalho": zod.union([zod.enum(['PRIMEIRO', 'TODOS', 'NENHUM']),zod.null()]),
  "segregarFifo": zod.union([zod.array(zod.string()),zod.null()]),
  "dataMaximaPercentual": zod.number().min(buscarConfiguracaoPorCentroResponseDataMaximaPercentualMin).max(buscarConfiguracaoPorCentroResponseDataMaximaPercentualMax),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "centerId": zod.string(),
  "atribuidoPorId": zod.union([zod.string(),zod.null()]),
  "empresa": zod.string(),
  "tipoImpressaoConferencia": zod.enum(['TRANSPORTE', 'CLIENTE']),
  "ordemConferencia": zod.union([zod.array(zod.string()),zod.null()]),
  "ordemFifo": zod.union([zod.array(zod.string()),zod.null()]),
  "ordemPaletes": zod.union([zod.array(zod.string()),zod.null()]),
  "ordemPicking": zod.union([zod.array(zod.string()),zod.null()]),
  "ordemUnidades": zod.union([zod.array(zod.string()),zod.null()])
})

/**
 * @summary Configurar impressão de mapa por centro e empresa
 */
export const criarConfiguracaoImpressaoParams = zod.object({
  "centerId": zod.string()
})

export const criarConfiguracaoImpressaoBodyDataMaximaPercentualMin = -2147483648;
export const criarConfiguracaoImpressaoBodyDataMaximaPercentualMax = 2147483647;

export const criarConfiguracaoImpressaoBody = zod.object({
  "id": zod.string(),
  "tipoImpressao": zod.enum(['TRANSPORTE', 'CLIENTE']),
  "quebraPalete": zod.boolean(),
  "tipoQuebra": zod.union([zod.enum(['LINHAS', 'PERCENTUAL']),zod.null()]),
  "valorQuebra": zod.union([zod.string(),zod.null()]),
  "separarPaleteFull": zod.boolean(),
  "separarUnidades": zod.boolean(),
  "exibirInfoCabecalho": zod.union([zod.enum(['PRIMEIRO', 'TODOS', 'NENHUM']),zod.null()]),
  "segregarFifo": zod.union([zod.array(zod.string()),zod.null()]),
  "dataMaximaPercentual": zod.number().min(criarConfiguracaoImpressaoBodyDataMaximaPercentualMin).max(criarConfiguracaoImpressaoBodyDataMaximaPercentualMax),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "centerId": zod.string(),
  "atribuidoPorId": zod.union([zod.string(),zod.null()]),
  "empresa": zod.string(),
  "tipoImpressaoConferencia": zod.enum(['TRANSPORTE', 'CLIENTE']),
  "ordemConferencia": zod.union([zod.array(zod.string()),zod.null()]),
  "ordemFifo": zod.union([zod.array(zod.string()),zod.null()]),
  "ordemPaletes": zod.union([zod.array(zod.string()),zod.null()]),
  "ordemPicking": zod.union([zod.array(zod.string()),zod.null()]),
  "ordemUnidades": zod.union([zod.array(zod.string()),zod.null()])
})

export const criarConfiguracaoImpressaoResponseDataMaximaPercentualMin = -2147483648;
export const criarConfiguracaoImpressaoResponseDataMaximaPercentualMax = 2147483647;

export const criarConfiguracaoImpressaoResponse = zod.object({
  "id": zod.string(),
  "tipoImpressao": zod.enum(['TRANSPORTE', 'CLIENTE']),
  "quebraPalete": zod.boolean(),
  "tipoQuebra": zod.union([zod.enum(['LINHAS', 'PERCENTUAL']),zod.null()]),
  "valorQuebra": zod.union([zod.string(),zod.null()]),
  "separarPaleteFull": zod.boolean(),
  "separarUnidades": zod.boolean(),
  "exibirInfoCabecalho": zod.union([zod.enum(['PRIMEIRO', 'TODOS', 'NENHUM']),zod.null()]),
  "segregarFifo": zod.union([zod.array(zod.string()),zod.null()]),
  "dataMaximaPercentual": zod.number().min(criarConfiguracaoImpressaoResponseDataMaximaPercentualMin).max(criarConfiguracaoImpressaoResponseDataMaximaPercentualMax),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "centerId": zod.string(),
  "atribuidoPorId": zod.union([zod.string(),zod.null()]),
  "empresa": zod.string(),
  "tipoImpressaoConferencia": zod.enum(['TRANSPORTE', 'CLIENTE']),
  "ordemConferencia": zod.union([zod.array(zod.string()),zod.null()]),
  "ordemFifo": zod.union([zod.array(zod.string()),zod.null()]),
  "ordemPaletes": zod.union([zod.array(zod.string()),zod.null()]),
  "ordemPicking": zod.union([zod.array(zod.string()),zod.null()]),
  "ordemUnidades": zod.union([zod.array(zod.string()),zod.null()])
})

/**
 * @summary Cria nova regra de motor
 */
export const criarNovaRegraDeMotorBody = zod.object({
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "centerId": zod.string(),
  "enabled": zod.boolean().optional(),
  "conditions": zod.union([zod.union([zod.string(),zod.number(),zod.boolean(),zod.null()]),zod.record(zod.string(), zod.any()),zod.array(zod.any())]),
  "processo": zod.string()
})

export const criarNovaRegraDeMotorResponse = zod.object({
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "centerId": zod.string(),
  "enabled": zod.boolean().optional(),
  "conditions": zod.union([zod.union([zod.string(),zod.number(),zod.boolean(),zod.null()]),zod.record(zod.string(), zod.any()),zod.array(zod.any())]),
  "processo": zod.string()
})

/**
 * @summary Busca todas as regras de motor
 */
export const buscarTodasRegrasDeMotorParams = zod.object({
  "centerId": zod.string()
})

export const buscarTodasRegrasDeMotorResponseIdMin = -2147483648;
export const buscarTodasRegrasDeMotorResponseIdMax = 2147483647;

export const buscarTodasRegrasDeMotorResponseItem = zod.object({
  "id": zod.number().min(buscarTodasRegrasDeMotorResponseIdMin).max(buscarTodasRegrasDeMotorResponseIdMax),
  "name": zod.string(),
  "description": zod.union([zod.string(),zod.null()]),
  "centerId": zod.string(),
  "enabled": zod.boolean(),
  "conditions": zod.union([zod.union([zod.string(),zod.number(),zod.boolean(),zod.null()]),zod.record(zod.string(), zod.any()),zod.array(zod.any())]),
  "createdBy": zod.union([zod.string(),zod.null()]),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "processo": zod.string(),
  "criadoPorId": zod.string()
})
export const buscarTodasRegrasDeMotorResponse = zod.array(buscarTodasRegrasDeMotorResponseItem)

/**
 * @summary Atualiza uma regra de motor
 */
export const atualizarRegraDeMotorParams = zod.object({
  "id": zod.string()
})

export const atualizarRegraDeMotorBodyIdMin = -2147483648;
export const atualizarRegraDeMotorBodyIdMax = 2147483647;

export const atualizarRegraDeMotorBody = zod.object({
  "id": zod.number().min(atualizarRegraDeMotorBodyIdMin).max(atualizarRegraDeMotorBodyIdMax).optional(),
  "name": zod.string().optional(),
  "description": zod.union([zod.string(),zod.null()]).optional(),
  "centerId": zod.string().optional(),
  "enabled": zod.boolean().optional(),
  "conditions": zod.union([zod.union([zod.string(),zod.number(),zod.boolean(),zod.null()]),zod.record(zod.string(), zod.any()),zod.array(zod.any())]).optional(),
  "createdBy": zod.union([zod.string(),zod.null()]).optional(),
  "createdAt": zod.string().optional(),
  "updatedAt": zod.string().optional(),
  "processo": zod.string().optional(),
  "criadoPorId": zod.string().optional()
})

/**
 * @summary Deleta uma regra de motor
 */
export const deletarRegraDeMotorParams = zod.object({
  "id": zod.string()
})

