export enum TipoCorteEnum {
  FALTA_MERCADORIA = 'FALTA_MERCADORIA',
  FALTA_ESPACO = 'FALTA_ESPACO',
  RECUSA_SEFAZ = 'RECUSA_SEFAZ',
  QUALIDADE = 'QUALIDADE',
  DATA_VENCIMENTO = 'DATA_VENCIMENTO'
}