/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import zod from 'zod';


/**
 * @summary Buscar produtos por transporte
 */
export const buscarProdutosPorTransporteParams = zod.object({
  "centerId": zod.string(),
  "transporteId": zod.string()
})

export const buscarProdutosPorTransporteResponseQuantidadeDefault = 0;export const buscarProdutosPorTransporteResponseQuantidadeCortadaDefault = 0;export const buscarProdutosPorTransporteResponseCaixasDefault = 0;export const buscarProdutosPorTransporteResponseCaixasCortadasDefault = 0;export const buscarProdutosPorTransporteResponseTipoDefault = "1";

export const buscarProdutosPorTransporteResponseItem = zod.object({
  "transporte": zod.string(),
  "remessa": zod.string(),
  "cliente": zod.string(),
  "sku": zod.string(),
  "descricao": zod.string(),
  "placa": zod.string(),
  "nomeCliente": zod.string(),
  "lote": zod.string(),
  "quantidade": zod.number().optional(),
  "quantidadeCortada": zod.number().optional(),
  "caixas": zod.number().optional(),
  "caixasCortadas": zod.number().optional(),
  "segmento": zod.string(),
  "tipo": zod.string().default(buscarProdutosPorTransporteResponseTipoDefault)
})
export const buscarProdutosPorTransporteResponse = zod.array(buscarProdutosPorTransporteResponseItem)

/**
 * @summary Criar corte de produto
 */
export const criarCorteDeProdutoParams = zod.object({
  "centerId": zod.string()
})

export const criarCorteDeProdutoBodyUnidadesMin = -2147483648;
export const criarCorteDeProdutoBodyUnidadesMax = 2147483647;export const criarCorteDeProdutoBodyCaixasMin = -2147483648;
export const criarCorteDeProdutoBodyCaixasMax = 2147483647;

export const criarCorteDeProdutoBodyItem = zod.object({
  "produto": zod.string(),
  "lote": zod.string(),
  "unidades": zod.number().min(criarCorteDeProdutoBodyUnidadesMin).max(criarCorteDeProdutoBodyUnidadesMax),
  "motivo": zod.enum(['FALTA_MERCADORIA', 'FALTA_ESPACO', 'RECUSA_SEFAZ']),
  "realizado": zod.boolean().optional(),
  "transporteId": zod.string(),
  "direcao": zod.union([zod.enum(['OPERACIONAL', 'ADMINISTRATIVO']),zod.null()]).optional(),
  "caixas": zod.number().min(criarCorteDeProdutoBodyCaixasMin).max(criarCorteDeProdutoBodyCaixasMax),
  "descricao": zod.union([zod.string(),zod.null()]).optional(),
  "realizadoPorId": zod.union([zod.string(),zod.null()]).optional()
})
export const criarCorteDeProdutoBody = zod.array(criarCorteDeProdutoBodyItem)

/**
 * @summary Buscar todos os cortes de produto
 */
export const buscarTodosOsCortesDeProdutoParams = zod.object({
  "centerId": zod.string()
})

export const buscarTodosOsCortesDeProdutoQueryParams = zod.object({
  "produto": zod.string().optional(),
  "lote": zod.string().optional(),
  "motivo": zod.enum(['FALTA_MERCADORIA', 'FALTA_ESPACO', 'RECUSA_SEFAZ']).optional(),
  "realizado": zod.boolean().optional(),
  "criadoPorId": zod.string().optional(),
  "transporteId": zod.string().optional(),
  "direcao": zod.union([zod.enum(['OPERACIONAL', 'ADMINISTRATIVO']),zod.null()]).optional(),
  "centerId": zod.string().optional(),
  "descricao": zod.union([zod.string(),zod.null()]).optional(),
  "realizadoPorId": zod.union([zod.string(),zod.null()]).optional(),
  "inicio": zod.string().optional(),
  "fim": zod.string().optional()
})

export const buscarTodosOsCortesDeProdutoResponseIdMin = -2147483648;
export const buscarTodosOsCortesDeProdutoResponseIdMax = 2147483647;export const buscarTodosOsCortesDeProdutoResponseUnidadesMin = -2147483648;
export const buscarTodosOsCortesDeProdutoResponseUnidadesMax = 2147483647;export const buscarTodosOsCortesDeProdutoResponseCaixasMin = -2147483648;
export const buscarTodosOsCortesDeProdutoResponseCaixasMax = 2147483647;

export const buscarTodosOsCortesDeProdutoResponseItem = zod.object({
  "id": zod.number().min(buscarTodosOsCortesDeProdutoResponseIdMin).max(buscarTodosOsCortesDeProdutoResponseIdMax),
  "produto": zod.string(),
  "lote": zod.string(),
  "unidades": zod.number().min(buscarTodosOsCortesDeProdutoResponseUnidadesMin).max(buscarTodosOsCortesDeProdutoResponseUnidadesMax),
  "motivo": zod.enum(['FALTA_MERCADORIA', 'FALTA_ESPACO', 'RECUSA_SEFAZ']),
  "realizado": zod.boolean(),
  "criadoEm": zod.string(),
  "atualizadoEm": zod.string(),
  "criadoPorId": zod.string(),
  "transporteId": zod.string(),
  "direcao": zod.union([zod.enum(['OPERACIONAL', 'ADMINISTRATIVO']),zod.null()]),
  "caixas": zod.number().min(buscarTodosOsCortesDeProdutoResponseCaixasMin).max(buscarTodosOsCortesDeProdutoResponseCaixasMax),
  "centerId": zod.string(),
  "descricao": zod.union([zod.string(),zod.null()]),
  "realizadoPorId": zod.union([zod.string(),zod.null()])
})
export const buscarTodosOsCortesDeProdutoResponse = zod.array(buscarTodosOsCortesDeProdutoResponseItem)

/**
 * @summary Confirmar corte de produto
 */
export const confirmarCorteDeProdutoParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Deletar corte de produto
 */
export const deletarCorteDeProdutoParams = zod.object({
  "id": zod.string()
})

/**
 * @summary Confirmar corte de produto por transporte
 */
export const confirmarCorteDeProdutoPorTransporteParams = zod.object({
  "transporteId": zod.string()
})

