/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, delay, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type {
  OverViewProdutividadeDataDto,
  PausaGeralGetDataDto,
  ProdutividadeGetDataDto,
  ProdutividadeWithPausaAndPaleteDto,
} from '../../model';

export const getBuscarPausasAtivasResponseMock = (): PausaGeralGetDataDto[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: -2147483648, max: 2147483647 }),
    inicio: faker.string.alpha({ length: { min: 10, max: 20 } }),
    fim: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    motivo: faker.string.alpha({ length: { min: 10, max: 20 } }),
    centerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    processo: faker.helpers.arrayElement([
      'SEPARACAO',
      'CARREGAMENTO',
      'CONFERENCIA',
    ] as const),
    turno: faker.helpers.arrayElement([
      'MANHA',
      'TARDE',
      'NOITE',
      'INTERMEDIARIO',
      'ADMINISTRATIVO',
    ] as const),
    registradoPorId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    criadoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
    atualizadoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
    segmento: faker.string.alpha({ length: { min: 10, max: 20 } }),
  }));

export const getGetProdutividadeResponseMock = (): ProdutividadeGetDataDto[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    idDemanda: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    empresa: faker.string.alpha({ length: { min: 10, max: 20 } }),
    centerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    processo: faker.string.alpha({ length: { min: 10, max: 20 } }),
    segmento: faker.string.alpha({ length: { min: 10, max: 20 } }),
    inicio: faker.string.alpha({ length: { min: 10, max: 20 } }),
    fim: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    cadastradoPorId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    turno: faker.string.alpha({ length: { min: 10, max: 20 } }),
    funcionarioId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    nomeFuncionario: faker.string.alpha({ length: { min: 10, max: 20 } }),
    statusDemanda: faker.string.alpha({ length: { min: 10, max: 20 } }),
    caixas: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    unidades: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    paletes: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    visitas: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    pausas: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    tempoTrabalhado: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    tempoPausas: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    tempoTotal: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    produtividade: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    obs: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
  }));

export const getOverViewProdutividadeResponseMock = (
  overrideResponse: Partial<OverViewProdutividadeDataDto> = {},
): OverViewProdutividadeDataDto => ({
  processos: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  emAndamento: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  concluidos: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  totalCaixas: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  totalUnidades: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  produtividade: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  ...overrideResponse,
});

export const getGetProdutividadeByIdResponseMock = (
  overrideResponse: Partial<ProdutividadeWithPausaAndPaleteDto> = {},
): ProdutividadeWithPausaAndPaleteDto => ({
  idDemanda: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  empresa: faker.string.alpha({ length: { min: 10, max: 20 } }),
  centerId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  processo: faker.string.alpha({ length: { min: 10, max: 20 } }),
  segmento: faker.string.alpha({ length: { min: 10, max: 20 } }),
  inicio: faker.string.alpha({ length: { min: 10, max: 20 } }),
  fim: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    null,
  ]),
  cadastradoPorId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  turno: faker.string.alpha({ length: { min: 10, max: 20 } }),
  funcionarioId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  nomeFuncionario: faker.string.alpha({ length: { min: 10, max: 20 } }),
  statusDemanda: faker.string.alpha({ length: { min: 10, max: 20 } }),
  caixas: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  unidades: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  paletes: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  visitas: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  pausas: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  tempoTrabalhado: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  tempoPausas: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  tempoTotal: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  produtividade: faker.number.float({
    min: undefined,
    max: undefined,
    fractionDigits: 2,
  }),
  obs: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    null,
  ]),
  listaPausas: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    inicio: faker.string.alpha({ length: { min: 10, max: 20 } }),
    fim: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    motivo: faker.string.alpha({ length: { min: 10, max: 20 } }),
    descricao: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    demandaId: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    registradoPorId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  })),
  listaPaletes: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    empresa: faker.string.alpha({ length: { min: 10, max: 20 } }),
    quantidadeCaixas: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    quantidadeUnidades: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    quantidadePaletes: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    enderecoVisitado: faker.number.float({
      min: undefined,
      max: undefined,
      fractionDigits: 2,
    }),
    segmento: faker.string.alpha({ length: { min: 10, max: 20 } }),
    transporteId: faker.string.alpha({ length: { min: 10, max: 20 } }),
    inicio: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    fim: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    tipoProcesso: faker.string.alpha({ length: { min: 10, max: 20 } }),
    criadoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
    atualizadoEm: faker.string.alpha({ length: { min: 10, max: 20 } }),
    demandaId: faker.helpers.arrayElement([
      faker.number.float({ min: undefined, max: undefined, fractionDigits: 2 }),
      null,
    ]),
    status: faker.string.alpha({ length: { min: 10, max: 20 } }),
    validado: faker.datatype.boolean(),
    criadoPorId: faker.string.alpha({ length: { min: 10, max: 20 } }),
  })),
  ...overrideResponse,
});

export const getCriarDemandaProdutividadeMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/gestao-produtividade',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getFinalizarPaleteProdutividadeMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/gestao-produtividade/finalizar-palete',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getAddPausaIndividualMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/gestao-produtividade/add-pausa-individual/:paleteId',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getFinalizarPausaIndividualMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/gestao-produtividade/finalizar-pausa-individual/:paleteId',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getAddPausaGeralMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/gestao-produtividade/add-pausa-geral',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getFinalizarPausaGeralMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/gestao-produtividade/finalizar-pausa-geral/:centerId/:segmento/:turno/:processo',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getBuscarPausasAtivasMockHandler = (
  overrideResponse?:
    | PausaGeralGetDataDto[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PausaGeralGetDataDto[]> | PausaGeralGetDataDto[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/gestao-produtividade/buscar-pausas-ativas/:centerId',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getBuscarPausasAtivasResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetProdutividadeMockHandler = (
  overrideResponse?:
    | ProdutividadeGetDataDto[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProdutividadeGetDataDto[]> | ProdutividadeGetDataDto[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/gestao-produtividade/get-produtividade/:centerId',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetProdutividadeResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getOverViewProdutividadeMockHandler = (
  overrideResponse?:
    | OverViewProdutividadeDataDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<OverViewProdutividadeDataDto>
        | OverViewProdutividadeDataDto),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/gestao-produtividade/over-view-produtividade/:centerId/:processo/:dataRegistro',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getOverViewProdutividadeResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getGetProdutividadeByIdMockHandler = (
  overrideResponse?:
    | ProdutividadeWithPausaAndPaleteDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<ProdutividadeWithPausaAndPaleteDto>
        | ProdutividadeWithPausaAndPaleteDto),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/gestao-produtividade/get-produtividade-by-id/:idDemanda',
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === 'function'
              ? await overrideResponse(info)
              : overrideResponse
            : getGetProdutividadeByIdResponseMock(),
        ),
        { status: 200, headers: { 'Content-Type': 'application/json' } },
      );
    },
    options,
  );
};

export const getDeletarDemandaMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/api/gestao-produtividade/deletar-demanda/:paleteId',
    async (info) => {
      await delay(1000);
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }
      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getGestaoProdutividadeMock = () => [
  getCriarDemandaProdutividadeMockHandler(),
  getFinalizarPaleteProdutividadeMockHandler(),
  getAddPausaIndividualMockHandler(),
  getFinalizarPausaIndividualMockHandler(),
  getAddPausaGeralMockHandler(),
  getFinalizarPausaGeralMockHandler(),
  getBuscarPausasAtivasMockHandler(),
  getGetProdutividadeMockHandler(),
  getOverViewProdutividadeMockHandler(),
  getGetProdutividadeByIdMockHandler(),
  getDeletarDemandaMockHandler(),
];
