/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API de Gestão de Devolução e Produtividade
 * Documentação da API responsável por: gestão de produtividade, montagem e impressão de mapas de separação, sistema de devolução de estoque e contagem de inventário.
 * OpenAPI spec version: 1.0
 */
import zod from 'zod';


/**
 * @summary Buscar informações da viagem
 */
export const getInfoByViagemIdParams = zod.object({
  "viagemId": zod.string()
})

export const getInfoByViagemIdResponsePlacaMin = 7;
export const getInfoByViagemIdResponsePlacaMax = 7;export const getInfoByViagemIdResponseNotasItemItensItemDescricaoRegExp = new RegExp('^(?!produto não encontrado$).*$');


export const getInfoByViagemIdResponse = zod.object({
  "idViagem": zod.string(),
  "placa": zod.string().min(getInfoByViagemIdResponsePlacaMin).max(getInfoByViagemIdResponsePlacaMax),
  "motorista": zod.string(),
  "transportadora": zod.string(),
  "notas": zod.array(zod.object({
  "tipo": zod.enum(['DEVOLUCAO', 'DEVOLUCAO_PARCIAL', 'REENTREGA']),
  "notaFiscal": zod.string(),
  "notaFiscalParcial": zod.union([zod.string(),zod.null()]).optional(),
  "motivoDevolucao": zod.string(),
  "descMotivoDevolucao": zod.union([zod.string(),zod.null()]),
  "operador": zod.union([zod.string(),zod.null()]).optional(),
  "empresa": zod.string(),
  "itens": zod.array(zod.object({
  "sku": zod.string(),
  "descricao": zod.string().regex(getInfoByViagemIdResponseNotasItemItensItemDescricaoRegExp),
  "pesoLiquido": zod.number(),
  "quantidadeRavex": zod.number(),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "fatorConversao": zod.number(),
  "unPorCaixa": zod.number(),
  "decimal": zod.number()
}))
}))
})

/**
 * @summary Adicionar demanda
 */
export const addDemandaDevolucaoParams = zod.object({
  "centerId": zod.string()
})

export const addDemandaDevolucaoBody = zod.object({
  "placa": zod.string().describe('Placa do veiculo'),
  "motorista": zod.string().describe('Nome Motorista'),
  "idTransportadora": zod.string().describe('Nome Transportadora'),
  "viagemId": zod.string().describe('Id Viagem Ravex'),
  "telefone": zod.string().describe('Telefone Motorista'),
  "cargaSegregada": zod.boolean().describe('Existe carga segregada'),
  "paletesRetorno": zod.number().describe('Quantos paletes estão sendo retornados'),
  "doca": zod.string().describe('Qual doca o carro vai ser descarregado')
})

export const addDemandaDevolucaoResponse = zod.string()

/**
 * @summary Listar demandas de devolução
 */
export const listarDemandasDevolucaoParams = zod.object({
  "centerId": zod.string(),
  "data": zod.string()
})

export const listarDemandasDevolucaoResponseIdMin = -2147483648;
export const listarDemandasDevolucaoResponseIdMax = 2147483647;export const listarDemandasDevolucaoResponseQuantidadePaletesMinOne = -2147483648;
export const listarDemandasDevolucaoResponseQuantidadePaletesMaxOne = 2147483647;

export const listarDemandasDevolucaoResponseItem = zod.object({
  "id": zod.number().min(listarDemandasDevolucaoResponseIdMin).max(listarDemandasDevolucaoResponseIdMax),
  "placa": zod.string(),
  "motorista": zod.string(),
  "idTransportadora": zod.union([zod.string(),zod.null()]),
  "telefone": zod.union([zod.string(),zod.null()]),
  "cargaSegregada": zod.boolean(),
  "quantidadePaletes": zod.union([zod.number().min(listarDemandasDevolucaoResponseQuantidadePaletesMinOne).max(listarDemandasDevolucaoResponseQuantidadePaletesMaxOne),zod.null()]),
  "doca": zod.union([zod.string(),zod.null()]),
  "centerId": zod.string(),
  "adicionadoPorId": zod.string(),
  "conferenteId": zod.union([zod.string(),zod.null()]),
  "criadoEm": zod.string(),
  "atualizadoEm": zod.string(),
  "status": zod.enum(['AGUARDANDO_LIBERACAO', 'AGUARDANDO_CONFERENCIA', 'EM_CONFERENCIA', 'CONFERENCIA_FINALIZADA', 'FINALIZADO', 'CANCELADO']),
  "fechouComAnomalia": zod.union([zod.boolean(),zod.null()]),
  "liberadoParaConferenciaEm": zod.union([zod.string(),zod.null()]),
  "inicioConferenciaEm": zod.union([zod.string(),zod.null()]),
  "fimConferenciaEm": zod.union([zod.string(),zod.null()]),
  "finalizadoEm": zod.union([zod.string(),zod.null()]),
  "senha": zod.string(),
  "viagemId": zod.union([zod.string(),zod.null()])
})
export const listarDemandasDevolucaoResponse = zod.array(listarDemandasDevolucaoResponseItem)

/**
 * @summary Buscar demanda de devolução por ID
 */
export const getDemandaByIdDevolucaoParams = zod.object({
  "id": zod.string()
})

export const getDemandaByIdDevolucaoResponseIdMin = -2147483648;
export const getDemandaByIdDevolucaoResponseIdMax = 2147483647;export const getDemandaByIdDevolucaoResponseQuantidadePaletesMinOne = -2147483648;
export const getDemandaByIdDevolucaoResponseQuantidadePaletesMaxOne = 2147483647;

export const getDemandaByIdDevolucaoResponse = zod.object({
  "id": zod.number().min(getDemandaByIdDevolucaoResponseIdMin).max(getDemandaByIdDevolucaoResponseIdMax),
  "placa": zod.string(),
  "motorista": zod.string(),
  "idTransportadora": zod.union([zod.string(),zod.null()]),
  "telefone": zod.union([zod.string(),zod.null()]),
  "cargaSegregada": zod.boolean(),
  "quantidadePaletes": zod.union([zod.number().min(getDemandaByIdDevolucaoResponseQuantidadePaletesMinOne).max(getDemandaByIdDevolucaoResponseQuantidadePaletesMaxOne),zod.null()]),
  "doca": zod.union([zod.string(),zod.null()]),
  "centerId": zod.string(),
  "adicionadoPorId": zod.string(),
  "conferenteId": zod.union([zod.string(),zod.null()]),
  "criadoEm": zod.string(),
  "atualizadoEm": zod.string(),
  "status": zod.enum(['AGUARDANDO_LIBERACAO', 'AGUARDANDO_CONFERENCIA', 'EM_CONFERENCIA', 'CONFERENCIA_FINALIZADA', 'FINALIZADO', 'CANCELADO']),
  "fechouComAnomalia": zod.union([zod.boolean(),zod.null()]),
  "liberadoParaConferenciaEm": zod.union([zod.string(),zod.null()]),
  "inicioConferenciaEm": zod.union([zod.string(),zod.null()]),
  "fimConferenciaEm": zod.union([zod.string(),zod.null()]),
  "finalizadoEm": zod.union([zod.string(),zod.null()]),
  "senha": zod.string(),
  "viagemId": zod.union([zod.string(),zod.null()])
})

/**
 * @summary Adicionar nota de devolução
 */
export const addNotaDevolucaoBody = zod.object({
  "empresa": zod.enum(['ITB', 'LDB', 'DPA']),
  "devolucaoDemandaId": zod.number(),
  "notaFiscal": zod.string(),
  "motivoDevolucao": zod.string(),
  "descMotivoDevolucao": zod.string(),
  "nfParcial": zod.string().optional(),
  "idViagemRavex": zod.string().optional(),
  "tipo": zod.enum(['DEVOLUCAO', 'DEVOLUCAO_PARCIAL', 'REENTREGA']),
  "itens": zod.array(zod.object({
  "sku": zod.string(),
  "descricao": zod.string(),
  "lote": zod.string().optional(),
  "fabricacao": zod.number().optional(),
  "sif": zod.string().optional(),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "avariaCaixas": zod.number().optional(),
  "tipo": zod.enum(['DEVOLUCAO', 'DEVOLUCAO_PARCIAL', 'REENTREGA']),
  "demandaId": zod.number()
}))
})

export const addNotaDevolucaoResponse = zod.string()

/**
 * @summary Buscar nota de devolução por NF e ID da viagem
 */
export const getNotaByNfAndIdViagemDevolucaoParams = zod.object({
  "nf": zod.string(),
  "idViagem": zod.string()
})

export const getNotaByNfAndIdViagemDevolucaoResponse = zod.string()

/**
 * @summary Buscar notas de devolução por ID da demanda
 */
export const getNotasByDemandaIdDevolucaoParams = zod.object({
  "demandaId": zod.string()
})

export const getNotasByDemandaIdDevolucaoResponseIdMin = -2147483648;
export const getNotasByDemandaIdDevolucaoResponseIdMax = 2147483647;export const getNotasByDemandaIdDevolucaoResponseDevolucaoDemandaIdMin = -2147483648;
export const getNotasByDemandaIdDevolucaoResponseDevolucaoDemandaIdMax = 2147483647;

export const getNotasByDemandaIdDevolucaoResponseItem = zod.object({
  "id": zod.number().min(getNotasByDemandaIdDevolucaoResponseIdMin).max(getNotasByDemandaIdDevolucaoResponseIdMax),
  "empresa": zod.enum(['ITB', 'LDB', 'DPA']),
  "devolucaoDemandaId": zod.number().min(getNotasByDemandaIdDevolucaoResponseDevolucaoDemandaIdMin).max(getNotasByDemandaIdDevolucaoResponseDevolucaoDemandaIdMax),
  "notaFiscal": zod.string(),
  "motivoDevolucao": zod.string(),
  "descMotivoDevolucao": zod.union([zod.string(),zod.null()]),
  "nfParcial": zod.union([zod.string(),zod.null()]),
  "idViagemRavex": zod.union([zod.string(),zod.null()]),
  "criadoEm": zod.string(),
  "atualizadoEm": zod.string(),
  "tipo": zod.enum(['DEVOLUCAO', 'DEVOLUCAO_PARCIAL', 'REENTREGA'])
})
export const getNotasByDemandaIdDevolucaoResponse = zod.array(getNotasByDemandaIdDevolucaoResponseItem)

/**
 * @summary Liberar demanda para conferência
 */
export const liberarDemandaDevolucaoParams = zod.object({
  "demandaId": zod.string()
})

export const liberarDemandaDevolucaoResponse = zod.string()

/**
 * @summary Remover nota de devolução
 */
export const removerNotaDevolucaoParams = zod.object({
  "id": zod.string()
})

export const removerNotaDevolucaoResponse = zod.string()

/**
 * @summary Deletar demanda de devolução
 */
export const deletarDemandaDevolucaoParams = zod.object({
  "id": zod.string()
})

export const deletarDemandaDevolucaoResponse = zod.string()

/**
 * @summary Reabrir demanda de devolução
 */
export const reabrirDemandaDevolucaoParams = zod.object({
  "id": zod.string()
})

export const reabrirDemandaDevolucaoResponse = zod.string()

/**
 * @summary Finalizar demanda de devolução
 */
export const finalizarDemandaDevolucaoParams = zod.object({
  "id": zod.string()
})

export const finalizarDemandaDevolucaoResponse = zod.string()

/**
 * @summary Buscar resultado de demanda de devolução
 */
export const getResultadoDemandaDevolucaoParams = zod.object({
  "id": zod.string()
})

export const getResultadoDemandaDevolucaoResponse = zod.object({
  "demandaId": zod.number(),
  "placa": zod.string(),
  "motorista": zod.string(),
  "transportadora": zod.string(),
  "doca": zod.string(),
  "criadoPor": zod.string(),
  "conferente": zod.string(),
  "criadoEm": zod.string(),
  "LiberadoParaConferenciaEm": zod.string(),
  "InicioConferenciaEm": zod.string(),
  "FimConferenciaEm": zod.string(),
  "FinalizadoEm": zod.string(),
  "Status": zod.string(),
  "FechouComAnomalia": zod.boolean(),
  "notas": zod.array(zod.object({
  "notaFiscal": zod.string(),
  "notaFiscalParcial": zod.string(),
  "descMotivoDevolucao": zod.string(),
  "viagemId": zod.string(),
  "tipo": zod.enum(['DEVOLUCAO', 'DEVOLUCAO_PARCIAL', 'REENTREGA'])
})),
  "itens": zod.array(zod.object({
  "sku": zod.string(),
  "descricao": zod.string(),
  "quantidadeCaixasContabil": zod.number(),
  "quantidadeUnidadesContabil": zod.number(),
  "quantidadeCaixasFisico": zod.number(),
  "quantidadeUnidadesFisico": zod.number(),
  "saldoCaixas": zod.number(),
  "saldoUnidades": zod.number(),
  "avariaCaixas": zod.number(),
  "avariaUnidades": zod.number()
}))
})

